import { db } from "./index";
import { quizQuestionsTable, practiceExamQuestionsTable } from "./schema";
import { eq, inArray } from "drizzle-orm";

async function expandPracticeExams() {
  console.log("Expanding practice exams to 25 questions per topic...\n");

  // ===========================================================================
  // BRAIN STRUCTURES (topic 16, exam 16) — 15 additional questions
  // ===========================================================================
  const brainQ: (typeof quizQuestionsTable.$inferInsert)[] = [
    {
      topicId: 16,
      question: "The hippocampus is critical for which type of memory?",
      optionA: "Procedural (implicit) motor memory",
      optionB: "Working memory — active maintenance of information",
      optionC: "New episodic memory consolidation (anterograde declarative memory)",
      optionD: "Priming and perceptual learning",
      correctAnswer: "C",
      explanation: "The hippocampus is essential for consolidating new explicit (declarative) memories — episodic and semantic. Patient H.M., who had bilateral hippocampal removal, could not form any new declarative memories (severe anterograde amnesia) yet retained intact procedural memory, working memory, and remote pre-surgical memories.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "Which structure is the largest commissure connecting the two cerebral hemispheres?",
      optionA: "Anterior commissure",
      optionB: "Posterior commissure",
      optionC: "Massa intermedia (interthalamic adhesion)",
      optionD: "Corpus callosum",
      correctAnswer: "D",
      explanation: "The corpus callosum is the largest commissure — ~200 million axons connecting homotopic and heterotopic cortical areas bilaterally. Callosotomy ('split-brain') for epilepsy creates hemispheric disconnection syndrome. The anterior commissure connects olfactory and anterior temporal areas; the posterior commissure connects midbrain structures.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "Broca's area is located in which region and is responsible for what?",
      optionA: "Left superior temporal gyrus — auditory language comprehension",
      optionB: "Left inferior frontal gyrus — speech production and expressive language",
      optionC: "Left angular gyrus — reading and writing integration",
      optionD: "Right prefrontal cortex — prosody and emotional language",
      correctAnswer: "B",
      explanation: "Broca's area (Brodmann areas 44 and 45 — pars opercularis and triangularis of the left inferior frontal gyrus) is responsible for speech production. Damage causes Broca's aphasia: non-fluent, effortful, telegraphic speech with relatively preserved comprehension. The classic lesion site is the posterior left inferior frontal gyrus.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "The thalamus functions as the primary relay station for all sensory information EXCEPT which sense?",
      optionA: "Vision (routed through the lateral geniculate nucleus)",
      optionB: "Hearing (routed through the medial geniculate nucleus)",
      optionC: "Olfaction (projects directly to olfactory cortex without thalamic relay)",
      optionD: "Somatosensation (routed through VPL/VPM nuclei)",
      correctAnswer: "C",
      explanation: "Olfaction is the only sensory modality that does NOT relay through the thalamus before reaching cortex. Olfactory information projects directly from the olfactory bulb to the piriform cortex and amygdala via the olfactory tract. All other senses (vision → LGN, audition → MGN, somatosensation → VPL/VPM) relay through the thalamus.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "Bilateral amygdala damage (as in Urbach-Wiethe disease) classically produces:",
      optionA: "Severe anterograde amnesia for all declarative memories",
      optionB: "Impaired fear conditioning, fearlessness, and failure to recognize fearful facial expressions",
      optionC: "Hyperphagia, hypersexuality, and visual agnosia (Kluver-Bucy syndrome)",
      optionD: "Loss of emotional expression with intact emotional experience",
      correctAnswer: "B",
      explanation: "The amygdala is the key structure for fear processing — fear conditioning, enhancing emotional memories, and recognizing fearful expressions. Bilateral amygdala damage produces fearlessness (approach behavior toward threats), impaired recognition of fear/anger in faces, and deficient fear conditioning. Note: Kluver-Bucy syndrome requires broader bilateral temporal lobe damage beyond just the amygdala.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "The dorsolateral prefrontal cortex (DLPFC) is most closely associated with which cognitive function?",
      optionA: "Emotional regulation and reward valuation",
      optionB: "Working memory and executive functions (planning, monitoring, cognitive flexibility)",
      optionC: "Primary language comprehension and semantic processing",
      optionD: "Spatial navigation and memory consolidation",
      correctAnswer: "B",
      explanation: "The DLPFC (Brodmann areas 9 and 46) is the key region for working memory — active maintenance and manipulation of information — and broader executive functions. It has the highest density of dopamine D1 receptors in the cortex. Reduced DLPFC activation is observed in ADHD during executive tasks and in schizophrenia (associated with negative symptoms and cognitive deficits).",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "Damage to the right parietal lobe classically produces which syndrome?",
      optionA: "Wernicke's aphasia — fluent speech with impaired comprehension",
      optionB: "Left hemispatial neglect — ignoring the left side of space",
      optionC: "Gerstmann syndrome — agraphia, acalculia, finger agnosia",
      optionD: "Broca's aphasia — non-fluent speech with intact comprehension",
      correctAnswer: "B",
      explanation: "The right parietal lobe (especially the temporoparietal junction and superior parietal lobule) is dominant for spatial attention across both hemifields. Right parietal lesions cause left hemispatial neglect — patients fail to attend to stimuli in the left hemispace. Gerstmann syndrome is associated with left angular gyrus damage. Aphasia syndromes involve left hemisphere language areas.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "In the basal ganglia circuit, the direct pathway's net effect on movement is:",
      optionA: "Suppression of movement by increasing thalamic inhibition",
      optionB: "Facilitation of movement by releasing the thalamus from inhibition",
      optionC: "No net effect — the direct pathway only modulates movement speed",
      optionD: "Suppression of movement by increasing striatal dopamine",
      correctAnswer: "B",
      explanation: "The direct pathway (striatum → GPi/SNr → thalamus → cortex): striatal D1 neurons inhibit GPi/SNr, which normally inhibits the thalamus. Activation of the direct pathway → GPi/SNr inhibited → thalamus released from inhibition → increased cortical activation → movement facilitated. The indirect pathway has the opposite effect (suppresses movement). Dopamine from SNc activates D1 (direct) and inhibits D2 (indirect), promoting movement.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "Wernicke's area is located in which region and what deficit results from its damage?",
      optionA: "Left inferior frontal gyrus — non-fluent speech with intact comprehension",
      optionB: "Left posterior superior temporal gyrus — fluent speech with impaired comprehension ('word salad')",
      optionC: "Left angular gyrus — inability to read or write",
      optionD: "Right temporal lobe — impaired emotional prosody",
      correctAnswer: "B",
      explanation: "Wernicke's area (Brodmann area 22 — left posterior superior temporal gyrus) mediates auditory language comprehension. Wernicke's aphasia features: fluent, melodic speech with poor content (paraphasias, neologisms, 'word salad'), severely impaired comprehension, and often poor repetition. Patients are unaware of their errors (anosognosia). Contrast with Broca's aphasia — non-fluent but comprehension relatively preserved.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "The hypothalamus is BEST described as the master regulator of:",
      optionA: "Explicit memory consolidation and spatial navigation",
      optionB: "Voluntary motor initiation and fine motor coordination",
      optionC: "Autonomic homeostasis, endocrine function, circadian rhythms, feeding, thirst, and temperature",
      optionD: "Attention allocation and sensory filtering across cortical regions",
      correctAnswer: "C",
      explanation: "The hypothalamus integrates and regulates: autonomic nervous system (sympathetic/parasympathetic balance), endocrine function (controls pituitary via releasing hormones), circadian rhythms (suprachiasmatic nucleus — the body's 'master clock'), feeding/satiety, thirst/water balance, thermoregulation, and reproductive behavior. It connects the nervous and endocrine systems as the 'head ganglion' of the autonomic nervous system.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "The angular gyrus lesion (Gerstmann syndrome) is characterized by which four features?",
      optionA: "Agraphia, acalculia, left-right disorientation, and finger agnosia",
      optionB: "Aphasia, alexia, acalculia, and constructional apraxia",
      optionC: "Visual agnosia, prosopagnosia, alexia, and anomia",
      optionD: "Hemispatial neglect, anosognosia, dressing apraxia, and constructional apraxia",
      correctAnswer: "A",
      explanation: "Gerstmann syndrome results from left angular gyrus damage (dominant parietal-temporal-occipital junction). The four features: Agraphia (cannot write), Acalculia (cannot calculate), Left-Right disorientation (confusion of left and right sides), and Finger agnosia (cannot identify fingers). The angular gyrus integrates visual, auditory, and somatosensory information — critical for reading, writing, and number processing.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "Patient H.M. could learn new motor skills (mirror drawing) despite severe amnesia. This finding best demonstrates:",
      optionA: "The hippocampus is not needed for any type of long-term learning",
      optionB: "The double dissociation between declarative memory (hippocampus-dependent) and procedural memory (basal ganglia/cerebellum-dependent)",
      optionC: "Working memory is sufficient to support motor skill learning",
      optionD: "The amygdala compensates for hippocampal loss during procedural learning",
      correctAnswer: "B",
      explanation: "H.M.'s preserved procedural learning (mirror drawing, rotary pursuit tasks) despite inability to form new declarative memories demonstrates a classic double dissociation: declarative (explicit) memory depends on the hippocampus and medial temporal lobe, while procedural (implicit/skill) memory depends on the basal ganglia, cerebellum, and motor cortex — separate neural systems for different memory types.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "The insular cortex (insula) is primarily associated with which functions?",
      optionA: "Primary visual processing and object recognition",
      optionB: "Interoception, pain processing, disgust, taste (primary gustatory cortex), and empathy",
      optionC: "Long-term memory consolidation and fear conditioning",
      optionD: "Language production and phonological processing",
      correctAnswer: "B",
      explanation: "The insular cortex processes internal body states (interoception), pain signals, and the sensation of disgust. The posterior insula is the primary gustatory cortex (taste). It also mediates empathy by linking bodily sensations to emotional experience — key for 'feeling what others feel.' Left insula damage can cause aphasia; damage impairs pain perception and disgust recognition.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "The cerebellum receives climbing fiber input exclusively from which brainstem nucleus?",
      optionA: "Pontine nuclei",
      optionB: "Red nucleus",
      optionC: "Inferior olivary nucleus",
      optionD: "Vestibular nuclei",
      correctAnswer: "C",
      explanation: "Climbing fibers originate exclusively from the contralateral inferior olivary nucleus (inferior olive) in the medulla. Each climbing fiber synapses on one Purkinje cell with powerful excitatory input — thought to encode motor error signals (teaching signals for cerebellar learning). Mossy fibers carry all other input (from spinal cord, pontine nuclei relaying cortical signals, and vestibular nuclei) and synapse on granule cells.",
      examOnly: true,
    },
    {
      topicId: 16,
      question: "Which cerebral lobe contains the primary auditory cortex, and where is it located anatomically?",
      optionA: "Frontal lobe — posterior inferior frontal gyrus",
      optionB: "Parietal lobe — postcentral gyrus",
      optionC: "Temporal lobe — superior temporal gyrus (Heschl's gyri, Brodmann areas 41/42)",
      optionD: "Occipital lobe — calcarine cortex",
      correctAnswer: "C",
      explanation: "The primary auditory cortex (Brodmann areas 41 and 42 — Heschl's transverse gyri) is located on the superior surface of the temporal lobe, buried within the lateral (Sylvian) fissure. It is tonotopically organized (frequency maps). Surrounding it is the secondary auditory cortex and, in the left hemisphere posteriorly, Wernicke's area for language comprehension.",
      examOnly: true,
    },
  ];

  // ===========================================================================
  // CRANIAL NERVES (topic 17, exam 17) — 15 additional questions
  // ===========================================================================
  const cranialQ: (typeof quizQuestionsTable.$inferInsert)[] = [
    {
      topicId: 17,
      question: "Which cranial nerve carries the special sense of smell, and what is unique about its cortical projection?",
      optionA: "CN I — it relays through the thalamus before reaching olfactory cortex",
      optionB: "CN I — it is the only sensory cranial nerve that projects directly to cortex WITHOUT thalamic relay",
      optionC: "CN V — the trigeminal nerve carries olfactory information from the nasal mucosa",
      optionD: "CN VII — the facial nerve carries smell via the chorda tympani branch",
      correctAnswer: "B",
      explanation: "CN I (Olfactory nerve) is unique — it is the only sensory cranial nerve that does NOT relay through the thalamus. Olfactory receptor neurons project directly from the nasal epithelium (through the cribriform plate) to the olfactory bulb, then to the piriform cortex and amygdala via the olfactory tract. This explains why odors powerfully trigger emotional memories (amygdala connection).",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "A patient has difficulty looking down stairs and tilts their head to compensate. Which cranial nerve palsy is most likely?",
      optionA: "CN III — loss of most extraocular movements",
      optionB: "CN IV — superior oblique palsy causing inability to depress and intort the eye",
      optionC: "CN VI — lateral rectus palsy causing inability to abduct the eye",
      optionD: "CN VII — facial nerve palsy causing eyelid weakness",
      correctAnswer: "B",
      explanation: "CN IV (Trochlear nerve) innervates the superior oblique muscle, which depresses and intorts the eye (especially when the eye is adducted). CN IV palsy makes it hard to look down and inward — so descending stairs is difficult. Patients typically tilt their head toward the opposite shoulder to compensate. CN IV has the longest intracranial course and decussates in the dorsal midbrain.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "In the pupillary light reflex, the afferent limb travels via CN II and the efferent limb via CN III. A relative afferent pupillary defect (RAPD) indicates:",
      optionA: "An efferent CN III lesion causing the pupil to fail to constrict on the affected side",
      optionB: "An afferent CN II lesion causing reduced direct response with preserved consensual response when the affected eye is illuminated",
      optionC: "Bilateral CN III lesions causing loss of both direct and consensual responses",
      optionD: "A ciliary ganglion lesion causing tonic pupil",
      correctAnswer: "B",
      explanation: "RAPD (Marcus Gunn pupil) results from an afferent (CN II) defect — the damaged optic nerve sends a weaker signal. When light shines in the affected eye: reduced direct response AND reduced consensual response in the other eye (because the bilateral projection from pretectal nucleus is driven by the weaker signal). The swinging flashlight test reveals RAPD. CN III lesion affects efferent — causes dilated, non-reactive pupil.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "Bell's palsy (peripheral CN VII palsy) is distinguished from a central (UMN) facial palsy by which key feature?",
      optionA: "Bell's palsy only affects the lower face; central palsy affects both upper and lower face",
      optionB: "Bell's palsy causes complete ipsilateral facial paralysis including the forehead; central palsy spares the forehead",
      optionC: "Central palsy includes loss of taste; Bell's palsy does not",
      optionD: "Bell's palsy is always painful; central palsy is never painful",
      correctAnswer: "B",
      explanation: "The FOREHEAD is the key distinguishing feature. Bell's palsy (LMN/peripheral): complete ipsilateral paralysis including forehead (frontalis) — because all cortical input to the ipsilateral CN VII nucleus is lost. Central (UMN) facial palsy: forehead SPARED because the upper face receives bilateral cortical representation (both motor cortices project to the forehead). 'Bell's rings the forehead; Central spares the forehead.'",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "The vagus nerve (CN X) provides parasympathetic innervation to the GI tract up to which anatomical landmark?",
      optionA: "Ileocecal valve (end of small intestine)",
      optionB: "Splenic flexure of the transverse colon",
      optionC: "Rectum and internal anal sphincter",
      optionD: "Entire colon including sigmoid and rectum",
      correctAnswer: "B",
      explanation: "CN X parasympathetic innervation extends from the esophagus to the splenic flexure (left colic flexure) of the transverse colon. Beyond the splenic flexure — the descending colon, sigmoid, and rectum — parasympathetic innervation comes from the pelvic splanchnic nerves (S2-S4). This division is clinically relevant in Hirschsprung disease (absent enteric ganglia) and in understanding autonomic dysreflexia.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "A patient cannot abduct the right eye. The right eye is deviated medially at rest. Which cranial nerve is most likely affected?",
      optionA: "CN III (Oculomotor) — loss of all extraocular muscles except SO and LR",
      optionB: "CN IV (Trochlear) — loss of superior oblique",
      optionC: "CN VI (Abducens) — loss of lateral rectus causing medial deviation (esotropia)",
      optionD: "CN VII (Facial) — inability to close the eyelid",
      correctAnswer: "C",
      explanation: "CN VI (Abducens) innervates the lateral rectus muscle — the sole abductor of the eye. CN VI palsy causes an ipsilateral esotropia (eye deviated medially due to unopposed medial rectus) with inability to abduct past midline. CN VI has the longest intracranial course and is commonly injured by elevated intracranial pressure (false localizing sign) or pontine lesions.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "Which cranial nerve mediates the afferent limb of the gag reflex, and which nerve mediates the efferent limb?",
      optionA: "CN V afferent (trigeminal) — CN X efferent (vagus)",
      optionB: "CN IX afferent (glossopharyngeal) — CN X efferent (vagus)",
      optionC: "CN X afferent (vagus) — CN XII efferent (hypoglossal)",
      optionD: "CN IX afferent (glossopharyngeal) — CN XII efferent (hypoglossal)",
      correctAnswer: "B",
      explanation: "CN IX (glossopharyngeal) carries general sensation from the posterior pharynx — triggering the gag reflex afferently. CN X (vagus) via the nucleus ambiguus mediates the motor response (pharyngeal muscle contraction — the gag). Clinically: touching the posterior pharynx should produce a bilateral response because CN X has bilateral projections; asymmetric response suggests CN IX or X lesion.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "Taste from the anterior 2/3 of the tongue is carried by which cranial nerve branch?",
      optionA: "CN V3 (lingual nerve — trigeminal mandibular branch)",
      optionB: "CN VII (chorda tympani branch of facial nerve)",
      optionC: "CN IX (glossopharyngeal nerve)",
      optionD: "CN X (vagus nerve — superior laryngeal branch)",
      correctAnswer: "B",
      explanation: "Taste from anterior 2/3 tongue: CN VII via chorda tympani (joins the lingual nerve — a branch of V3 — in the infratemporal fossa, but taste fibers belong to CN VII). General sensation (touch, temperature) from anterior 2/3: CN V3 lingual branch. Taste from posterior 1/3 tongue: CN IX. Taste from epiglottis/laryngopharynx: CN X. Salivation: chorda tympani also carries parasympathetics to submandibular and sublingual glands.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "Horner's syndrome is characterized by which triad?",
      optionA: "Mydriasis (dilated pupil), ptosis, and diplopia — indicating CN III palsy",
      optionB: "Ptosis (partial), miosis, and anhidrosis — indicating sympathetic pathway interruption",
      optionC: "Complete ptosis, fixed dilated pupil, and eye deviated 'down and out' — indicating CN III palsy",
      optionD: "Diplopia on downward gaze and compensatory head tilt — indicating CN IV palsy",
      correctAnswer: "B",
      explanation: "Horner's syndrome: Ptosis (partial — loss of superior tarsal/Müller's muscle, NOT levator palpebrae which is CN III), Miosis (pupil constriction — loss of sympathetic dilator pupillae), and Anhidrosis (loss of ipsilateral facial sweating, depending on lesion level). Caused by interruption of the 3-neuron sympathetic chain: hypothalamus → ciliospinal center of Budge (C8-T2) → superior cervical ganglion → iris/eyelid/face.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "Compressive CN III palsy (e.g., from a posterior communicating artery aneurysm) classically presents with which pupillary finding, and why?",
      optionA: "Normal pupils — because pupillary fibers are deep inside CN III and protected",
      optionB: "Dilated, fixed pupil — because parasympathetic pupillary fibers travel on the outer surface of CN III and are compressed first",
      optionC: "Miosis — because compression activates parasympathetic fibers causing sustained constriction",
      optionD: "RAPD — because CN III carries afferent visual information for the light reflex",
      correctAnswer: "B",
      explanation: "Parasympathetic pupillary fibers run on the OUTER surface of CN III. External compressive lesions (aneurysm, uncal herniation) → 'surgical' CN III palsy with dilated, fixed pupil + ophthalmoplegia. Ischemic/diabetic CN III lesions damage internal nerve fibers first, sparing the outer pupillary fibers → 'medical' CN III palsy with ophthalmoplegia but INTACT pupil. A dilated pupil in CN III palsy demands urgent imaging to exclude a PComm aneurysm.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "Which cranial nerve is the only one to exit from the DORSAL (posterior) surface of the brainstem?",
      optionA: "CN III (Oculomotor)",
      optionB: "CN IV (Trochlear)",
      optionC: "CN V (Trigeminal)",
      optionD: "CN VI (Abducens)",
      correctAnswer: "B",
      explanation: "CN IV (Trochlear nerve) is the only cranial nerve that exits the DORSAL midbrain — it decussates in the dorsal midbrain tegmentum before emerging just below the inferior colliculus. All other cranial nerves exit from the ventral or lateral brainstem surface. This anatomical feature and CN IV's long course around the brainstem makes it susceptible to dorsal midbrain pathology (pineal tumors, trauma).",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "Trigeminal neuralgia (tic douloureux) most commonly affects which branch(es) of CN V?",
      optionA: "V1 (ophthalmic) exclusively — periorbital pain",
      optionB: "V2 (maxillary) and/or V3 (mandibular) — V1 is least commonly affected",
      optionC: "All three branches simultaneously — pan-facial pain",
      optionD: "V3 (mandibular) exclusively — lower jaw pain only",
      correctAnswer: "B",
      explanation: "Trigeminal neuralgia produces brief, excruciating, electric shock-like pain triggered by light tactile stimulation (eating, talking, touching face). V2 (cheek, upper lip) and V3 (lower lip, chin) distributions are most commonly affected; V1 (forehead, eye) is least common. Most cases result from vascular compression of CN V at the root entry zone; first-line treatment is carbamazepine.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "CN XI (Spinal Accessory nerve) innervates which two muscles, and how is it clinically tested?",
      optionA: "Stylohyoid and digastric — tested by opening mouth against resistance",
      optionB: "Sternocleidomastoid and trapezius — tested by head rotation and shoulder shrug against resistance",
      optionC: "Genioglossus and hyoglossus — tested by tongue protrusion",
      optionD: "Masseter and temporalis — tested by jaw clenching",
      correctAnswer: "B",
      explanation: "CN XI (Spinal Accessory) innervates: 1) Sternocleidomastoid (SCM) — turns head to the OPPOSITE side; 2) Trapezius — elevates and retracts shoulder, stabilizes scapula. CN XI arises from the C1-C5 anterior horn cells, ascends through the foramen magnum, exits via the jugular foramen. Clinically: shoulder shrug against resistance (trapezius) and turning head against resistance (SCM).",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "CN XII (Hypoglossal nerve) damage causes the tongue to deviate in which direction on protrusion?",
      optionA: "Away from the side of the lesion (contralesional deviation)",
      optionB: "Toward the side of the lesion (ipsilesional deviation)",
      optionC: "No deviation — the tongue cannot be protruded at all",
      optionD: "Toward the side of the lesion only in UMN (central) lesions",
      correctAnswer: "B",
      explanation: "CN XII innervates all intrinsic tongue muscles and most extrinsic tongue muscles (except palatoglossus — CN X). On protrusion, the genioglossus pushes the tongue forward; a weakened ipsilateral genioglossus allows the stronger contralateral side to push the tongue TOWARD the weak (ipsilateral) side. LMN lesion also produces ipsilateral tongue atrophy and fasciculations. UMN lesion: same direction of deviation but without atrophy.",
      examOnly: true,
    },
    {
      topicId: 17,
      question: "The three divisions of CN V (Trigeminal) transmit sensory information from which areas respectively?",
      optionA: "V1 = forehead/cornea; V2 = cheek/upper lip/palate; V3 = lower face + motor to jaw muscles",
      optionB: "V1 = face; V2 = scalp; V3 = neck and jaw",
      optionC: "V1 = eye; V2 = nose; V3 = mouth — all purely sensory",
      optionD: "V1 = forehead + motor to eye; V2 = cheek + motor to palate; V3 = jaw only",
      correctAnswer: "A",
      explanation: "V1 (Ophthalmic — purely sensory): forehead, scalp, upper eyelid, cornea (corneal reflex afferent — efferent is CN VII), anterior nasal cavity. V2 (Maxillary — purely sensory): cheek, lower eyelid, upper lip, maxillary teeth/gums, hard palate, lateral nose. V3 (Mandibular — sensory + MOTOR): lower lip, chin, mandibular teeth, anterior 2/3 tongue (general sensation); motor to muscles of mastication (masseter, temporalis, pterygoids), tensor tympani, tensor veli palatini.",
      examOnly: true,
    },
  ];

  // ===========================================================================
  // VASCULAR SYSTEM (topic 18, exam 18) — 15 additional questions
  // ===========================================================================
  const vascularQ: (typeof quizQuestionsTable.$inferInsert)[] = [
    {
      topicId: 18,
      question: "The internal carotid artery (ICA) gives off which branches before dividing into ACA and MCA?",
      optionA: "Only the anterior choroidal artery — no other branches",
      optionB: "Ophthalmic artery, posterior communicating artery, and anterior choroidal artery",
      optionC: "Posterior cerebral artery and superior cerebellar artery",
      optionD: "Vertebral arteries and basilar artery",
      correctAnswer: "B",
      explanation: "The ICA branches (in order): 1) Ophthalmic artery (first intracranial branch — visual symptoms with ICA disease), 2) Posterior communicating artery (PComm — connects ICA to PCA; common aneurysm site causing CN III palsy), 3) Anterior choroidal artery (supplies posterior limb of internal capsule, optic tract, hippocampus, amygdala, lateral geniculate). Then ICA divides into ACA and MCA.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "Anterior cerebral artery (ACA) occlusion produces which pattern of neurological deficit?",
      optionA: "Contralateral face and arm weakness with aphasia (dominant hemisphere)",
      optionB: "Contralateral leg weakness and sensory loss, urinary incontinence, and abulia",
      optionC: "Contralateral homonymous hemianopia with macular sparing",
      optionD: "Ipsilateral cerebellar ataxia and contralateral limb sensory loss",
      correctAnswer: "B",
      explanation: "ACA supplies the medial surface of the frontal and parietal lobes — where the leg/foot representation of the motor and sensory homunculus is located (paracentral lobule). ACA stroke: contralateral leg > arm weakness, contralateral leg sensory loss, urinary incontinence (medial frontal bladder control center), and abulia/akinetic mutism (medial prefrontal cortex). Face and arm are largely spared.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "The posterior cerebral artery (PCA) is most commonly a branch of which vessel in adults?",
      optionA: "Internal carotid artery in most adults (fetal PCA pattern is dominant)",
      optionB: "Basilar artery in most adults (~70%)",
      optionC: "Vertebral artery directly",
      optionD: "Posterior communicating artery",
      correctAnswer: "B",
      explanation: "In most adults (~70%), the PCA arises from the basilar artery (top of the basilar, at the pontomesencephalic junction). In approximately 30%, the PCA arises from the ICA ('fetal PCA' or fetal-type PCA) — a developmental variant where the posterior circulation remains ICA-dependent. This distinction matters for stroke risk stratification (anterior vs. posterior circulation disease).",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "PCA territory infarction classically produces which primary visual field deficit?",
      optionA: "Bitemporal hemianopia (loss of peripheral vision in both eyes)",
      optionB: "Monocular blindness (loss of vision in one eye only)",
      optionC: "Contralateral homonymous hemianopia, often with macular sparing",
      optionD: "Central scotoma (loss of central vision only)",
      correctAnswer: "C",
      explanation: "PCA supplies the occipital lobe (primary visual cortex V1 — calcarine cortex). Infarction causes contralateral homonymous hemianopia (same visual field loss in both eyes — e.g., right PCA → left homonymous hemianopia). Macular sparing occurs because the macular cortex has dual blood supply (from both MCA and PCA). Macular sparing is a useful clinical sign pointing to PCA rather than optic radiation involvement.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "Watershed (border zone) infarcts occur at which territories, and what clinical scenario produces them?",
      optionA: "ACA/MCA and MCA/PCA junction zones — caused by global ischemia (severe hypotension, cardiac arrest)",
      optionB: "Deep penetrating artery territories — caused by hypertension",
      optionC: "The central MCA territory — caused by emboli from the heart",
      optionD: "The thalamus and basal ganglia — caused by small vessel disease",
      correctAnswer: "A",
      explanation: "Watershed infarcts occur at the border between two major arterial territories where perfusion pressure is lowest: ACA/MCA junction (parasagittal motor cortex — proximal arm and shoulder representation) and MCA/PCA junction (posterior temporal-parietal). They are caused by global hypoperfusion (cardiac arrest, severe hypotension, carotid stenosis). The classic 'man in a barrel' syndrome: bilateral proximal arm > leg weakness from bilateral ACA/MCA watershed infarcts.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "Lenticulostriate artery occlusion causes which type of stroke syndrome?",
      optionA: "Large territorial infarct with aphasia and gaze deviation",
      optionB: "Lacunar infarct — typically pure motor hemiplegia or pure sensory stroke",
      optionC: "Posterior fossa infarct with crossed deficits",
      optionD: "Subarachnoid hemorrhage with sudden severe headache",
      correctAnswer: "B",
      explanation: "Lenticulostriate arteries are small perforating branches of the MCA supplying the striatum (putamen, caudate), globus pallidus, and posterior limb of the internal capsule. Occlusion of these small vessels (most commonly from hypertensive lipohyalinosis) causes lacunar infarcts — small deep infarcts with classic syndromes: pure motor hemiplegia (internal capsule posterior limb), pure sensory stroke (thalamus — thalamoperforators), ataxic hemiparesis, or dysarthria-clumsy hand.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "The basilar artery is formed by the junction of which two vessels, and at which anatomical level?",
      optionA: "Internal carotid arteries — at the level of the circle of Willis",
      optionB: "Two vertebral arteries — at the pontomedullary junction",
      optionC: "Vertebral arteries and posterior inferior cerebellar arteries — at the medullary level",
      optionD: "Two posterior communicating arteries — at the level of the midbrain",
      correctAnswer: "B",
      explanation: "The two vertebral arteries (branches of the subclavian arteries) merge to form the basilar artery at the pontomedullary junction. The basilar then ascends along the ventral surface of the pons, giving off: AICA (anterior inferior cerebellar), pontine perforators, and SCA (superior cerebellar artery), before bifurcating into the two PCAs at the pontomesencephalic junction.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "AICA (Anterior Inferior Cerebellar Artery) occlusion syndrome is characterized by:",
      optionA: "Ipsilateral limb ataxia, contralateral pain/temperature loss, and dysphagia (Wallenberg syndrome)",
      optionB: "Ipsilateral facial nerve palsy (CN VII), hearing loss and vertigo (CN VIII), with contralateral body pain/temperature loss",
      optionC: "Locked-in syndrome with intact vertical eye movements",
      optionD: "Pure cerebellar ataxia without any brainstem cranial nerve deficits",
      correctAnswer: "B",
      explanation: "AICA supplies the anterior-inferior cerebellum and the lateral inferior PONS, including CN VII (facial) and CN VIII (vestibulocochlear) nuclei, and sends the labyrinthine artery to the inner ear. AICA infarct: ipsilateral facial paralysis (CN VII), ipsilateral hearing loss and vertigo (CN VIII/labyrinthine artery), ipsilateral facial numbness (CN V), Horner's, contralateral body pain/temperature loss (spinothalamic tract). Distinguished from Wallenberg by hearing loss.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "Wallenberg syndrome (lateral medullary syndrome) is caused by occlusion of which artery?",
      optionA: "Anterior inferior cerebellar artery (AICA)",
      optionB: "Posterior inferior cerebellar artery (PICA) or vertebral artery",
      optionC: "Superior cerebellar artery (SCA)",
      optionD: "Basilar artery",
      correctAnswer: "B",
      explanation: "PICA or vertebral artery occlusion causes lateral medullary infarction (Wallenberg syndrome). Features: ipsilateral facial pain/numbness (CN V — spinal trigeminal nucleus), dysphagia and hoarseness (CN IX/X — nucleus ambiguus), ipsilateral Horner's (descending sympathetic fibers), ipsilateral limb ataxia (inferior cerebellar peduncle), hiccups, vertigo; AND contralateral body loss of pain/temperature (spinothalamic tract). Crossed findings = medullary lesion.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "Complete basilar artery occlusion most characteristically produces:",
      optionA: "Bilateral cerebellar ataxia with preserved consciousness and speech",
      optionB: "Locked-in syndrome — conscious but quadriplegic, communicates only via vertical eye movements",
      optionC: "Global aphasia with intact limb function",
      optionD: "Bilateral posterior cortical blindness with preserved limb function",
      correctAnswer: "B",
      explanation: "Basilar artery thrombosis causes bilateral ventral pontine infarction — destroying corticospinal tracts (limb movement) and corticobulbar tracts (speech, swallowing). Consciousness is preserved (reticular formation in dorsal pons/midbrain is spared). Vertical eye movements and blinking are preserved (CN III, IV — midbrain). Locked-in syndrome is a devastating condition where the patient is fully conscious but cannot move or speak; only vertical gaze and blinking remain.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "The superior cerebellar artery (SCA) occlusion produces which combination of deficits?",
      optionA: "Ipsilateral hearing loss, facial paralysis, and vertigo",
      optionB: "Ipsilateral cerebellar ataxia, ipsilateral Horner's, and contralateral loss of pain/temperature",
      optionC: "Bilateral limb weakness and locked-in syndrome",
      optionD: "Contralateral hemianopia and hemisensory loss only",
      correctAnswer: "B",
      explanation: "SCA branches from the rostral basilar just before the PCA. It supplies the superior cerebellar surface, deep cerebellar nuclei, superior cerebellar peduncle, and adjacent lateral pons. Infarction: ipsilateral cerebellar ataxia (cerebellar hemisphere + superior peduncle), ipsilateral Horner's (descending sympathetics in lateral tegmentum), contralateral body pain/temperature loss (spinothalamic), and ipsilateral CN IV/CN V involvement. Distinguished from AICA by no hearing loss.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "Cerebral venous blood ultimately drains into which vessel that exits the skull?",
      optionA: "External jugular veins via emissary veins",
      optionB: "Internal jugular veins via the sigmoid sinuses",
      optionC: "Vertebral veins via the epidural venous plexus",
      optionD: "Directly into the right atrium via the superior vena cava without a named sinus",
      correctAnswer: "B",
      explanation: "Cerebral veins → dural venous sinuses: Superior sagittal sinus (convexity drainage) and Inferior sagittal sinus (medial hemisphere) → merge at the confluence (torcular Herophili) → Transverse sinuses (bilateral) → Sigmoid sinuses → Internal jugular veins (bilateral) → Superior vena cava. The Great vein of Galen drains deep structures into the straight sinus. SSS thrombosis can cause bilateral cortical infarcts with hemorrhage.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "Hypertensive intracerebral hemorrhage most commonly occurs in which brain region?",
      optionA: "Frontal lobe white matter (lobar hemorrhage)",
      optionB: "Cerebellum (fourth ventricle compression)",
      optionC: "Putamen and basal ganglia (lenticulostriate arteries — Charcot's arteries)",
      optionD: "Corpus callosum (diffuse axonal injury pattern)",
      correctAnswer: "C",
      explanation: "The putamen/basal ganglia is the most common site of hypertensive intracerebral hemorrhage (~35-50%), caused by rupture of the lenticulostriate arteries (called 'Charcot's arteries of cerebral hemorrhage' — they branch at right angles from the MCA at high pressure). Putaminal hemorrhage features: contralateral hemiplegia, hemisensory loss, ipsilateral gaze deviation, and hemispheric signs (aphasia if dominant). Second most common: thalamus (~15-25%).",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "Subarachnoid hemorrhage (SAH) from a ruptured aneurysm presents with which characteristic symptom?",
      optionA: "Gradual-onset unilateral headache with progressive vision loss",
      optionB: "Sudden 'thunderclap' headache — 'worst headache of my life' — with meningismus",
      optionC: "Stepwise worsening headache over weeks with ipsilateral pupil dilation",
      optionD: "Hemiplegic migraine with focal deficits resolving within 24 hours",
      correctAnswer: "B",
      explanation: "Ruptured aneurysm SAH: sudden-onset 'thunderclap' headache — 'worst headache of my life' reaching maximum intensity in seconds. Associated with meningismus (neck stiffness from blood in CSF), photophobia, and may have transient LOC. Most common cause: ruptured saccular (berry) aneurysm (~85%), usually at circle of Willis branch points. Anterior communicating artery aneurysm is the most common overall site. Urgent CT and lumbar puncture (xanthochromia) are diagnostic.",
      examOnly: true,
    },
    {
      topicId: 18,
      question: "The ischemic penumbra is clinically important because:",
      optionA: "It represents already-dead tissue that defines the minimum infarct size",
      optionB: "It is the zone of functionally impaired but structurally intact tissue that can be salvaged by timely reperfusion",
      optionC: "It determines the risk of hemorrhagic transformation regardless of treatment",
      optionD: "It is relevant only in hemorrhagic strokes, not ischemic strokes",
      correctAnswer: "B",
      explanation: "The ischemic penumbra (CBF 10-20 mL/100g/min): neurons are electrically silent and non-functional but structurally intact — they can recover if perfusion is restored promptly. The core infarct (CBF <10 mL/100g/min) is irreversibly dead. Reperfusion therapies (IV tPA, mechanical thrombectomy) target penumbral salvage. 'Time is brain' — ~1.9 million neurons lost per minute in untreated MCA occlusion. Advanced imaging (MRI perfusion-diffusion mismatch) maps the penumbra.",
      examOnly: true,
    },
  ];

  // ===========================================================================
  // NEURODEVELOPMENTAL DISORDERS (topic 19, exam 19) — 15 additional questions
  // ===========================================================================
  const neurodevQ: (typeof quizQuestionsTable.$inferInsert)[] = [
    {
      topicId: 19,
      question: "Habit Reversal Training (HRT) is the behavioral core of which intervention for tic disorders?",
      optionA: "DBT (Dialectical Behavior Therapy) adapted for tic suppression",
      optionB: "CBIT (Comprehensive Behavioral Intervention for Tics) — the first-line non-pharmacological treatment",
      optionC: "CBT-E (Enhanced CBT) for Tourette's co-occurring OCD",
      optionD: "PCIT (Parent-Child Interaction Therapy) for tic-related family conflict",
      correctAnswer: "B",
      explanation: "CBIT (Comprehensive Behavioral Intervention for Tics) is the first-line non-pharmacological treatment for tic disorders, with strong RCT evidence. Its core component is Habit Reversal Training (HRT): awareness training (identifying the premonitory urge), competing response training (performing an incompatible behavior when the urge is felt), and social support. Effective for Tourette's and persistent tic disorders in children and adults.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "What is the minimum symptom duration required for a diagnosis of Specific Learning Disorder in DSM-5?",
      optionA: "3 months despite appropriate support",
      optionB: "6 months of persistent difficulties despite intervention",
      optionC: "1 academic year of school failure",
      optionD: "2 years of consistently below-grade performance",
      correctAnswer: "B",
      explanation: "DSM-5 requires at least 6 months of persistent learning difficulties that have not substantially improved despite targeted intervention. This threshold distinguishes SLD from transient academic problems related to inadequate instruction, adjustment difficulties, psychosocial stressors, or brief developmental lags. The criterion ensures persistence and treatment-resistance before SLD is diagnosed.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "Applied Behavior Analysis (ABA) is the most evidence-based intervention for ASD. Its theoretical foundation is:",
      optionA: "Psychodynamic theory — resolving unconscious conflicts underlying social withdrawal",
      optionB: "Operant conditioning — systematic use of antecedents, behaviors, and consequences to shape adaptive behaviors",
      optionC: "Cognitive processing theory — changing maladaptive thoughts about social situations",
      optionD: "Attachment theory — repairing insecure caregiver bonds underlying social deficits",
      correctAnswer: "B",
      explanation: "ABA is grounded in Skinnerian operant conditioning. The ABC model (Antecedent-Behavior-Consequence) guides interventions: structured antecedents set occasions for behavior; reinforcement increases adaptive behaviors; extinction and differential reinforcement reduce maladaptive behaviors. Early Intensive Behavioral Intervention (EIBI) — 20-40 hours/week for young children — is the most intensive application, with strongest evidence for improving IQ, language, and adaptive behavior.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "The 'broader autism phenotype' refers to:",
      optionA: "The full range of ASD severity from Level 1 to Level 3",
      optionB: "Subclinical autistic traits (social communication differences, circumscribed interests) in first-degree relatives of individuals with ASD",
      optionC: "Previously diagnosed Asperger's disorder under DSM-IV criteria",
      optionD: "The spectrum of conditions that were merged into ASD in DSM-5",
      correctAnswer: "B",
      explanation: "The broader autism phenotype (BAP) describes milder but measurable autistic traits in first-degree relatives of ASD probands — including reduced eye contact, circumscribed interests, preference for routines, and subtle social communication differences that do not meet full ASD criteria. The BAP supports the genetic continuity of autism as a dimensional trait rather than a binary category, consistent with heritability estimates of 60-90%.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "The WISC-V Working Memory Index (WMI) and Processing Speed Index (PSI) are commonly low relative to other indices in which neurodevelopmental disorders?",
      optionA: "Intellectual Developmental Disorder only — all indices are uniformly low",
      optionB: "ADHD and Specific Learning Disorders — creating diagnostic profiles with significant index score variability",
      optionC: "ASD only — due to the specific executive function profile of ASD",
      optionD: "Tic disorders and Tourette's — due to motor interference during testing",
      correctAnswer: "B",
      explanation: "In ADHD, WMI and PSI are typically the lowest index scores due to executive function and attentional deficits — often significantly below the Verbal Comprehension Index (VCI) and Fluid Reasoning Index (FRI). In dyslexia (SLD-reading), low PSI and WMI (especially Digit Span) contrast with higher VCI, creating a diagnostic profile. Significant intra-individual variability (rather than global low scores) suggests SLD or ADHD rather than IDD.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "The most evidence-based reading remediation approach for dyslexia is:",
      optionA: "Whole language immersion — extensive reading of authentic texts at grade level",
      optionB: "Visual tracking exercises and colored overlays to reduce visual stress",
      optionC: "Structured Literacy (Orton-Gillingham approach) — systematic, explicit phonological awareness and phonics instruction",
      optionD: "Sight word memorization using flash cards without phonics",
      correctAnswer: "C",
      explanation: "Structured Literacy — exemplified by the Orton-Gillingham approach and related programs (Wilson Reading, Barton, RAVE-O) — is the most evidence-based intervention for dyslexia. Key components: explicit phonological awareness training, systematic grapheme-phoneme (phonics) instruction, decoding and spelling practice, fluency building, and vocabulary. Effective remediation measurably changes brain activation patterns (increased left hemisphere activity on fMRI).",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "Under IDEA (Individuals with Disabilities Education Act), a child with ADHD who qualifies for special education services would most likely be classified under which eligibility category?",
      optionA: "Emotional Disturbance",
      optionB: "Specific Learning Disability",
      optionC: "Other Health Impairment (OHI)",
      optionD: "Autism",
      correctAnswer: "C",
      explanation: "ADHD most commonly qualifies children for special education under the 'Other Health Impairment' (OHI) category in IDEA, which includes conditions affecting alertness, vitality, and strength — including ADHD — that adversely affect educational performance. Children with ADHD who don't qualify for an IEP (special education) may receive accommodations through Section 504 plans (civil rights law — lower threshold than IDEA).",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "Which brain region shows the most consistent functional deficit during working memory tasks in ADHD neuroimaging studies?",
      optionA: "Hippocampus — reflecting memory consolidation failure",
      optionB: "Amygdala — reflecting emotional dysregulation during cognitive effort",
      optionC: "Dorsolateral prefrontal cortex (DLPFC) — reflecting executive control deficits",
      optionD: "Cerebellum — reflecting timing and motor coordination deficits",
      correctAnswer: "C",
      explanation: "The dorsolateral prefrontal cortex (DLPFC, Brodmann areas 9 and 46) consistently shows reduced activation during working memory and executive function tasks in ADHD. The DLPFC is richly innervated by dopaminergic and noradrenergic projections from the midbrain/locus coeruleus — the targets of stimulant medications. Stimulants normalize DLPFC activation patterns and improve working memory performance.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "Preterm birth (<37 weeks) is associated with significantly increased risk for which neurodevelopmental outcomes?",
      optionA: "Only motor disorders (cerebral palsy) — cognitive development is unaffected by prematurity",
      optionB: "ADHD, cognitive impairment, ASD, cerebral palsy, and sensory processing difficulties",
      optionC: "Exclusively language disorders — no increased risk for ADHD or ASD",
      optionD: "Only IDD when gestational age is less than 28 weeks",
      correctAnswer: "B",
      explanation: "Preterm birth significantly increases risk for: ADHD (3-4x increased risk), intellectual disability, cerebral palsy, ASD, specific learning disorders, and sensory/behavioral problems. Periventricular leukomalacia (PVL) — white matter injury common in very preterm infants — disrupts long-range cortical-subcortical connectivity relevant to executive function, social cognition, and motor control. The earlier the gestational age, the higher the neurodevelopmental risk.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "Selective mutism is classified in DSM-5 under which diagnostic category?",
      optionA: "Communication Disorders — as a subtype of Language Disorder",
      optionB: "Autism Spectrum Disorder — as a presentation with minimal verbal output",
      optionC: "Anxiety Disorders — consistent failure to speak in specific social situations despite speaking normally elsewhere",
      optionD: "Neurodevelopmental Disorders — alongside Speech Sound Disorder",
      correctAnswer: "C",
      explanation: "Selective mutism is classified under Anxiety Disorders in DSM-5 (not Communication Disorders or neurodevelopmental disorders). It involves consistent failure to speak in specific social situations (typically school) despite speaking normally in other settings (home). Language skills are intact — the mutism is anxiety-driven (extreme social anxiety). Must be distinguished from Language Disorder (pervasive language deficit) and ASD (global social communication impairment).",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "First-line genetic testing recommended for individuals with ASD includes:",
      optionA: "Standard karyotype (G-banded chromosomes) to detect aneuploidy",
      optionB: "Chromosomal microarray (CMA) and Fragile X testing — detecting copy number variants in 10-15% of ASD cases",
      optionC: "Whole genome sequencing — recommended for every individual with ASD",
      optionD: "MECP2 gene testing — to rule out Rett syndrome in all children with ASD",
      correctAnswer: "B",
      explanation: "Current guidelines recommend chromosomal microarray (CMA) as first-line genetic testing for ASD — it detects submicroscopic copy number variants (deletions/duplications) in approximately 10-15% of ASD cases. Fragile X testing (FMR1 CGG repeat analysis) is also recommended (especially in males). CMA has higher diagnostic yield than traditional karyotype. Whole exome sequencing detects additional causes but is not yet universal first-line.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "Phenylketonuria (PKU) causes intellectual disability through which mechanism, and how is it prevented?",
      optionA: "Chromosomal nondisjunction causing trisomy — prevented by prenatal diagnosis",
      optionB: "Phenylalanine hydroxylase deficiency → phenylalanine accumulation → brain toxicity — prevented by newborn screening and low-phenylalanine diet",
      optionC: "CGG repeat expansion silencing FMRP — prevented by genetic counseling",
      optionD: "Prenatal alcohol exposure — prevented by abstinence from alcohol during pregnancy",
      correctAnswer: "B",
      explanation: "PKU is autosomal recessive (PAH gene — phenylalanine hydroxylase deficiency). Phenylalanine cannot be converted to tyrosine → phenylalanine accumulates → toxic to the developing brain → severe intellectual disability if untreated. Mandatory newborn screening (heel-stick) detects PKU within days of birth. A phenylalanine-restricted diet initiated in the first weeks of life completely prevents intellectual disability. PKU is the model for metabolic screening and dietary prevention of IDD.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "The ADOS-2 (Autism Diagnostic Observation Schedule) is best described as:",
      optionA: "A parent-report questionnaire scoring ASD symptoms across home and school settings",
      optionB: "A standardized cognitive test measuring IQ and language in individuals with ASD",
      optionC: "A semi-structured clinician-administered observational assessment — the gold standard for ASD behavioral observation",
      optionD: "An EEG-based biomarker tool for ASD diagnosis",
      correctAnswer: "C",
      explanation: "The ADOS-2 (Autism Diagnostic Observation Schedule, 2nd Edition) is a semi-structured, standardized observational assessment — the gold standard for directly observing ASD-related behaviors. A trained clinician administers structured social 'presses' and activities, then codes behaviors in Domains A (social communication) and B (RRBs). Has 5 modules based on language level. Combined with the ADI-R (parent interview), it forms the gold standard research diagnostic battery.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "Executive function deficits are best described as 'transdiagnostic' across neurodevelopmental disorders because:",
      optionA: "They are specific only to ADHD and do not appear in ASD or SLD",
      optionB: "Working memory, inhibitory control, cognitive flexibility, planning, and processing speed deficits appear across ADHD, ASD, SLD, and IDD",
      optionC: "Only planning deficits are shared; inhibitory control is specific to conduct disorder",
      optionD: "Executive function deficits are only relevant in adulthood when compensatory strategies fail",
      correctAnswer: "B",
      explanation: "Executive function deficits are transdiagnostic — they appear across ADHD (response inhibition and working memory — core per Barkley's model), ASD (cognitive flexibility and set-shifting deficits underlying insistence on sameness), SLD (verbal working memory in dyslexia, processing speed in dyscalculia), and IDD (global executive dysfunction). This overlapping profile underlies the high comorbidity rates between neurodevelopmental disorders.",
      examOnly: true,
    },
    {
      topicId: 19,
      question: "The sex ratio gap in specific learning disorder diagnoses (historically 3-4:1 male:female) is now thought to largely reflect:",
      optionA: "A true biological vulnerability in males at the genetic level",
      optionB: "Referral bias — females with SLD internalize difficulties and are less likely to be referred for evaluation",
      optionC: "Earlier brain maturation in females that permanently prevents SLD",
      optionD: "Higher rates of co-occurring intellectual disability in males skewing SLD prevalence data",
      correctAnswer: "B",
      explanation: "The historical 3-4:1 male:female ratio in SLD diagnoses is now understood to largely reflect referral bias rather than true prevalence differences. Females with reading disorders tend to internalize — becoming anxious and withdrawn rather than disruptive — making them less likely to be referred for evaluation. Epidemiological studies using direct screening (rather than clinic-referred samples) find sex ratios approaching parity, similar to ADHD research.",
      examOnly: true,
    },
  ];

  // Insert all new questions
  const allNew = [
    ...brainQ,
    ...cranialQ,
    ...vascularQ,
    ...neurodevQ,
  ];
  const inserted = await db.insert(quizQuestionsTable).values(allNew).returning();
  console.log(`✓ Inserted ${inserted.length} new quiz questions (15 per topic)`);

  // Group inserted question IDs by topicId
  const byTopic: Record<number, number[]> = { 16: [], 17: [], 18: [], 19: [] };
  for (const q of inserted) {
    byTopic[q.topicId].push(q.id);
  }

  // Fetch existing question IDs for each topic
  const existingQuestions = await db.select({ id: quizQuestionsTable.id, topicId: quizQuestionsTable.topicId })
    .from(quizQuestionsTable)
    .where(inArray(quizQuestionsTable.topicId, [16, 17, 18, 19]));

  const existing: Record<number, number[]> = { 16: [], 17: [], 18: [], 19: [] };
  for (const q of existingQuestions) {
    if (byTopic[q.topicId] && !byTopic[q.topicId].includes(q.id)) {
      existing[q.topicId].push(q.id);
    }
  }

  // Rebuild practice exams for each topic
  const examMap: Record<number, number> = { 16: 16, 17: 17, 18: 18, 19: 19 };

  for (const [topicIdStr, examId] of Object.entries(examMap)) {
    const topicId = Number(topicIdStr);

    // Delete old practice exam questions
    await db.delete(practiceExamQuestionsTable)
      .where(eq(practiceExamQuestionsTable.examId, examId));

    // First 10 are original quiz questions, next 15 are new (examOnly)
    const allForTopic = [...existing[topicId], ...byTopic[topicId]];
    const selected = allForTopic.slice(0, 25);

    const rows = selected.map((qId, i) => ({
      examId,
      questionId: qId,
      questionOrder: i + 1,
    }));

    await db.insert(practiceExamQuestionsTable).values(rows);
    console.log(`✓ Topic ${topicId}: practice exam ${examId} rebuilt with ${selected.length} questions`);
  }

  console.log("\n✅ All practice exams expanded to 25 questions.");
}

expandPracticeExams()
  .then(() => process.exit(0))
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
