import { db } from "./index";
import { eq } from "drizzle-orm";
import {
  topicsTable, flashcardsTable, quizQuestionsTable,
  studyGuidesTable, practiceExamsTable, practiceExamQuestionsTable,
} from "./schema";

const TOPIC_ID = 16;

async function rework() {
  console.log("Reworking Brain Structures (topic 16)...");

  // Clear existing
  const exams = await db.select({ id: practiceExamsTable.id }).from(practiceExamsTable).where(eq(practiceExamsTable.topicId, TOPIC_ID));
  for (const e of exams) {
    await db.delete(practiceExamQuestionsTable).where(eq(practiceExamQuestionsTable.examId, e.id));
  }
  await db.delete(practiceExamsTable).where(eq(practiceExamsTable.topicId, TOPIC_ID));
  await db.delete(quizQuestionsTable).where(eq(quizQuestionsTable.topicId, TOPIC_ID));
  await db.delete(flashcardsTable).where(eq(flashcardsTable.topicId, TOPIC_ID));
  await db.delete(studyGuidesTable).where(eq(studyGuidesTable.topicId, TOPIC_ID));
  console.log("  ✓ Cleared old data");

  await db.update(topicsTable).set({
    description: "A comprehensive anatomical map of the brain organized into cortical and subcortical regions — lobes and association areas, the diencephalon, basal ganglia, limbic system, brainstem, cerebellum, and white matter pathways, with connectivity, lateralization, and clinical correlates throughout."
  }).where(eq(topicsTable.id, TOPIC_ID));

  // ──────────────────────────────────────────────────────────────────────
  // STUDY GUIDE
  // ──────────────────────────────────────────────────────────────────────
  const sgContent = `# Brain Structures

---

# PART I: THE CEREBRAL CORTEX

## 1. Overview of Cortical Organization

The cerebral cortex is the outermost layer of gray matter covering the cerebral hemispheres — a heavily convoluted sheet approximately 2-4 mm thick that, when unfolded, would occupy roughly 2,500 cm². Its convolutions (gyri) and grooves (sulci and fissures) dramatically increase cortical surface area within the fixed volume of the skull. The cortex is organized both areally — into regions with distinct cytoarchitecture (Brodmann's areas, numbered BA 1-52) — and hierarchically — from primary sensorimotor areas through unimodal and heteromodal association cortex. The left and right hemispheres are connected by the corpus callosum and are functionally lateralized, with the left hemisphere dominant for language in approximately 95% of right-handers and 70% of left-handers.

A primary organizing principle is the distinction between **primary cortex** (receiving direct thalamic sensory input or sending direct motor output), **unimodal association cortex** (processing a single sensory modality more abstractly), and **heteromodal association cortex** (integrating across modalities — the prefrontal, inferior parietal, and anterior temporal lobes). The further from primary cortex, the more abstract, integrative, and clinically consequential the function.

---

## 2. The Frontal Lobe

The frontal lobe is the largest lobe, extending from the frontal pole to the central sulcus posteriorly and the lateral sulcus (Sylvian fissure) inferiorly. It contains all motor cortex and the core of the prefrontal executive system.

### 2.1 Motor Regions

The **primary motor cortex (M1)** occupies the precentral gyrus (BA 4). It contains the largest pyramidal neurons in the brain — the Betz cells — whose axons form the largest component of the corticospinal tract. M1 is organized somatotopically as the **motor homunculus**: the medial surface controls the leg and foot; the lateral surface controls the hand, face, and tongue, with disproportionate representation reflecting the fine motor demands of hand and orofacial function. Damage to M1 produces contralateral UMN weakness — initially flaccid, then spastic with hyperreflexia.

The **premotor cortex** (lateral BA 6) programs complex, externally guided motor sequences and contributes axons to the corticospinal tract. It is essential for sequencing movements triggered by external cues. The **supplementary motor area (SMA)** (medial BA 6) is recruited for internally generated, self-initiated movements, bimanual coordination, and sequences from memory. Damage to the SMA produces **akinesia** and, with bilateral injury, **akinetic mutism** — a state of profound motor and speech initiation failure with retained arousal. Alien hand syndrome can follow SMA or corpus callosum lesions.

### 2.2 Prefrontal Cortex

The prefrontal cortex (PFC) — everything anterior to the premotor cortex — is the brain's highest-order regulatory system. Three anatomically and functionally distinct regions are clinically important.

The **dorsolateral PFC (dlPFC, BA 9/46)** is essential for **working memory** (actively holding and manipulating information in mind), **cognitive flexibility** (shifting between tasks and rules), and directed **attention**. It maintains a continuous dialogue with the parietal cortex and thalamus. Damage produces a dysexecutive syndrome — impaired planning, perseveration (inability to shift cognitive set), working memory deficits, and difficulty suppressing inappropriate responses. This is the neuroanatomical basis of the executive dysfunction seen after traumatic brain injury, frontal strokes, and in many psychiatric disorders.

The **orbitofrontal/ventromedial PFC (OFC/vmPFC, BA 11/12/25)** integrates emotion and reward into decision-making. It receives direct amygdala input and encodes the emotional value of options. Damage produces the **pseudopsychopathic syndrome**: socially disinhibited behavior, poor risk assessment, emotional lability, inappropriate humor, and impaired impulse control — despite often-preserved performance on standard cognitive tests. The classic case is Phineas Gage; the somatic marker hypothesis (Damasio) was developed to explain this dissociation.

The **medial PFC and anterior cingulate cortex (mPFC/ACC)** participate in self-referential processing, error monitoring, conflict detection, and affective motivation. This region is a key node of the **default mode network (DMN)** — the circuit active during self-reflection, mind-wandering, and autobiographical memory retrieval.

### 2.3 Language and Language-Adjacent Areas

**Broca's area (BA 44/45)** in the left inferior frontal gyrus (pars opercularis and triangularis) is responsible for speech production, motor language programming, syntactic processing, and verbal working memory. Damage causes **Broca's (nonfluent/expressive) aphasia**: halting, effortful speech with intact comprehension but impaired production and repetition, often accompanied by right face and hand weakness.

The **frontal eye fields (FEF, BA 8)** generate voluntary saccades to the contralateral visual field. Acute damage produces **ipsilateral gaze deviation** (eyes look toward the lesion, away from the hemiparesis) — because the intact contralateral FEF drives eyes unopposed. This reverses in seizures, where eyes deviate contralaterally (away from the irritating focus).

---

## 3. The Parietal Lobe

The parietal lobe extends from the central sulcus anteriorly to the parieto-occipital sulcus posteriorly, and from the lateral sulcus to the interhemispheric fissure.

The **primary somatosensory cortex (S1)** occupies the postcentral gyrus (BA 1, 2, 3). It receives input from VPL (body) and VPM (face) thalamic nuclei and processes contralateral touch, pressure, vibration, temperature, and proprioception in a somatotopic **sensory homunculus** arrangement mirroring the motor homunculus. Damage produces contralateral hemisensory loss, with impaired tactile discrimination, graphesthesia, and stereognosis.

The **superior parietal lobule (SPL, BA 5/7)** integrates somatosensory and visual information for visuomotor guidance, reaching and grasping, and spatial attention. The **inferior parietal lobule (IPL)** contains two key regions: the **angular gyrus (BA 39)** — critical for reading, writing, arithmetic, cross-modal integration, and body-schema. Left angular gyrus damage produces **Gerstmann's syndrome** (finger agnosia, left-right disorientation, agraphia, and acalculia). The **supramarginal gyrus (BA 40)** contributes to phonological processing and limb-kinetic praxis.

The **right parietal lobe** is dominant for visuospatial processing and directed spatial attention. Right parietal damage — particularly involving the temporoparietal junction and IPL — produces **hemispatial neglect** (failure to attend to the contralateral hemispace), **anosognosia** (unawareness of one's own deficits), and **constructional apraxia**. Severe neglect is approximately five times more common and more persistent after right than left parietal lesions.

---

## 4. The Temporal Lobe

The temporal lobe extends inferiorly and posteriorly from the lateral sulcus. It is the most functionally heterogeneous lobe — encompassing auditory cortex, language areas, visual object recognition, memory, and emotion.

The **primary auditory cortex (Heschl's gyri, BA 41/42)** lies on the superior surface of the temporal lobe within the lateral sulcus. It receives tonotopically organized input from the medial geniculate nucleus (MGN) and processes basic acoustic features of sound. **Wernicke's area (BA 22)**, in the posterior superior temporal gyrus of the left hemisphere, is essential for **language comprehension** and phonological decoding. Damage produces **Wernicke's (fluent/receptive) aphasia**: fluent but paraphasic, semantically incoherent speech with severely impaired comprehension and repetition.

The **fusiform gyrus** (BA 37) in the inferior temporal cortex contains the **fusiform face area (FFA)**, which is specialized for face identity recognition and is right-dominant. Damage to the right fusiform causes **prosopagnosia** — inability to recognize faces as individuals (though the person is still perceived as a face). More lateral occipito-temporal regions process object identity (the ventral visual stream, or "what" pathway).

The **medial temporal lobe (MTL)** — comprising the hippocampus, parahippocampal gyrus (perirhinal and entorhinal cortex), and amygdala — is the brain's memory and emotional processing hub. It is covered extensively in Part II under the limbic system.

---

## 5. The Occipital Lobe

The occipital lobe sits at the posterior pole of the brain. Its medial surface contains the **calcarine sulcus**, along whose banks lies the **primary visual cortex (V1, striate cortex, BA 17)**. V1 is retinotopically organized — the lower visual field maps to the upper bank (cuneus), and the upper visual field to the lower bank (lingual gyrus). The macular (foveal) representation is disproportionately large and occupies the most posterior portion. Bilateral V1 destruction causes **cortical blindness** with intact pupillary reflexes (the afferent arc via the superior colliculus is preserved). Unilateral V1 lesions produce a contralateral **homonymous hemianopia** with macular sparing (when the lesion is posterior, because the macula has dual blood supply).

The **extrastriate cortex** (V2-V5 and beyond) carries out higher visual computations. V4 and the fusiform gyrus process color and object form. V5/MT processes motion; damage produces **akinetopsia** (inability to perceive visual motion). The two major visual processing streams diverge from extrastriate cortex: the **dorsal stream** ("where/how" pathway) runs into the posterior parietal cortex for visuospatial processing and visually guided action; the **ventral stream** ("what" pathway) runs into the inferotemporal cortex for object recognition.

---

# PART II: SUBCORTICAL STRUCTURES

## 6. Introduction to Subcortical Organization

The term *subcortical* literally means "beneath the cortex." Subcortical structures are the gray-matter nuclei and related regions that lie below the cerebral cortex — buried within the cerebral hemispheres, the diencephalon, brainstem, and cerebellum. These regions are phylogenetically older than the neocortex, present in simpler vertebrates that lack an expanded cortical mantle. In humans, they are tightly interwoven with cortical systems: almost no cortical function proceeds without subcortical participation, and vice versa.

A few overarching principles govern subcortical function and pathology:

**Small lesions produce outsized deficits.** Subcortical structures are compact and densely connected. Even a tiny lacunar infarct in the internal capsule or thalamus can produce dramatic motor or cognitive syndromes because so many fibers are packed into a small space.

**Circuits matter more than individual structures.** Similar deficits arise from damage anywhere in a shared loop — the Papez circuit for memory, the cortico-striato-thalamo-cortical loops for movement and cognition. Thinking in circuits rather than single structures is clinically more powerful.

**Lateralization affects presentation.** Left and right subcortical lesions produce different cognitive profiles, mirroring the lateralization of the cortex they support.

**Subcortical damage affects cognition and emotion, not just movement.** The older view that subcortical equals motor is outdated. The basal ganglia, thalamus, limbic system, and cerebellum all contribute to cognition, mood, and behavior, and damage can closely mimic psychiatric disease.

---

## 7. The Diencephalon

The diencephalon occupies the core of the brain between the cerebral hemispheres and the brainstem, surrounding the third ventricle. It is the principal relay and regulatory hub of the nervous system and comprises four regions: the thalamus, hypothalamus, epithalamus, and subthalamus.

### 7.1 Thalamus

The thalamus is a paired, egg-shaped mass of gray matter forming the bulk of the diencephalon and is often described as the brain's "gateway to the cortex" — virtually every sensory modality (with the sole exception of olfaction, which projects directly to the piriform cortex) passes through a specific thalamic nucleus before reaching the cerebral cortex. The thalamus also relays motor signals from the cerebellum and basal ganglia to the motor cortex, and participates in attention, arousal, and consciousness.

Internally, the thalamus is divided by the **internal medullary lamina** into anterior, medial, and lateral nuclear groups, with additional intralaminar and reticular nuclei.

**Sensory relay nuclei:** The **ventral posterolateral nucleus (VPL)** relays somatosensory information from the body (arriving via the medial lemniscus and spinothalamic tract) to S1 cortex. The **ventral posteromedial nucleus (VPM)** relays face somatosensory input from the trigeminal system and taste from the NTS to S1 and the insula. The **lateral geniculate nucleus (LGN)** is the dedicated visual relay, receiving retinal ganglion axons via the optic tract and projecting to V1. The **medial geniculate nucleus (MGN)** is the auditory relay, receiving input from the inferior colliculus and projecting to the primary auditory cortex.

**Motor relay nuclei:** The **ventral anterior (VA) and ventral lateral (VL) nuclei** receive output from the basal ganglia (GPi/SNr via the thalamic fasciculus) and cerebellum (dentate nucleus via the superior cerebellar peduncle), respectively, and project to the motor and premotor cortex. These nuclei are the final relay through which both major motor control systems influence voluntary movement.

**Associative and limbic nuclei:** The **mediodorsal (MD) nucleus** connects bidirectionally with the prefrontal cortex and is involved in executive function, decision-making, and emotional regulation — damage contributes to thalamic amnesia and affective blunting. The **anterior nuclear group** is part of the Papez circuit, receiving mammillary body input via the mammillothalamic tract and projecting to the cingulate cortex for memory and emotion. The **pulvinar** is a large posterior nucleus involved in visual attention, integration of visual information, and salience detection.

**Connectivity:** The thalamus maintains reciprocal connections with virtually every area of the cerebral cortex via thalamocortical radiations passing through the internal capsule and corona radiata. This positions it at the intersection of all major cortico-subcortical loops. The **thalamic reticular nucleus (TRN)** — a shell of GABAergic neurons surrounding the thalamus — modulates the gain of thalamocortical transmission and is involved in selective attention (gating relevant signals through while suppressing others during focused attention and sleep).

**Lateralization:** Thalamic lateralization mirrors the cortex it serves. The left pulvinar and MD are more engaged in language-related processing; their right counterparts contribute more to visuospatial attention. Hemispatial neglect after right thalamic stroke tends to be more severe and persistent than after left-sided lesions.

**Clinical damage:** Thalamic strokes produce strikingly varied syndromes depending on the territory involved. VPL/VPM lesions cause contralateral hemisensory loss; with recovery, a particularly disabling **thalamic pain syndrome (Déjerine-Roussy syndrome)** may develop — burning, allodynic contralateral pain that is often treatment-refractory. LGN lesions produce visual field defects; VL/VA lesions cause contralateral movement disorders. Bilateral **paramedian thalamic infarction** (from occlusion of a common artery) produces profound disturbances of consciousness, memory, and vertical gaze — a small stroke with devastating consequences. **Fatal familial insomnia** is a prion disease selectively destroying thalamic nuclei, causing progressive, untreatable insomnia, autonomic failure, and death.

### 7.2 Hypothalamus

Despite weighing only approximately 4 grams, the hypothalamus is the master regulator of homeostasis. It sits below the thalamus, forming the floor and lateral walls of the third ventricle, and lies immediately above the pituitary gland to which it is connected via the pituitary stalk. It coordinates autonomic, endocrine, and behavioral responses to maintain the internal environment.

The hypothalamus contains multiple functionally distinct nuclei. The **suprachiasmatic nucleus (SCN)** is the body's master circadian clock — a self-sustaining pacemaker entrained by light signals arriving via the retinohypothalamic tract. It orchestrates daily rhythms of sleep, hormone secretion, body temperature, and behavior throughout the entire body. The **paraventricular nucleus (PVN)** produces oxytocin and vasopressin (antidiuretic hormone, ADH) and coordinates the stress response through the hypothalamic-pituitary-adrenal (HPA) axis via CRH release. The **supraoptic nucleus** also synthesizes vasopressin and oxytocin, which are transported to the posterior pituitary for release into the bloodstream.

The **arcuate nucleus** regulates appetite and energy balance, releasing hypothalamic releasing hormones (GHRH, CRH, TRH, GnRH) into the portal system and containing the NPY/AgRP (orexigenic) and POMC/CART (anorexigenic) neuronal populations that are central to energy homeostasis regulation. The **ventromedial nucleus (VMH)** functions as a satiety center — VMH lesions produce hyperphagia and obesity. The **lateral hypothalamic area (LHA)** is the feeding/hunger center — LHA lesions cause aphagia (refusal to eat) and wasting. The LHA also contains **orexin (hypocretin) neurons** that maintain wakefulness and stabilize the sleep-wake cycle; loss of these neurons is the cause of **narcolepsy type 1**. The **preoptic area** regulates body temperature (the preoptic area is the thermostat set-point region) and plays a role in sleep onset (the VLPO produces GABA and galanin to inhibit arousal nuclei).

The **mammillary bodies** are two small nuclei on the ventral hypothalamic surface that form a critical node of the Papez memory circuit, relaying hippocampal output (arriving via the fornix) to the anterior thalamus.

**Connectivity:** The hypothalamus communicates with the anterior pituitary via the **hypothalamo-hypophyseal portal system** (releasing hormones secreted into portal blood that drive or inhibit pituitary hormone release) and with the posterior pituitary via direct axonal projections (the neurohypophyseal tract carrying oxytocin and vasopressin). It connects to brainstem and spinal cord autonomic preganglionic neurons, to limbic structures via the medial forebrain bundle and stria terminalis, and to the thalamus via the mammillothalamic tract.

**Clinical damage:** Hypothalamic damage — from tumors (craniopharyngioma is the archetypal hypothalamic mass lesion), TBI, surgical injury, or stroke — produces a predictable but broad set of deficits: disrupted thermoregulation (poikilothermia), **diabetes insipidus** (from vasopressin deficiency — massive dilute urine), SIADH (from excess vasopressin), obesity or anorexia, loss of circadian rhythmicity, panhypopituitarism, and altered sexual behavior.

### 7.3 Epithalamus

The epithalamus lies on the posterior-dorsal aspect of the diencephalon. Its two principal components are the **pineal gland** and the **habenular nuclei**.

The **pineal gland** secretes **melatonin** in response to darkness — the signal is conveyed from the SCN through a multisynaptic pathway involving the superior cervical ganglion and sympathetic innervation of the pineal. Melatonin regulates sleep onset and circadian entrainment. Pineal calcification with age makes it a useful midline landmark on head CT.

The **habenular nuclei** are an evolutionarily ancient structure connecting limbic forebrain structures (via the stria medullaris) to brainstem monoaminergic nuclei (via the fasciculus retroflexus to the interpeduncular nucleus and raphe). They are increasingly implicated in **depression, reward processing, and responses to aversive stimuli** — hyperactivity of the lateral habenula is proposed as a mechanism of anhedonia and depressive hopelessness. Deep brain stimulation of the habenula is under investigation for treatment-resistant depression.

**Clinical damage:** Pineal tumors compress the **tectum** (superior colliculi) and the cerebral aqueduct. Compression of the tectum produces **Parinaud's syndrome**: impaired upward vertical gaze, convergence-retraction nystagmus (eyes jerk back and converge rather than moving up), and light-near dissociation of the pupils (poor response to light, preserved near response). Aqueductal obstruction causes obstructive hydrocephalus.

### 7.4 Subthalamus

The subthalamus sits below the thalamus and contains the **subthalamic nucleus (STN)** and zona incerta. The STN is functionally part of the basal ganglia and is discussed in that section.

---

## 8. The Basal Ganglia

The basal ganglia are a group of interconnected subcortical nuclei primarily involved in motor control, action selection, habit formation, and procedural learning. They also contribute substantially to cognition and emotion. The classical components are the **caudate nucleus**, **putamen**, **globus pallidus**, **substantia nigra**, and **subthalamic nucleus**.

**Key anatomical groupings:**
- **Striatum:** Caudate + putamen — the primary input structure of the basal ganglia
- **Lentiform nucleus:** Putamen + globus pallidus — an anatomical (not functional) grouping based on their lens-shaped appearance
- **Corpus striatum:** Caudate + putamen + globus pallidus

### 8.1 Caudate Nucleus

The caudate nucleus is a C-shaped structure whose head, body, and tail follow the curve of the lateral ventricle through the frontal, parietal, and temporal lobes. Its head lies adjacent to the frontal horn; its tail reaches the amygdala in the temporal lobe. The caudate is primarily part of **associative and limbic basal ganglia circuits** and contributes to goal-directed behavior, cognitive flexibility, response inhibition, and learning. The head of the caudate is tightly connected with the PFC and is engaged during rule-learning, task-switching, and reward-based decision-making.

**Lateralization:** The dominant-hemisphere caudate contributes more to language and verbal fluency, while the non-dominant caudate contributes more to visuospatial processing. In Parkinson's disease, asymmetric nigral degeneration produces asymmetric striatal dopamine loss, producing asymmetric motor and cognitive symptoms.

**Clinical damage:** Bilateral caudate atrophy is a hallmark of **Huntington's disease**, producing the classic triad of chorea, cognitive decline, and psychiatric symptoms (depression, irritability, OCD, psychosis). The characteristic "box-car" ventriculomegaly of HD on MRI reflects expansion of the frontal horns as the caudate heads shrink. Focal caudate strokes (often lacunar infarcts) can produce striking **abulia** (severe apathy and reduced spontaneous behavior) and executive dysfunction that can be mistaken for depression.

### 8.2 Putamen

The putamen is the largest and most lateral component of the striatum. It is the primary recipient of somatomotor cortex input and is most heavily engaged in **motor execution and motor learning** — the automation of learned movements. Together with the caudate, it receives the majority of cortical glutamatergic input to the basal ganglia.

### 8.3 Globus Pallidus

The globus pallidus (GP) lies medial to the putamen and has two functionally distinct segments. The **external globus pallidus (GPe)** is a central node of the indirect pathway, projecting inhibitory (GABAergic) fibers to the subthalamic nucleus. The **internal globus pallidus (GPi)** is a major output nucleus of the entire basal ganglia system, sending GABAergic inhibitory fibers to the VA/VL thalamus. The GPi is tonically active and continuously inhibits the thalamus — the basal ganglia's regulation of movement depends on modulating this tonic inhibition.

**Clinical damage:** GPi lesions cause movement disorders, most classically **dystonia** (sustained, involuntary muscle contractions causing twisting postures). Pallidotomy (surgical GPi lesioning) and deep brain stimulation of the GPi are established treatments for refractory Parkinson's disease and primary dystonia.

### 8.4 Substantia Nigra

Located in the midbrain tegmentum, the substantia nigra has two functionally distinct components. The **pars compacta (SNc)** contains large dopaminergic neurons, densely packed and appearing dark on gross inspection (from neuromelanin accumulation). SNc neurons project via the **nigrostriatal pathway** to the striatum, where dopamine modulates the activity of both pathway circuits. The **pars reticulata (SNr)** is a GABAergic output nucleus functionally similar to the GPi — it sends inhibitory output to the superior colliculus (controlling gaze) and thalamus.

**Clinical damage:** The defining pathology of **Parkinson's disease** is progressive degeneration of SNc dopaminergic neurons — with alpha-synuclein Lewy body accumulation and the loss of approximately 70-80% of these neurons before the motor threshold is crossed and symptoms emerge. The result is the classic parkinsonian triad of **resting tremor, rigidity, and bradykinesia**, along with postural instability and a rich array of non-motor features (anosmia, constipation, REM sleep behavior disorder, depression, and cognitive decline).

### 8.5 Subthalamic Nucleus (STN)

The STN is a small, lens-shaped structure at the diencephalic-mesencephalic junction. It is the key excitatory driver of the indirect pathway, projecting glutamatergic fibers to the GPi and SNr. By exciting the GPi, the STN increases inhibitory output to the thalamus and thereby suppresses movement — its physiological role is to help brake unwanted or competing movements.

**Clinical damage:** Unilateral STN lesions — most famously from small lacunar infarcts — produce **hemiballismus**: violent, flinging, large-amplitude involuntary movements of the contralateral limbs. This results from loss of STN excitation of the GPi, leading to reduced GPi output, disinhibition of the thalamus, and runaway motor cortex activation. The STN is also the most common target for **deep brain stimulation (DBS)** in Parkinson's disease, where high-frequency stimulation disrupts pathological bursting in the circuit.

### 8.6 The Direct and Indirect Pathways

The basal ganglia regulate movement selection through two opposing circuits that together implement a "go/no-go" gating system for voluntary actions.

**Direct pathway** (the "go" signal): Cortex → striatum → GPi/SNr → thalamus → cortex. The striatum inhibits the GPi (GABAergic synapse). This reduces GPi inhibition of the thalamus (disinhibition) → the thalamus becomes more active → motor cortex activation → movement facilitation.

**Indirect pathway** (the "stop" signal): Cortex → striatum → GPe → STN → GPi/SNr → thalamus → cortex. The striatum inhibits the GPe → the STN is disinhibited → STN excites the GPi → the GPi more strongly inhibits the thalamus → motor cortex is suppressed → movement inhibition.

**Dopaminergic modulation:** Dopamine from the SNc modulates both pathways through different receptor subtypes. D1 receptors (on direct-pathway striatal neurons) are excitatory → dopamine facilitates the direct pathway (promotes movement). D2 receptors (on indirect-pathway striatal neurons) are inhibitory → dopamine inhibits the indirect pathway (reduces movement suppression). Both effects synergize to facilitate movement.

In **Parkinson's disease**, dopamine loss tips the balance toward the indirect pathway: reduced direct pathway activity + increased indirect pathway activity → GPi is overactive → thalamus is excessively inhibited → motor cortex is underactive → **hypokinesia** (bradykinesia, akinesia, freezing). In **Huntington's disease**, early selective loss of indirect-pathway striatal neurons removes the brake on movement → insufficient GPi output → thalamic disinhibition → **hyperkinesia** (chorea).

**Basal ganglia lateralization:** Basal ganglia function is primarily **contralateral** — left basal ganglia control the right body and vice versa — because their output reaches motor cortex, which controls contralateral muscles. In Parkinson's disease, symptoms typically begin asymmetrically, reflecting asymmetric nigral degeneration.

---

## 9. The Limbic System

The limbic system is a functionally defined collection of structures arranged around the medial edge of the cerebral hemisphere. It governs emotion, motivation, memory, and aspects of autonomic and endocrine regulation. The core components are the hippocampus, amygdala, cingulate cortex, fornix, mammillary bodies, and nucleus accumbens.

### 9.1 Hippocampus

Named for its seahorse-like shape in coronal section, the hippocampus sits in the medial temporal lobe, forming the floor of the inferior horn of the lateral ventricle. It is architecturally divided into several subfields — CA1, CA2, CA3, CA4, and the dentate gyrus — connected in a sequential circuit: dentate gyrus → CA3 → CA1 → subiculum → entorhinal cortex. **CA1 is the most metabolically vulnerable subfield**, highly susceptible to ischemia and hypoxia — the mechanism of hippocampal sclerosis in temporal lobe epilepsy.

The hippocampus is essential for the **formation of new declarative (explicit) memories** — both episodic (personally experienced events) and semantic (facts and conceptual knowledge). It binds together the distributed cortical representations of a memory episode and is critical during the initial consolidation period. It also supports **spatial navigation**, constructing and using cognitive maps of space via place cells that fire selectively when the animal occupies particular locations.

The hippocampus is one of only two brain regions supporting robust **adult neurogenesis** (the olfactory bulb is the other) — new granule cells are continuously added to the dentate gyrus throughout life, and this process is modulated by exercise (promoting), stress and glucocorticoids (suppressing), and antidepressants (promoting).

**Connectivity:** Cortical input arrives via the **entorhinal cortex** (via the perforant path — the major cortical input to the hippocampus). The major hippocampal output is the **fornix**, which arches beneath the corpus callosum to reach the mammillary bodies, anterior thalamus, and septal nuclei, completing the **Papez circuit**: hippocampus → fornix → mammillary bodies → anterior thalamus → cingulate cortex → parahippocampal gyrus → hippocampus. This circuit is central to declarative memory consolidation and emotional memory.

**Lateralization:** Left hippocampus is preferentially involved in **verbal memory** (words, stories, facts); right hippocampus is more engaged in **spatial and nonverbal memory** (places, faces, routes). Left temporal lobe epilepsy surgery commonly impairs verbal memory; right-sided surgery more commonly impairs visuospatial memory and navigation.

**Clinical damage:** Bilateral hippocampal damage produces **profound anterograde amnesia** — the inability to form new long-term declarative memories — with retrograde amnesia for recent events and relative preservation of remote (consolidated) memories and procedural learning. The famous patient H.M. (Henry Molaison) lived for decades unable to form any new explicit memories following bilateral medial temporal lobectomy. The hippocampus is among the **first regions damaged in Alzheimer's disease** (Braak stages I-II involve the entorhinal cortex and CA1) and is highly vulnerable to **herpes simplex encephalitis** (which has a predilection for the medial temporal lobes).

### 9.2 Amygdala

The amygdala is an almond-shaped cluster of approximately 13 distinct nuclei in the medial temporal lobe, immediately anterior to the hippocampus. It functions as the brain's primary **emotional salience detector** — particularly for fear, threat, and reward — and is critical for emotional learning, the formation and retrieval of emotional memories, and social cognition.

The amygdala receives rich sensory input through two routes: a **fast, coarse subcortical pathway** directly from the thalamus (the "low road") that provides rapid — though imprecise — threat detection, and a **slower, detailed cortical pathway** (the "high road") via sensory cortex that provides more accurate but slower evaluation. This dual-route architecture allows rapid behavioral responses to potential threats before full conscious evaluation is complete.

**Connectivity:** The amygdala projects extensively to the hypothalamus (generating autonomic fear responses — accelerated heart rate, sweating, pupil dilation), the brainstem (startle reflexes, freezing), the nucleus accumbens (fear motivation and avoidance learning), and the prefrontal cortex (top-down emotional regulation) via the **stria terminalis** and **ventral amygdalofugal pathway**.

**Lateralization:** The right amygdala is more engaged in rapid, automatic, and nonverbal emotional processing; the left amygdala is more involved in sustained and verbally mediated emotional evaluation and regulation. Both amygdalae are hyperactive in anxiety disorders and PTSD, and the amygdala response to threatening stimuli is modulated by descending regulatory input from the medial PFC and ACC.

**Clinical damage:** Bilateral amygdala damage — as occurs in **Urbach-Wiethe disease** (a rare genetic disorder causing calcification of the amygdalae) — impairs recognition of fearful facial expressions, eliminates conditioned fear learning, and reduces the normal personal space boundaries between individuals. It can produce the human analogue of **Klüver-Bucy syndrome** (originally described in monkeys after bilateral temporal lobectomy): hyperorality, hypersexuality, visual agnosia, and diminished emotional reactivity.

### 9.3 Cingulate Cortex

The cingulate gyrus arches over the corpus callosum on the medial surface of each hemisphere. Though technically cortical in cytoarchitecture, it is tightly integrated with subcortical limbic structures and is considered part of the limbic system.

The **anterior cingulate cortex (ACC, BA 24/32)** is involved in conflict monitoring (detecting when response competition exists), error detection, pain affect (the emotional unpleasantness of pain — distinct from its sensory quality which is processed in S1), and emotional regulation. It receives dense input from the amygdala and sends output to motor and prefrontal cortex. The ACC is heavily activated in attention-demanding tasks and in conditions of emotional conflict. It is a key node linking cognitive and emotional control.

The **posterior cingulate cortex (PCC)** is one of the central hubs of the **default mode network** — a set of regions more active at rest than during externally directed tasks. It is involved in self-referential thought, autobiographical memory retrieval, and mind-wandering. PCC and medial PFC are among the earliest sites of **amyloid accumulation** in Alzheimer's disease, and their deactivation during external tasks is disrupted in early AD.

### 9.4 Fornix and Mammillary Bodies

The **fornix** is the major white-matter output tract of the hippocampus, arching in a sweeping curve from the hippocampal subiculum beneath the corpus callosum to its primary termination at the **mammillary bodies** and anterior thalamus, with additional projections to the septal nuclei and lateral hypothalamus. It is an essential component of the Papez circuit, carrying hippocampal output forward in the memory consolidation pathway.

The **mammillary bodies** are two small nuclei on the ventral hypothalamic surface. They receive hippocampal input via the fornix and relay this forward to the anterior thalamus via the **mammillothalamic tract**, continuing the Papez circuit. Despite their small size, they are indispensable nodes in the memory circuit.

**Clinical damage:** Atrophy of the mammillary bodies — visible on MRI as symmetric reduction in their normal T1-bright signal — is a hallmark of **Wernicke's encephalopathy** and its chronic sequela, **Korsakoff syndrome**, caused by thiamine deficiency. Fornix transection (from surgical injury, colloid cyst, or deep midline tumors) produces a dense anterograde amnesia. The bilateral mammillary body damage of Korsakoff syndrome produces **dense anterograde amnesia, retrograde amnesia with a temporal gradient, and confabulation** — the spontaneous (and unintentional) fabrication of memories to fill in gaps.

### 9.5 Nucleus Accumbens

The nucleus accumbens sits at the junction of the caudate and putamen in the **ventral striatum**. It is the central node of the brain's **reward circuit**, receiving dopaminergic input from the **ventral tegmental area (VTA)** via the **mesolimbic pathway** — the most heavily studied reward pathway in the brain. It integrates motivational signals from the amygdala, hippocampus, and PFC with dopaminergic reward prediction signals to drive approach behavior, pleasure, and reinforcement learning.

The nucleus accumbens has a **shell** region (more closely connected with the amygdala, hypothalamus, and brainstem autonomic centers — involved in primary reward and aversion) and a **core** region (more connected with the caudate, putamen, and motor system — involved in learned instrumental behaviors and habit formation).

**Clinical relevance:** Dysfunction of the nucleus accumbens and mesolimbic dopamine pathway is implicated in virtually all forms of **addiction** — addictive drugs hijack this system by producing supraphysiological dopamine release or blocking reuptake. It is also a key substrate for **anhedonia** (the inability to experience pleasure) in major depression and schizophrenia. The nucleus accumbens is an emerging **deep brain stimulation target** for refractory major depression and OCD.

---

## 10. The Brainstem

The brainstem connects the forebrain to the spinal cord and contains nuclei essential to life — centers for breathing, heart rate, blood pressure, consciousness, and all but two of the cranial nerves (I and II arise more rostrally). It is divided into three regions: the midbrain, pons, and medulla oblongata, with the reticular formation running throughout all three.

### 10.1 Midbrain

The midbrain (mesencephalon) is the most rostral brainstem region.

The **tectum** (dorsal midbrain) contains the **superior colliculi** — visual reflex centers that coordinate gaze orientation and reflexive saccades toward novel visual stimuli — and the **inferior colliculi** — an obligatory auditory relay in the ascending auditory pathway, sending fibers to the MGN.

The **tegmentum** (ventral) contains the **red nucleus** (a motor coordination center giving rise to the rubrospinal tract), the **periaqueductal gray (PAG)** (involved in pain modulation, defensive behavior, and vocalization), the **substantia nigra**, the **ventral tegmental area (VTA)** (source of mesolimbic dopamine to the nucleus accumbens and mesocortical dopamine to the PFC), and the nuclei of cranial nerves III (oculomotor) and IV (trochlear).

**Clinical damage:** Midbrain lesions produce characteristic named syndromes. **Weber syndrome** (ventral midbrain infarction): ipsilateral CN III palsy (ptosis, dilated pupil, downward-outward eye deviation) with contralateral hemiparesis (from corticospinal tract damage in the cerebral peduncle). **Benedikt syndrome** (tegmental midbrain): ipsilateral CN III palsy with contralateral tremor and ataxia (red nucleus damage).

### 10.2 Pons

The pons ("bridge") serves as the major relay between the cerebral cortex and the cerebellum via the massive **pontocerebellar fibers** forming the middle cerebellar peduncles. It contains the nuclei of cranial nerves V (trigeminal), VI (abducens), VII (facial), and VIII (vestibulocochlear).

The pontine tegmentum contains important centers for **sleep regulation** — notably the REM-generating nuclei (the subcoeruleus area, which drives atonia of REM sleep via the spinal cord) — and for **horizontal conjugate gaze** (the paramedian pontine reticular formation, PPRF, and the abducens nucleus, which connects via the MLF to the contralateral CN III nucleus). Respiratory control contributions (pneumotaxic and apneustic centers) also reside here.

**Clinical damage:** Extensive bilateral ventral pontine lesions (most commonly from basilar artery thrombosis) cause **locked-in syndrome** — the patient is fully conscious (reticular formation and cortex are spared) but completely paralyzed except for vertical eye movements and blinking (which use the midbrain and are preserved). **Central pontine myelinolysis** follows rapid correction of chronic hyponatremia — rapid osmotic shifts destroy the pontine myelin, causing dysphagia, dysarthria, and quadriparesis.

### 10.3 Medulla Oblongata

The medulla is the most caudal brainstem region, continuous with the spinal cord at the level of the foramen magnum. It contains centers essential for survival: **cardiovascular regulation** (vasomotor center controlling blood pressure and heart rate), **respiratory rhythm generation** (the pre-Bötzinger complex and dorsal/ventral respiratory groups), and reflexes for vomiting, coughing, swallowing, and hiccuping. It contains the nuclei of cranial nerves IX (glossopharyngeal), X (vagus), XI (accessory), and XII (hypoglossal), and the site of the **pyramidal decussation** (where 85-90% of corticospinal fibers cross to the contralateral side) and the **sensory decussation** (where second-order DCML neurons cross to form the medial lemniscus).

**Clinical damage:** **Lateral medullary (Wallenberg) syndrome** — classically from posterior inferior cerebellar artery (PICA) occlusion — produces one of neurology's most complex and instructive crossed syndromes: ipsilateral facial sensory loss (V nucleus), ipsilateral Horner's syndrome (descending sympathetic fibers), ipsilateral limb ataxia (inferior cerebellar peduncle), dysarthria and dysphagia (vagal nuclei), vertigo and nystagmus (vestibular nuclei), with contralateral body pain and temperature loss (spinothalamic tract). **Medial medullary syndrome** from anterior spinal artery occlusion produces contralateral hemiparesis (pyramidal tract), contralateral DCML loss, and ipsilateral tongue weakness (CN XII nucleus).

### 10.4 Reticular Formation

The reticular formation is a diffuse network of interconnected neurons running the full length of the brainstem core, from the medulla through the pons and midbrain. It performs four critical functions.

**Arousal and consciousness** are maintained by the **ascending reticular activating system (ARAS)** — projections from the reticular formation to the intralaminar thalamic nuclei and directly to the cortex, sustaining the waking state. Damage to the ARAS, particularly at the rostral pons/midbrain level or bilaterally at any level, produces **coma** — this is why small, strategically placed brainstem lesions can abolish consciousness despite leaving the entire cortex intact.

**Monoaminergic modulation:** The reticular formation contains the brain's major monoaminergic nuclei. The **locus coeruleus** (dorsal pons) is the primary source of **norepinephrine** to the entire brain — critical for arousal, attention, and stress responses. The **raphe nuclei** (midline throughout the brainstem) are the primary source of **serotonin** — modulating mood, appetite, sleep, and pain. The **VTA** (midbrain) and **SNc** provide **dopamine** to limbic and cortical targets.

**Autonomic integration** occurs through reticular connections to the hypothalamus and spinal autonomic preganglionic neurons.

**Motor modulation** includes descending reticulospinal tracts that regulate muscle tone and participate in posture and gait.

---

## 11. The Cerebellum

Although the cerebellum sits posterior rather than inferior to the cortex, it is traditionally grouped with subcortical structures. It contains **more neurons than the rest of the brain combined** — approximately 80% of all neurons in the human CNS (largely cerebellar granule cells) — and is essential for motor coordination, balance, posture, and motor learning. It also contributes to cognition, language, and emotion in ways increasingly recognized by modern neuroimaging.

### 11.1 Functional Divisions

The cerebellum is divided into three functionally distinct zones based on their connections and roles.

The **vestibulocerebellum** (the flocculonodular lobe — the phylogenetically oldest part, also called the archicerebellum) connects with the vestibular nuclei and controls balance, posture, and eye movements. It is the smallest division and contains the flocculus and nodulus. Damage produces **truncal and gait ataxia** and **nystagmus** — patients cannot maintain balance and fall, even with eyes open, when the vestibulospinal system is disrupted.

The **spinocerebellum** (the vermis and paravermis — the paleocerebellum) receives proprioceptive and somatosensory input from the spinal cord via the spinocerebellar tracts, monitoring the ongoing state of ongoing limb movement. It coordinates posture, gait, and the execution of ongoing movements in real time. The vermis regulates axial and proximal limb muscles; the paravermis regulates distal limb movements. Vermis damage produces **gait ataxia**; paravermis damage produces **ipsilateral limb dysmetria** and **intention tremor**.

The **cerebrocerebellum** (the lateral hemispheres — the neocerebellum) is the largest and most recently evolved division. It connects with the cerebral cortex via the pons (input) and dentate nucleus-thalamus-motor cortex circuit (output) and is involved in **motor planning, timing, and the automation of complex movements**. It also contributes to cognitive functions including working memory, language processing, and timing of cognitive operations. Damage to the lateral hemispheres produces **appendicular ataxia** (ipsilateral limb incoordination), **dysmetria** (over- or undershooting), and **dysdiadochokinesia** (inability to perform rapid alternating movements).

### 11.2 Connectivity

The cerebellum connects to the brainstem through three pairs of **cerebellar peduncles**. The **inferior cerebellar peduncles** carry input from the spinal cord (spinocerebellar tracts) and medulla (inferior olivary nucleus — the major source of climbing fiber input that drives cerebellar plasticity). The **middle cerebellar peduncles** — the largest — carry input from the pontine nuclei (relaying cortical information via the corticopontine tract). The **superior cerebellar peduncles** carry output from the deep cerebellar nuclei (primarily the dentate nucleus) to the contralateral thalamus (VL) and midbrain (red nucleus) — crossing the midline in the decussation of the superior cerebellar peduncles.

A critical feature is that **cerebellar control is ipsilateral** to the body. This is because the cerebellar output crosses in the superior cerebellar peduncle, but then the corticospinal tract crosses again at the pyramidal decussation. These two crossings cancel out — the right cerebellum ultimately controls the right body. A right cerebellar hemisphere lesion produces right-sided ataxia.

### 11.3 Cognitive and Emotional Roles

Modern neuroimaging and careful lesion studies have established that the cerebellum participates in working memory, attention, language processing (particularly timing and articulatory programming), and emotional regulation. Damage to the **posterior cerebellum** — particularly the vermis and right posterolateral hemisphere — can produce **cerebellar cognitive affective syndrome (Schmahmann's syndrome)**: executive dysfunction, linguistic difficulties, visuospatial impairment, and personality changes including affective blunting and inappropriate behavior.

---

## 12. White Matter and Connectivity

Gray-matter nuclei would be functionally useless without the white-matter tracts that connect them. White-matter fibers fall into three anatomical categories.

**Projection fibers** connect the cortex with subcortical structures and the spinal cord. The **internal capsule** is the principal example — a compact, V-shaped bundle that carries corticospinal, corticobulbar, and thalamocortical fibers. The posterior limb of the internal capsule contains the densely packed corticospinal tract; even a tiny lacunar infarct here produces a **pure motor hemiparesis** with no sensory deficit.

**Commissural fibers** connect the two hemispheres. The **corpus callosum** — the largest white-matter structure in the brain — connects homotopic cortical regions of the two hemispheres. Its genu connects prefrontal areas, the body connects motor and somatosensory areas, and the splenium connects posterior parietal and occipital areas. The **anterior commissure** connects the anterior temporal lobes and olfactory structures. The **posterior commissure** connects pretectal nuclei involved in the pupillary light reflex. Corpus callosum transection (surgical or from Marchiafava-Bignami disease, a rare alcoholic demyelinating disorder) produces **interhemispheric disconnection syndromes** — the left hand literally does not know what the right hand is doing.

**Association fibers** connect cortical regions within the same hemisphere. The **arcuate fasciculus / superior longitudinal fasciculus** connects Broca's and Wernicke's areas — damage to it produces **conduction aphasia** (fluent speech, intact comprehension, severely impaired repetition). The **uncinate fasciculus** connects the orbitofrontal cortex with the anterior temporal lobe — damaged in behavioral variant FTD. The **inferior longitudinal fasciculus** connects the occipital and temporal lobes along the ventral visual stream. The **cingulum** runs within the cingulate gyrus, connecting medial limbic structures.

**Dedicated subcortical tracts** deserve special mention: the **fornix** carries hippocampal output to the mammillary bodies (Papez circuit); the **stria terminalis** carries amygdala output to the hypothalamus and BNST; the **mammillothalamic tract** connects the mammillary bodies to the anterior thalamus; the **medial forebrain bundle** carries hypothalamic connections to the brainstem and limbic forebrain; and the three pairs of **cerebellar peduncles** carry all cerebellar input and output.`;

  // ──────────────────────────────────────────────────────────────────────
  // FLASHCARDS
  // ──────────────────────────────────────────────────────────────────────
  const flashcards = [
    // === CORTEX ===
    { question: "What is the functional distinction between the three prefrontal cortex regions?", answer: "dlPFC (BA 9/46): working memory, cognitive flexibility, directed attention — dysexecutive syndrome on damage. OFC/vmPFC (BA 11/12): emotion-reward integration in decision-making — pseudopsychopathic syndrome on damage (disinhibition, risk-taking, impulsivity despite intact cognition). mPFC/ACC: self-referential processing, error monitoring, conflict detection, affective motivation — default mode network hub; akinetic mutism with bilateral lesions.", difficulty: "hard" },
    { question: "What are the two major cortical visual processing streams, where do they originate, and what are their functions?", answer: "Both originate in V1/extrastriate occipital cortex. Dorsal stream ('where/how' pathway): V1 → parietal cortex — visuospatial processing, visually guided action, spatial awareness. Damage → hemispatial neglect, optic ataxia. Ventral stream ('what' pathway): V1 → inferotemporal cortex — object recognition, face recognition, color processing. Damage → visual agnosias, prosopagnosia. The two streams are anatomically and functionally dissociable.", difficulty: "hard" },
    { question: "What is Gerstmann's syndrome and where is the lesion?", answer: "Gerstmann's syndrome is produced by damage to the left angular gyrus (BA 39). It comprises four components: 1) Finger agnosia (inability to identify specific fingers), 2) Left-right disorientation, 3) Agraphia (impaired writing), 4) Acalculia (impaired arithmetic). It represents a disruption of body-schema and cross-modal integration at the left parieto-temporal junction.", difficulty: "medium" },
    { question: "What differentiates hemispatial neglect from hemianopia?", answer: "Hemianopia: loss of vision in contralateral hemifield due to V1 or optic tract damage — the patient is aware of the deficit and may compensate by turning head/eyes. Hemispatial neglect: failure to attend to or represent the contralateral hemispace despite intact primary vision — patient is often unaware (anosognosia). Cause: right parietal/temporoparietal junction damage. Distinguishing test: line bisection (neglect patients bisect to the right of center); cancellation tasks (neglect patients miss left-sided targets).", difficulty: "hard" },
    { question: "What is the default mode network and which structures constitute it?", answer: "The default mode network (DMN) is a set of brain regions more active during rest and self-referential thinking than during externally-directed task engagement. Core nodes: medial PFC (mPFC), posterior cingulate cortex (PCC), precuneus, and lateral temporal and parietal cortex (angular gyrus, inferior temporal gyrus). The DMN supports autobiographical memory retrieval, self-reflection, mental simulation, and social cognition. DMN deactivation during external tasks is impaired in early Alzheimer's disease; DMN hyperconnectivity is implicated in rumination in depression.", difficulty: "hard" },
    // === THALAMUS ===
    { question: "What are the major thalamic relay nuclei, their inputs, and their cortical targets?", answer: "VPL → S1 (body touch/proprioception/pain) from medial lemniscus + spinothalamic tract. VPM → S1/insula (face + taste) from trigeminal + NTS. LGN → V1 (vision) from optic tract. MGN → A1 (hearing) from inferior colliculus. VA/VL → motor/premotor cortex (motor control) from basal ganglia (VA) and cerebellum (VL). Mediodorsal → PFC (cognition/emotion) from limbic/basal ganglia. Anterior → cingulate cortex (memory/emotion) from mammillary bodies.", difficulty: "hard" },
    { question: "What is Déjerine-Roussy syndrome and what causes it?", answer: "Thalamic pain syndrome (Déjerine-Roussy): a chronic, severe, burning pain syndrome affecting the contralateral hemibody, often with allodynia (pain from normally non-painful stimuli), that develops weeks to months after a thalamic stroke affecting the VPL/VPM. The acute stroke initially causes hemisensory loss; as the thalamus partially recovers, abnormal pain processing emerges. The syndrome is often treatment-refractory. It illustrates that the thalamus is not merely a passive relay but an active modulator of sensory experience.", difficulty: "hard" },
    { question: "What is the thalamic reticular nucleus (TRN) and why is it clinically important?", answer: "The TRN is a shell of GABAergic neurons surrounding the thalamus (like a reticular net). It is the only thalamic nucleus that does NOT project to the cortex — instead it projects inhibitory axons back onto the thalamo-cortical relay neurons, modulating the gain of thalamocortical transmission. The TRN is involved in selective attention (amplifying relevant signals and suppressing others during focused cognition) and in generating sleep spindles (the hallmark of NREM stage 2 sleep). TRN dysfunction is implicated in attention disorders and possibly schizophrenia.", difficulty: "hard" },
    // === HYPOTHALAMUS ===
    { question: "What is the suprachiasmatic nucleus (SCN) and how does it entrain circadian rhythms?", answer: "The SCN (in the anterior hypothalamus, just above the optic chiasm) is the body's master circadian clock — a self-sustaining transcription-translation feedback loop (CLOCK/BMAL1 activate PER/CRY, which feed back to inhibit their own transcription, cycling every ~24 hours). Light entrains the SCN via the retinohypothalamic tract (ipRGCs → optic chiasm → SCN) — light suppresses melatonin release from the pineal gland (which is downstream of the SCN). The SCN then coordinates circadian output to the rest of the body via autonomic, neuroendocrine, and behavioral pathways.", difficulty: "hard" },
    { question: "What is the clinical syndrome produced by loss of hypothalamic orexin (hypocretin) neurons?", answer: "Narcolepsy type 1 (narcolepsy with cataplexy) is caused by destruction of orexin (hypocretin)-producing neurons in the lateral hypothalamic area — most commonly by an autoimmune process (HLA DQB1*06:02 strongly associated; T-cell mediated destruction follows infection or vaccination in genetically predisposed individuals). Orexin normally stabilizes the sleep-wake switch; its loss causes pathological intrusions of REM sleep into wakefulness. Clinical features: excessive daytime sleepiness, cataplexy (sudden bilateral muscle weakness triggered by strong emotion — the pathognomonic feature), sleep paralysis, and hypnagogic/hypnopompic hallucinations.", difficulty: "hard" },
    { question: "What is diabetes insipidus and what part of the hypothalamic-pituitary axis does it involve?", answer: "Diabetes insipidus (DI) is a disorder of water regulation caused by deficient antidiuretic hormone (vasopressin/ADH) action. Central DI: insufficient ADH production from the supraoptic and paraventricular nuclei (or damaged transport to the posterior pituitary) — causes include hypothalamic tumors (craniopharyngioma), trauma, surgery, infiltrative disease (sarcoid, Langerhans cell histiocytosis), and autoimmune destruction. Result: massive polyuria (up to 15-20 L/day) of dilute urine, with compensatory polydipsia. Without adequate fluid intake, hypernatremic dehydration develops rapidly. Treatment: desmopressin (synthetic ADH analog).", difficulty: "hard" },
    // === BASAL GANGLIA ===
    { question: "Explain the direct and indirect basal ganglia pathways and what happens when dopamine is lost in Parkinson's disease.", answer: "Direct pathway: Striatum (D1 MSNs) → GPi/SNr (inhibit) → thalamus disinhibited → motor cortex facilitated → movement. Indirect pathway: Striatum (D2 MSNs) → GPe (inhibit) → STN disinhibited → GPi/SNr driven → thalamus inhibited → motor cortex suppressed → movement suppressed. Dopamine: excites D1 (facilitates direct/movement) and inhibits D2 (reduces indirect/movement suppression). In Parkinson's: dopamine loss → ↓ direct pathway + ↑ indirect pathway → GPi overactive → thalamus excessively inhibited → motor cortex underactive → bradykinesia, akinesia, rigidity.", difficulty: "hard" },
    { question: "What is hemiballismus and what subcortical structure is responsible?", answer: "Hemiballismus is a hyperkinetic movement disorder characterized by violent, flinging, large-amplitude involuntary movements of the contralateral arm and leg. It results from a lesion (typically a lacunar infarct) of the contralateral subthalamic nucleus (STN). Without STN excitation, the GPi becomes underactive → insufficient inhibition of the thalamus → thalamus disinhibited → runaway motor cortex excitation → explosive movements. Hemiballismus usually resolves within weeks to months as the circuit adapts.", difficulty: "medium" },
    { question: "What are the key anatomical groupings within the basal ganglia and what does each include?", answer: "Striatum: caudate + putamen — the main INPUT nucleus receiving cortical glutamatergic drive. Lentiform (lenticular) nucleus: putamen + globus pallidus — an anatomical grouping based on lens shape, not functional unity. Corpus striatum: caudate + putamen + globus pallidus. Ventral striatum: nucleus accumbens + olfactory tubercle — the reward/limbic circuit input. The basal ganglia proper also include the substantia nigra (in the midbrain) and the subthalamic nucleus (in the subthalamus).", difficulty: "medium" },
    // === LIMBIC ===
    { question: "Describe the Papez circuit and its role in memory.", answer: "The Papez circuit (1937) is a closed loop originally proposed for emotion, now understood as critical for declarative memory consolidation: Hippocampus (CA1/subiculum) → Fornix → Mammillary bodies → Mammillothalamic tract → Anterior thalamic nucleus → Cingulate gyrus → Parahippocampal cortex → Entorhinal cortex → Hippocampus. Damage at any node — the hippocampus (amnesia), fornix (transection amnesia), mammillary bodies (Korsakoff syndrome), or anterior thalamus (thalamic amnesia) — can produce anterograde amnesia, demonstrating that memory depends on the integrity of the entire circuit, not any single structure.", difficulty: "hard" },
    { question: "What is Klüver-Bucy syndrome and what bilateral damage produces it?", answer: "Klüver-Bucy syndrome follows bilateral medial temporal lobe damage (amygdala + anterior temporal cortex). Features: visual agnosia (inability to recognize objects visually), hyperorality (compulsively examining objects with the mouth), hypersexuality (inappropriate, indiscriminate sexual behavior), placidity (profound emotional blunting, loss of fear and aggression), and dietary changes (hyperphagia). In humans it can follow bilateral temporal lobectomy, herpes simplex encephalitis, trauma, or neurodegenerative disease. The full syndrome is rare; partial forms (especially placidity + hyperorality) are seen in advanced FTD and other temporal dementias.", difficulty: "medium" },
    { question: "How does the nucleus accumbens mediate addiction?", answer: "Addictive drugs (regardless of mechanism) converge on the nucleus accumbens by massively increasing dopamine in the synaptic cleft — either by promoting dopamine release (amphetamines, cocaine's DAT blockade), mimicking dopamine (opioids via disinhibition of VTA neurons), or blocking reuptake. This supraphysiological dopamine surge produces intense pleasure and potent reinforcement. With repeated exposure: 1) Postsynaptic D2 receptors downregulate (reducing sensitivity to natural rewards → anhedonia); 2) Glutamatergic inputs from PFC/amygdala become sensitized; 3) Incentive salience ('wanting') dissociates from 'liking'; 4) Prefrontal inhibitory control over the accumbens weakens → compulsive drug-seeking despite consequences.", difficulty: "hard" },
    { question: "What are the two routes by which the amygdala receives sensory information, and what is the functional significance of each?", answer: "1) The fast subcortical 'low road' (thalamus → amygdala direct): rapid (~12 ms) but coarse/imprecise — conveys a rough threat signal before full sensory analysis is complete; enables rapid autonomic fear responses. 2) The slow cortical 'high road' (thalamus → sensory cortex → amygdala): slower (~40-50 ms) but detailed and accurate — allows full perceptual analysis of whether the threat is real. LeDoux proposed this dual-route model. The low road explains why conditioned fear responses can occur to degraded or masked stimuli, and why anxiety responses can be triggered before conscious awareness.", difficulty: "hard" },
    // === BRAINSTEM ===
    { question: "What is Wallenberg (lateral medullary) syndrome — its cause, structures involved, and deficit pattern?", answer: "Cause: PICA (posterior inferior cerebellar artery) occlusion — the most common lateral medullary stroke. Structures and deficits: 1) Trigeminal nucleus (ipsilateral face pain/temp loss), 2) Descending sympathetic fibers (ipsilateral Horner's: ptosis, miosis, anhidrosis), 3) Inferior cerebellar peduncle (ipsilateral limb/gait ataxia), 4) Vagal nuclei: dysarthria, dysphagia, hoarseness, 5) Vestibular nuclei: vertigo, nystagmus, 6) Spinothalamic tract: contralateral body pain/temperature loss. The classic crossed pattern: ipsilateral face + contralateral body sensory loss is pathognomonic.", difficulty: "hard" },
    { question: "What is locked-in syndrome, what causes it, and why is consciousness preserved?", answer: "Locked-in syndrome results from extensive bilateral ventral pontine damage — most commonly from basilar artery thrombosis, but also pontine hemorrhage or central pontine myelinolysis. It destroys the corticobulbar and corticospinal tracts (causing complete paralysis of voluntary movement) and motor cranial nerve nuclei (causing anarthria and dysphagia). However, the reticular formation and ARAS are spared (often) → full consciousness preserved. The dorsal midbrain (vertical gaze and eyelid control) is usually intact → vertical eye movements and blinking remain the only voluntary motor output. Patients are aware but cannot signal it except through eye movements.", difficulty: "hard" },
    { question: "What is Parinaud's syndrome, what causes it, and what are its components?", answer: "Parinaud's (dorsal midbrain/pretectal) syndrome: 1) Impaired upward vertical gaze (superior colliculus/posterior commissure compression), 2) Convergence-retraction nystagmus (eyes converge and retract into orbits rather than moving upward when upward gaze is attempted), 3) Light-near dissociation (pupils fail to constrict to light but constrict normally to near accommodation — because the near reflex uses a different pathway). Cause: compression of the dorsal midbrain (tectum) — most commonly by a pineal region tumor (germinoma, pinealoma) or hydrocephalus from aqueductal obstruction.", difficulty: "hard" },
    // === CEREBELLUM ===
    { question: "What are the three functional divisions of the cerebellum, their connections, and their clinical damage patterns?", answer: "1) Vestibulocerebellum (flocculonodular lobe): connects with vestibular nuclei; controls balance and eye movements. Damage → truncal/gait ataxia, nystagmus, cannot stand with eyes closed. 2) Spinocerebellum (vermis/paravermis): receives spinocerebellar input; regulates posture and ongoing movement. Damage → gait ataxia (vermis), ipsilateral limb ataxia (paravermis). 3) Cerebrocerebellum (lateral hemispheres): connects with cortex via pons; motor planning, timing, cognition. Damage → ipsilateral appendicular ataxia, dysmetria, intention tremor, dysdiadochokinesia, scanning dysarthria, Schmahmann's syndrome.", difficulty: "hard" },
    { question: "Why is cerebellar damage ipsilateral rather than contralateral to the lesion?", answer: "Cerebellar lesions produce ipsilateral deficits because the cerebellar output crosses TWICE, canceling out. First crossing: output from the dentate nucleus exits via the superior cerebellar peduncle and crosses the midline to the contralateral VL thalamus and red nucleus (decussation of the superior cerebellar peduncles in the midbrain). Second crossing: the corticospinal tract (which carries the final motor command influenced by cerebellar input) crosses again at the pyramidal decussation in the medulla. Net result: right dentate → left VL thalamus → left motor cortex → crosses again → right spinal motor neurons → right muscles. A right cerebellar lesion causes right-sided ataxia.", difficulty: "hard" },
    // === WHITE MATTER ===
    { question: "What is conduction aphasia and what white matter tract damage produces it?", answer: "Conduction aphasia is characterized by fluent, phonemically paraphasic speech with intact auditory comprehension but severely impaired repetition (repeating words and phrases back) — the inability to 'conduct' the heard word back into the speech production system. Cause: damage to the arcuate fasciculus (the curved bundle connecting Broca's area in the left inferior frontal gyrus with Wernicke's area in the left posterior superior temporal gyrus) and/or the underlying white matter of the inferior parietal lobule. Because both Broca's and Wernicke's areas are intact, fluency and comprehension are preserved; repetition requires their connection, which is severed.", difficulty: "hard" },
    { question: "What is a pure motor hemiparesis and what anatomical location does it implicate?", answer: "Pure motor hemiparesis: complete contralateral face, arm, and leg weakness with no sensory deficit, no visual field cut, and no higher cortical dysfunction. This pattern indicates a small, capsular lacunar infarct in the posterior limb of the internal capsule — where all corticospinal and corticobulbar fibers are packed into a tiny area, such that a small infarct can interrupt all motor fibers without affecting adjacent sensory fibers (which travel in separate white matter). Other locations producing pure motor stroke: basis pontis, corona radiata. The purity of the deficit precisely localizes the lesion.", difficulty: "medium" },
    { question: "What are the three categories of white matter tracts and key examples of each?", answer: "1) Projection fibers (cortex ↔ subcortical/spinal): Internal capsule (corticospinal, corticobulbar, thalamocortical), cerebral peduncles, corona radiata. 2) Commissural fibers (connect hemispheres): Corpus callosum (genu = frontal, body = motor/sensory, splenium = occipital/parietal), anterior commissure (temporal lobes/olfactory), posterior commissure (pretectal — pupillary reflex). 3) Association fibers (within hemisphere): Arcuate fasciculus/SLF (language), uncinate fasciculus (OFC ↔ temporal), inferior longitudinal fasciculus (occipital-temporal/ventral stream), cingulum (limbic).", difficulty: "medium" },
    // === SUBCORTICAL PRINCIPLES ===
    { question: "What is Schmahmann's syndrome (cerebellar cognitive affective syndrome)?", answer: "Cerebellar cognitive affective syndrome (Schmahmann, 1998): a constellation of cognitive and behavioral deficits produced by damage to the posterior cerebellum (especially posterior vermis and right posterolateral hemisphere). Features: executive dysfunction (planning, working memory, set-shifting), linguistic difficulties (dysprosodia, word-finding, impaired syntax), visuospatial deficits, and personality/affective changes (affective blunting, disinhibition, impulsive behavior). The syndrome demonstrates that the cerebellum contributes to cognition and emotion via its cortical connections (particularly with PFC and posterior parietal cortex), not just to motor control.", difficulty: "hard" },
    { question: "How does the habenula relate to depression and reward processing?", answer: "The habenular nuclei (epithalamus) connect the limbic forebrain to brainstem monoaminergic systems (via the fasciculus retroflexus to the raphe nuclei and interpeduncular nucleus). The lateral habenula is particularly important: it receives input signaling negative outcomes and reward prediction errors, and projects inhibitory signals to the VTA and raphe, suppressing dopamine and serotonin release in response to frustration or unmet expectations. Hyperactivity of the lateral habenula is proposed as a mechanism of anhedonia and 'depressive brake' on reward. Deep brain stimulation of the lateral habenula and ketamine's rapid antidepressant effect (which partly involves suppressing pathological burst firing in the habenula) both support this model.", difficulty: "hard" },
  ];

  const insertedFC = await db.insert(flashcardsTable).values(flashcards.map(f => ({ ...f, topicId: TOPIC_ID }))).returning();
  console.log(`  ✓ ${insertedFC.length} flashcards`);

  // ──────────────────────────────────────────────────────────────────────
  // QUIZ QUESTIONS
  // ──────────────────────────────────────────────────────────────────────
  const regular = [
    { question: "A patient sustains a small lacunar stroke in the posterior limb of the internal capsule. What is the expected deficit?", optionA: "Contralateral hemisensory loss with preserved motor function", optionB: "Contralateral pure motor hemiparesis — face, arm, and leg — with no sensory or higher cortical deficits", optionC: "Contralateral homonymous hemianopia with macular sparing", optionD: "Ipsilateral cerebellar ataxia with contralateral weakness", correctAnswer: "B", explanation: "The posterior limb of the internal capsule contains the densely packed corticospinal and corticobulbar tracts. A tiny lacunar infarct here destroys all motor fibers without involving nearby sensory fibers (in the more posterior internal capsule or corona radiata), producing the classic 'pure motor stroke' with complete face-arm-leg weakness and no sensory or cognitive deficit — one of the most precisely localizing syndromes in clinical neurology.", examOnly: false },
    { question: "What is the primary function of the ventral lateral (VL) thalamic nucleus?", optionA: "Relaying visual information from the retina to the primary visual cortex", optionB: "Relaying cerebellar output (from the dentate nucleus) to the motor and premotor cortex", optionC: "Connecting the hippocampus to the cingulate cortex in the Papez memory circuit", optionD: "Monitoring and regulating the sleep-wake cycle via the ARAS", correctAnswer: "B", explanation: "The ventral lateral (VL) nucleus receives input from the dentate nucleus of the cerebellum via the superior cerebellar peduncle (after decussation in the midbrain) and relays it to the motor and premotor cortex. This is the final relay through which cerebellar output influences voluntary movement. The ventral anterior (VA) nucleus similarly relays basal ganglia output to motor cortex.", examOnly: false },
    { question: "A patient develops explosive, flinging movements of the left arm and leg following a right-sided stroke. Which structure is most likely affected?", optionA: "Right putamen", optionB: "Right subthalamic nucleus", optionC: "Left substantia nigra pars compacta", optionD: "Right caudate nucleus", correctAnswer: "B", explanation: "Unilateral subthalamic nucleus (STN) lesions produce hemiballismus — violent, contralateral flinging movements. The STN normally excites the GPi, which inhibits the thalamus. Loss of STN → reduced GPi activity → thalamus disinhibited → motor cortex overactivated → explosive contralateral limb movements. The right STN controls the left body (contralateral, like all subcortical motor structures).", examOnly: false },
    { question: "Which statement best describes the memory deficit associated with bilateral hippocampal damage?", optionA: "Profound retrograde amnesia for all episodic memory, with intact ability to form new memories going forward", optionB: "Profound anterograde amnesia (inability to form new long-term declarative memories) with relatively preserved remote memories and intact procedural learning", optionC: "Selective loss of semantic memory (facts) with preserved episodic memory (personal events)", optionD: "Impaired implicit/procedural memory with intact explicit declarative memory", correctAnswer: "B", explanation: "Bilateral hippocampal damage (as in patient H.M. following bilateral medial temporal lobectomy) produces dense anterograde amnesia — inability to form new explicit (declarative) memories — while leaving remote (consolidated) memories relatively intact and procedural (implicit) learning completely preserved. The temporal gradient reflects that older memories have been consolidated in the neocortex and are no longer dependent on hippocampal integrity.", examOnly: false },
    { question: "In the basal ganglia direct pathway, what is the net effect on the thalamus when the striatum is activated?", optionA: "Increased inhibition of the thalamus — movement is suppressed", optionB: "Disinhibition of the thalamus — movement is facilitated", optionC: "Increased excitation of the subthalamic nucleus — movement is stopped", optionD: "No change — the direct pathway only affects the cerebellum", correctAnswer: "B", explanation: "Direct pathway: striatum (activated) → GPi/SNr inhibited (D1 MSNs are GABAergic) → thalamus disinhibited (less GABA from GPi) → thalamus more active → motor cortex facilitated → movement. This is the 'go' signal. Dopamine augments this by exciting D1 receptors on direct-pathway striatal neurons. The indirect pathway has the opposite net effect (movement suppression).", examOnly: false },
    { question: "A patient with a right posterior parietal lesion fails to respond to objects in the left visual field and consistently draws only the right half of a clock face. What syndrome is this?", optionA: "Prosopagnosia", optionB: "Hemispatial neglect", optionC: "Hemianopia with left homonymous visual field cut", optionD: "Simultanagnosia", correctAnswer: "B", explanation: "Hemispatial neglect — failure to attend to, represent, or respond to the contralesional (left) hemispace, despite intact primary vision. Caused by right parietal/temporoparietal junction damage. Clock drawing and line bisection tests are diagnostic: neglect patients draw only the right half of the clock or bisect lines well to the right of center. Unlike hemianopia (a sensory deficit), neglect is an attentional failure — the information is potentially available but not processed.", examOnly: false },
    { question: "The Papez circuit involves all of the following structures EXCEPT:", optionA: "Hippocampus", optionB: "Mammillary bodies", optionC: "Substantia nigra", optionD: "Anterior thalamic nucleus", correctAnswer: "C", explanation: "The Papez circuit: hippocampus → fornix → mammillary bodies → mammillothalamic tract → anterior thalamic nucleus → cingulate gyrus → parahippocampal cortex → entorhinal cortex → hippocampus. The substantia nigra is part of the basal ganglia, not the Papez circuit. Damage to any Papez circuit node — including the mammillary bodies (Korsakoff syndrome), fornix, or anterior thalamus — can produce anterograde amnesia.", examOnly: false },
    { question: "What distinguishes Wernicke's aphasia from Broca's aphasia on clinical examination?", optionA: "Broca's: fluent speech with poor comprehension. Wernicke's: nonfluent speech with intact comprehension", optionB: "Broca's: nonfluent, effortful speech with intact comprehension. Wernicke's: fluent, paraphasic speech with impaired comprehension", optionC: "Both produce nonfluent speech, but Wernicke's also involves limb apraxia", optionD: "Wernicke's: complete mutism. Broca's: fluent with semantic paraphasias", correctAnswer: "B", explanation: "Broca's aphasia (left inferior frontal, BA 44/45): nonfluent, telegraphic, effortful speech; intact comprehension (especially single words); impaired repetition; often right face/hand hemiparesis. Wernicke's aphasia (left posterior STG, BA 22): fluent, phonemically or semantically paraphasic speech (neologisms, 'word salad'); severely impaired auditory comprehension; impaired repetition; no motor deficit. The fluency distinction is the key clinical discriminator.", examOnly: false },
    { question: "What neuropathological process causes Korsakoff syndrome and what is the characteristic neuropsychological profile?", optionA: "Dopamine neuron loss in the striatum → procedural memory impairment + movement disorder", optionB: "Thiamine deficiency → mammillary body and dorsomedial thalamus damage → dense anterograde amnesia + retrograde amnesia with confabulation", optionC: "Amyloid-beta accumulation in the hippocampus → progressive encoding deficit with slow onset", optionD: "Alpha-synuclein pathology in the brainstem → fluctuating consciousness and visual hallucinations", correctAnswer: "B", explanation: "Korsakoff syndrome: thiamine (B1) deficiency damages mammillary bodies and the dorsomedial thalamus (the thalamic node most connected with the PFC and limbic system). This produces: dense anterograde amnesia (cannot form new explicit memories), retrograde amnesia with a temporal gradient (recent more than remote), and confabulation (unintentional fabrication of plausible-sounding memories to fill gaps). Intelligence and procedural memory are relatively preserved.", examOnly: false },
    { question: "What characterizes lateral medullary (Wallenberg) syndrome that makes it a paradigmatic brainstem syndrome?", optionA: "It causes bilateral cortical blindness from occipital ischemia", optionB: "It produces a classic crossed sensory pattern — ipsilateral face and contralateral body pain/temperature loss — along with ipsilateral Horner's, ataxia, and dysphagia from a single compact brainstem lesion", optionC: "It causes complete hemiplegia with preserved sensation, localizing to the medullary pyramids", optionD: "It produces locked-in syndrome from bilateral ventral pontine damage", correctAnswer: "B", explanation: "Wallenberg (lateral medullary) syndrome from PICA occlusion damages multiple adjacent structures in one compact region: the trigeminal nucleus (ipsilateral face sensory loss), spinothalamic tract (contralateral body pain/temp loss — already crossed), descending sympathetics (ipsilateral Horner's), inferior cerebellar peduncle (ipsilateral ataxia), and vagal nuclei (dysarthria, dysphagia). The crossed sensory pattern — same-side face, opposite-side body — is the brainstem's signature and allows precise anatomical localization.", examOnly: false },
  ];

  const examOnly = [
    { question: "Why does bilateral amygdala damage impair fear conditioning but not all forms of emotional learning?", optionA: "The amygdala only processes positive emotions; negative emotions are processed in the anterior cingulate", optionB: "The amygdala is specifically required for conditioning emotional responses to previously neutral stimuli (CS-US pairing) via its connection with the hippocampus and hypothalamus, but declarative memory for the fact that a stimulus was paired with shock remains intact via hippocampal-cortical pathways", optionC: "Amygdala damage impairs all memory, not just emotional memory, because the amygdala is the primary memory consolidation structure", optionD: "Bilateral amygdala damage only impairs fear of familiar faces, leaving fear of novel threats intact", correctAnswer: "B", explanation: "The amygdala (especially the basolateral complex) is essential for Pavlovian fear conditioning — learning that a neutral CS (tone) predicts an aversive US (shock). This requires amygdala plasticity: LTP at BLA synapses drives output to the central nucleus → autonomic fear responses. People with bilateral amygdala damage cannot acquire conditioned fear responses (no autonomic fear to the CS) yet can explicitly remember being told about the CS-US pairing (hippocampus intact). This dissociation demonstrates the independent storage of explicit and implicit emotional memories.", examOnly: true },
    { question: "How does the cerebellum contribute to motor learning, and what cellular mechanism underlies it?", optionA: "The cerebellum learns by strengthening cortical-striatal connections through dopamine-dependent LTP", optionB: "Climbing fiber signals from the inferior olive (error signals) cause long-term depression (LTD) of parallel fiber-Purkinje cell synapses, reducing Purkinje cell inhibition of deep cerebellar nuclei — gradually building a stored motor program that improves with practice", optionC: "The cerebellum learns through NMDA receptor-dependent LTP in the dentate nucleus, identical to hippocampal learning", optionD: "Mossy fibers carry error signals and directly modify granule cell firing to encode motor memories", correctAnswer: "B", explanation: "Cerebellar motor learning is mediated by climbing fibers from the inferior olivary nucleus, which encode motor error signals. When a movement is executed incorrectly, climbing fibers fire and produce complex spikes in Purkinje cells — coincident activation of the parallel fiber and climbing fiber inputs induces LTD at the parallel fiber-Purkinje cell synapse (reducing Purkinje cell output). Since Purkinje cells tonically inhibit deep cerebellar nuclei (primarily the dentate), LTD reduces this inhibition → more cerebellar output → movement correction. Over trials, LTD builds a motor program that gradually corrects the error.", examOnly: true },
    { question: "What is the functional significance of the dual projections from the amygdala — the stria terminalis and the ventral amygdalofugal pathway?", optionA: "The stria terminalis carries auditory input to the amygdala; the ventral amygdalofugal pathway carries visual input", optionB: "The stria terminalis projects primarily to the hypothalamus and bed nucleus (BNST) — mediating sustained, contextual anxiety; the ventral amygdalofugal pathway projects to the nucleus accumbens, PFC, and brainstem — mediating acute fear responses, motivation, and cortical emotional regulation", optionC: "Both pathways are efferent but project exclusively to the hippocampus for memory consolidation of emotional events", optionD: "The stria terminalis is the main afferent pathway; the ventral amygdalofugal pathway is the main efferent pathway", correctAnswer: "B", explanation: "Amygdala outputs travel via two distinct white-matter routes with different functional profiles. The stria terminalis (a long, arching fiber bundle running alongside the caudate along the roof of the lateral ventricle) projects to the hypothalamus, septal nuclei, and bed nucleus of the stria terminalis (BNST) — the BNST mediates sustained, non-specific anxiety responses to uncertain threat. The shorter ventral amygdalofugal pathway (VAF) projects to the nucleus accumbens, brainstem (for autonomic and startle responses), and PFC (for emotional regulation and integration with cognition). This anatomical segregation underlies differences between acute fear (more VAF-dependent) and chronic anxiety (more BNST-dependent).", examOnly: true },
    { question: "What is the functional role of the thalamic reticular nucleus (TRN) during selective attention, and why is this clinically important?", optionA: "The TRN generates action potentials in the thalamo-cortical relay neurons, driving sensory signal amplification", optionB: "The TRN provides GABAergic inhibition of thalamo-cortical relay neurons, modulating which sensory signals are 'gated through' to cortex — focusing cortical attention by suppressing irrelevant inputs while allowing task-relevant signals to pass; disruption is implicated in attentional disorders and sleep spindle generation", optionC: "The TRN generates the delta rhythm of deep sleep and is destroyed in all patients with insomnia", optionD: "The TRN is the primary relay for pain signals from the spinal cord to the somatosensory cortex", correctAnswer: "B", explanation: "The TRN is a sheet of GABAergic neurons forming a reticular shell around the dorsal thalamus. It does not project to the cortex — instead it projects inhibitory axons onto thalamocortical relay neurons. It receives collateral inputs from both thalamocortical and corticothalamic axons, making it ideally positioned to be a 'searchlight' — suppressing irrelevant thalamic relay channels during focused attention and amplifying relevant ones. Sleep spindles (the hallmark of NREM stage 2 sleep) are generated by rhythmic TRN inhibition of relay neurons. TRN dysfunction is proposed in ADHD and certain schizophrenia models (impaired sensory gating).", examOnly: true },
    { question: "Why does the caudate nucleus show selective early degeneration in Huntington's disease, and what motor phenotype results?", optionA: "The caudate is most vulnerable because it contains the dopaminergic neurons targeted by the huntingtin protein's polyglutamine expansion", optionB: "The caudate (and putamen) striatal neurons — particularly D2-receptor-expressing medium spiny neurons of the indirect pathway — are selectively vulnerable to mutant huntingtin toxicity; their loss removes the brake on movement, disinhibiting the thalamus and producing chorea (involuntary, dance-like movements)", optionC: "Caudate degeneration causes pure cognitive impairment without motor symptoms in Huntington's disease; the chorea is produced by cortical degeneration", optionD: "The caudate degenerates because it is the most metabolically active structure and HD preferentially destroys the highest-energy-consuming regions", correctAnswer: "B", explanation: "Mutant huntingtin (with expanded polyglutamine repeats) is selectively toxic to striatal medium spiny neurons (MSNs), particularly those of the indirect pathway (expressing D2 receptors and enkephalin) — these die first. Loss of these neurons removes their GABAergic inhibition of GPe → GPe becomes overactive → inhibits STN → GPi becomes underactive → thalamus is disinhibited → motor cortex is overactivated → choreiform (hyperkinetic) movements. Later, direct pathway neurons (D1-expressing) and eventually the entire striatum degenerate, producing later-stage rigidity and bradykinesia.", examOnly: true },
    { question: "What is the anatomical basis of Parinaud's syndrome and what does the pupillary finding (light-near dissociation) tell you about the anatomy of the pupillary light reflex?", optionA: "Parinaud's syndrome destroys the pretectal nuclei bilaterally, which mediate the light reflex; the near reflex pathway through the Edinger-Westphal nucleus is anatomically separate and spared, explaining why light-near dissociation occurs", optionB: "Parinaud's syndrome impairs all pupillary function including near responses; light-near dissociation is actually caused by sympathetic damage, not pretectal damage", optionC: "The near reflex is spared because it is mediated by the thalamus, not the midbrain", optionD: "Light-near dissociation occurs because the optic nerve is damaged, not the pretectal region", correctAnswer: "A", explanation: "The pupillary light reflex arc: retina → optic nerve → optic chiasm → pretectal nucleus (bilateral) → Edinger-Westphal nucleus (CN III) → ciliary ganglion → iris sphincter. In Parinaud's syndrome, dorsal midbrain (tectum) compression destroys the pretectal nuclei → light reflex pathway is broken → pupils fail to constrict to light. However, the near reflex pathway uses a separate, more ventral route through the visual cortex → cortical fibers to the Edinger-Westphal nucleus, bypassing the pretectum → near accommodation still triggers pupillary constriction. This anatomical dissociation (pretectal: light; cortical: near) explains light-near dissociation.", examOnly: true },
    { question: "What is the functional significance of adult hippocampal neurogenesis and what factors regulate it?", optionA: "Adult hippocampal neurogenesis primarily generates new astrocytes that repair damaged hippocampal tissue after injury", optionB: "New granule cells continuously added to the dentate gyrus are involved in pattern separation (distinguishing similar memories) and potentially in clearing outdated memories; positive regulators include aerobic exercise, environmental enrichment, and antidepressants; negative regulators include stress, glucocorticoids, aging, and alcohol", optionC: "Hippocampal neurogenesis is relevant only during development; it ceases completely by early adulthood in humans", optionD: "New hippocampal neurons are generated exclusively from ependymal cells lining the lateral ventricle, not from dentate gyrus progenitors", correctAnswer: "B", explanation: "Adult hippocampal neurogenesis occurs in the subgranular zone of the dentate gyrus, producing new granule cells that mature over weeks and integrate into existing circuits. Their proposed function: pattern separation — the ability to distinguish highly similar experiences as distinct memories — is thought to require new neurons, which provide a degree of orthogonality to stored representations. Regulators: exercise (aerobic, the most consistent promoter of neurogenesis in animal and human studies), environmental enrichment, SSRIs (antidepressant neurogenic effect may contribute to therapeutic lag), and social interaction promote it; chronic stress, elevated glucocorticoids, aging, alcohol, and sleep deprivation suppress it.", examOnly: true },
    { question: "How does the nucleus accumbens' shell vs. core distinction matter clinically?", optionA: "The shell responds only to novel stimuli; the core responds only to familiar stimuli, with no clinical relevance to either", optionB: "The accumbens shell (connected with amygdala, hypothalamus, and brainstem) mediates primary reward and the direct motivational impact of drugs; the core (connected with dorsal striatum, PFC, and motor systems) mediates instrumental learned behaviors and compulsive habit execution — explaining why addiction transitions from drug 'liking' (shell) to compulsive drug-seeking regardless of consequences (core)", optionC: "The shell generates the aversive component of withdrawal; the core generates the pleasurable component of drug use, with both being equivalent targets for treatment", optionD: "The shell and core differ only anatomically, with no functional distinction between them in humans", correctAnswer: "B", explanation: "The shell/core distinction in the nucleus accumbens maps onto different phases of addiction and different clinical targets. Early addiction: the shell mediates the primary rewarding effects via dopamine surges — 'liking' and hedonic impact. With repeated use: the core becomes more critical as instrumental conditioning solidifies — the drug loses hedonic appeal but seeking behavior becomes habit-like and compulsive (mediated by core connections with dorsal striatum and motor output). This explains clinical observations: addicts in late-stage addiction often describe using without pleasure but being unable to stop. The core is the target for habit-breaking interventions.", examOnly: true },
  ];

  const allQs = [...regular, ...examOnly].map(q => ({ ...q, topicId: TOPIC_ID }));
  const insertedQs = await db.insert(quizQuestionsTable).values(allQs).returning();
  console.log(`  ✓ ${insertedQs.length} quiz questions`);

  // Study guide
  const [sg] = await db.insert(studyGuidesTable).values({
    topicId: TOPIC_ID,
    title: "Brain Structures — Cortical and Subcortical",
    content: sgContent,
  }).returning();
  console.log(`  ✓ Study guide id=${sg.id}`);

  // Practice exam
  const [exam] = await db.insert(practiceExamsTable).values({
    topicId: TOPIC_ID,
    title: "Brain Structures Practice Exam",
    timeLimit: 90,
    passingScore: 70,
  }).returning();

  const allQsFromDb = await db.select({ id: quizQuestionsTable.id }).from(quizQuestionsTable).where(eq(quizQuestionsTable.topicId, TOPIC_ID));
  await db.insert(practiceExamQuestionsTable).values(allQsFromDb.map((q, i) => ({ examId: exam.id, questionId: q.id, questionOrder: i + 1 })));
  console.log(`  ✓ Practice exam with ${allQsFromDb.length} questions`);

  console.log(`\n✅ Brain Structures rework complete!`);
  console.log(`   Flashcards: ${insertedFC.length} | Questions: ${insertedQs.length} | Study guide: updated`);
}

rework().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
