import { db } from "./index";
import { eq } from "drizzle-orm";
import {
  topicsTable, flashcardsTable, quizQuestionsTable,
  studyGuidesTable, practiceExamsTable, practiceExamQuestionsTable,
} from "./schema";

const TOPIC_ID = 15;

async function rework() {
  console.log("Reworking Neurocognitive Disorders v2 — prose genetics, PSP added, age of onset, critical considerations, differential diagnosis...");

  const exams = await db.select({ id: practiceExamsTable.id }).from(practiceExamsTable).where(eq(practiceExamsTable.topicId, TOPIC_ID));
  for (const e of exams) {
    await db.delete(practiceExamQuestionsTable).where(eq(practiceExamQuestionsTable.examId, e.id));
  }
  await db.delete(practiceExamsTable).where(eq(practiceExamsTable.topicId, TOPIC_ID));
  await db.delete(quizQuestionsTable).where(eq(quizQuestionsTable.topicId, TOPIC_ID));
  await db.delete(flashcardsTable).where(eq(flashcardsTable.topicId, TOPIC_ID));
  await db.delete(studyGuidesTable).where(eq(studyGuidesTable.topicId, TOPIC_ID));
  console.log("  ✓ Cleared old data");

  await db.update(topicsTable).set({
    description: "Comprehensive study of major neurocognitive disorders — Alzheimer's disease, vascular dementia, Lewy body disorders, FTD, Huntington's disease, PSP, NPH, TBI/CTE, and prion diseases — covering pathophysiology, genetics, neuropsychological profiles, critical clinical considerations, and differential diagnosis."
  }).where(eq(topicsTable.id, TOPIC_ID));

  // ─────────────────────────────────────────────────────────────────
  // FLASHCARDS (retained + expanded for PSP)
  // ─────────────────────────────────────────────────────────────────
  const flashcards = [
    { question: "What is the DSM-5 distinction between minor and major neurocognitive disorder?", answer: "Minor NCD (MCI): modest cognitive decline (~1-2 SD below normative mean) that does NOT impair functional independence — patient compensates with effort, strategies, or extra time. Major NCD (Dementia): substantial cognitive decline (typically >2 SD) with impairment in functional independence — assistance is required with everyday activities. Both require documented decline from a prior level and objective cognitive assessment.", difficulty: "medium" },
    { question: "What are the two core neuropathological hallmarks of Alzheimer's disease?", answer: "1) Amyloid plaques (neuritic/senile plaques): extracellular deposits of aggregated amyloid-beta (Aβ42) peptide — derived from cleavage of APP by β-secretase (BACE1) and γ-secretase (presenilin complex). 2) Neurofibrillary tangles (NFTs): intraneuronal accumulations of hyperphosphorylated tau protein that has detached from microtubules and paired into helical filaments. Synaptic density loss (not plaque/tangle burden per se) is the best correlate of cognitive impairment.", difficulty: "medium" },
    { question: "What is the amyloid cascade hypothesis of Alzheimer's disease?", answer: "The amyloid cascade hypothesis proposes that accumulation of amyloid-beta (Aβ42) is the initiating event in AD pathogenesis. Aβ42 oligomers (most neurotoxic form) disrupt synaptic function → trigger tau hyperphosphorylation → neuroinflammation (microglial activation) → synaptic loss and neuronal death. Supported by familial AD genetics: APP, PSEN1/2 mutations all increase Aβ42 production or reduce clearance.", difficulty: "hard" },
    { question: "What is the APOE ε4 allele and how does it affect Alzheimer's disease risk?", answer: "APOE ε4 (chromosome 19) is the most significant genetic risk factor for sporadic AD. One copy increases risk ~3x; two copies ~8-12x. APOE ε4 impairs Aβ clearance, promotes tau hyperphosphorylation, accelerates neuroinflammation, and dysregulates lipid metabolism in neurons. APOE ε2 is protective (~40% reduced risk vs ε3). APOE ε3 is neutral. APOE genotype is a risk modifier — not a deterministic cause — unlike the autosomal dominant FAD mutations.", difficulty: "hard" },
    { question: "What are the three autosomal dominant genes causing familial early-onset Alzheimer's disease?", answer: "1) PSEN1 (presenilin-1, chromosome 14): Most common FAD gene; >400 mutations; onset typically 30s-50s; alters γ-secretase → increased Aβ42:Aβ40 ratio. 2) PSEN2 (presenilin-2, chromosome 1): Rarer; slightly later onset than PSEN1; same γ-secretase mechanism. 3) APP (amyloid precursor protein, chromosome 21): Mutations near cleavage sites → overproduction of Aβ42. Also explains why Down syndrome (trisomy 21, 3 APP copies) causes AD pathology by age 40.", difficulty: "hard" },
    { question: "What is Braak staging of Alzheimer's disease?", answer: "Braak staging describes the stereotyped spread of neurofibrillary tau pathology: Stages I-II (transentorhinal): NFTs confined to entorhinal cortex and perirhinal cortex → earliest memory impairment (EC is the hippocampal encoding gateway). Stages III-IV (limbic): NFTs spread to hippocampus, amygdala, basal forebrain → overt amnestic syndrome. Stages V-VI (neocortical): NFTs in association neocortex → full multi-domain dementia. Tau pathology stage correlates better with cognitive severity than amyloid plaque burden.", difficulty: "hard" },
    { question: "What is the characteristic neuropsychological profile of Alzheimer's disease?", answer: "Core deficit: ENCODING FAILURE — poor free recall AND poor recognition (information not properly stored); fails to benefit from cues; high intrusion errors; rapid forgetting. Early: anterograde amnesia, anomia, topographic disorientation, category verbal fluency worse than letter fluency. Middle: visuospatial decline, executive dysfunction, acalculia, constructional apraxia. Late: language breakdown, limb apraxia, agnosia, complete ADL dependence. Key distinction from subcortical dementias: both free recall and recognition impaired (encoding deficit), not just retrieval.", difficulty: "hard" },
    { question: "What pharmacological treatments are approved for Alzheimer's disease and what do they do?", answer: "1) Cholinesterase inhibitors (donepezil, rivastigmine, galantamine): Inhibit acetylcholinesterase → increase synaptic ACh — compensating for nucleus basalis of Meynert cholinergic loss. Approved mild-moderate (donepezil also severe AD). Modest symptomatic benefit; do not alter disease course. 2) Memantine: NMDA receptor antagonist — reduces glutamate-mediated excitotoxicity. Approved moderate-severe AD. 3) Anti-amyloid immunotherapies (lecanemab, donanemab): Clear Aβ plaques; FDA-approved with demonstrated slowing of decline in early AD (A+/T+ patients); risk of ARIA (amyloid-related imaging abnormalities).", difficulty: "hard" },
    { question: "What is vascular cognitive impairment (VCI) and what are its main mechanisms?", answer: "VCI is the spectrum of cognitive disorders caused by cerebrovascular disease — from minor VCI to major vascular dementia (VaD). Second most common cause of dementia (~15-20% of cases). Mechanisms: large vessel disease (cortical strokes → focal deficits, stepwise progression), small vessel disease (lacunar infarcts, white matter hyperintensities — frontal-subcortical syndrome), strategic infarcts (thalamus, angular gyrus — disproportionate cognitive impact from small lesions), cerebral amyloid angiopathy (CAA — lobar hemorrhages, cortical microbleeds), and CADASIL (hereditary small vessel disease from NOTCH3 mutations).", difficulty: "medium" },
    { question: "What is the characteristic neuropsychological profile of vascular dementia?", answer: "VaD shows a frontal-subcortical pattern: prominent executive dysfunction (planning, set-shifting, cognitive flexibility), psychomotor slowing, attention and processing speed deficits, and gait disturbance — with relatively preserved memory (retrieval deficit more than encoding; recognition relatively spared). Stepwise progression (each infarct adds a step) vs. gradual decline in AD. Temporal relationship to a vascular event is diagnostically important. Focal neurological signs often present.", difficulty: "hard" },
    { question: "What is CADASIL and why is it clinically important?", answer: "CADASIL (Cerebral Autosomal Dominant Arteriopathy with Subcortical Infarcts and Leukoencephalopathy) is caused by NOTCH3 mutations — the most common hereditary cerebral small vessel disease. Clinical: early-onset migraine with aura (30s-40s), recurrent subcortical strokes (lacunar), progressive subcortical dementia, and psychiatric features (depression). MRI hallmark: white matter lesions prominently in anterior temporal poles and external capsule — distinctive. Occurs without traditional vascular risk factors. Autosomal dominant inheritance.", difficulty: "hard" },
    { question: "What are the four core clinical features of dementia with Lewy bodies (DLB)?", answer: "1) Fluctuating cognition (marked variation in alertness/attention; daytime somnolence; episodes of staring or confusion). 2) Recurrent well-formed visual hallucinations (vivid, detailed — people, animals; often non-threatening initially). 3) REM sleep behavior disorder (RBD) — acting out dreams; often precedes dementia by years. 4) Parkinsonism (bradykinesia, rigidity, rest tremor — typically after or concurrent with cognitive onset, unlike PD). Two core features = probable DLB; one = possible DLB. Supportive: abnormal DAT scan, low cardiac MIBG, polysomnographic RBD confirmation.", difficulty: "hard" },
    { question: "What is the distinction between Parkinson's disease dementia (PDD) and dementia with Lewy bodies (DLB)?", answer: "The 1-year rule (temporal relationship): PDD: Parkinson's motor symptoms clearly precede cognitive decline by ≥1 year. DLB: Cognitive symptoms and parkinsonism occur within 1 year of each other (or cognition first). Both share Lewy body (alpha-synuclein) pathology. PDD: more posterior cortical + frontal-subcortical involvement, often more preserved early. DLB: often more widespread early cortical involvement; more prominent early visuospatial and attentional dysfunction. Practically, they represent a disease spectrum.", difficulty: "hard" },
    { question: "Why are antipsychotic medications dangerous in DLB/PDD?", answer: "Patients with DLB/PDD have severe striatal dopaminergic deficits AND reduced D2/D3 receptor expression. Typical and most atypical antipsychotics block dopamine D2 receptors → can precipitate severe neuroleptic sensitivity reaction: acute parkinsonism, sedation, altered consciousness, autonomic instability, and sudden death risk. This is a BLACK BOX warning for DLB. If antipsychotics are absolutely required for severe psychosis, quetiapine or clozapine (minimal D2 blockade) are preferred. All dopamine D2 blockers (including metoclopramide, prochlorperazine) must be avoided.", difficulty: "hard" },
    { question: "What are the three main clinical subtypes of frontotemporal lobar degeneration (FTLD)?", answer: "1) Behavioral variant FTD (bvFTD): Early behavioral/personality change — disinhibition, apathy, loss of empathy, hyperorality, stereotyped/perseverative behaviors; executive dysfunction; relatively preserved episodic memory early. 2) Semantic variant PPA (svPPA): Loss of word meaning — fluent speech with profound anomia, single-word comprehension loss, surface dyslexia; left anterior temporal lobe. 3) Nonfluent/agrammatic variant PPA (nfvPPA): Effortful, apraxic speech, agrammatism, phonological errors; left posterior frontal-insular. All three share frontotemporal atrophy with relative posterior cortical sparing early.", difficulty: "hard" },
    { question: "What genetic mutations are associated with FTD and what are their clinical correlates?", answer: "C9orf72 hexanucleotide repeat expansion: Most common familial FTD/ALS cause; produces FTD-ALS overlap; prominent psychiatric features (psychosis, anxiety). GRN (progranulin, chromosome 17): Haploinsufficiency → loss of neurotrophic support; often asymmetric cortical syndrome with parkinsonism features; ~90% penetrance by 70. MAPT (tau gene, chromosome 17): Various mutations → FTLD-tau; parkinsonism common; highly variable age of onset. VCP: FTD + ALS + inclusion body myopathy + Paget's disease. All inherited FTD warrants genetic counseling.", difficulty: "hard" },
    { question: "What is the genetic basis of Huntington's disease?", answer: "HD is caused by autosomal dominant CAG trinucleotide repeat expansion in the HTT gene (chromosome 4p16.3). Repeat ranges: <36 = normal; 36-39 = intermediate (reduced penetrance — may or may not develop HD); ≥40 = full penetrance (disease is certain, timing depends on repeat length); >60 = juvenile HD (Westphal variant). Anticipation: CAG repeats expand across generations, especially through paternal transmission → earlier onset in successive generations. Repeat length inversely correlates with age of onset.", difficulty: "hard" },
    { question: "What is the characteristic neuropsychological profile of Huntington's disease?", answer: "HD produces a subcortical dementia pattern: psychomotor slowing (processing speed — among the earliest and most prominent changes), executive dysfunction (planning, set-shifting, verbal fluency — letter AND category both reduced), attention deficits, and visuospatial impairment. Memory: retrieval deficit with relatively preserved encoding — recognition testing shows better performance than free recall. Psychiatric: depression most common (~40%), followed by irritability/aggression, OCD, apathy, and psychosis. Motor: chorea, oculomotor abnormalities (saccade initiation delay — an early sign), dysarthria, dysphagia.", difficulty: "hard" },
    { question: "What is the classic triad of normal pressure hydrocephalus?", answer: "Hakim-Adams triad: 1) Gait disturbance (most prominent/earliest): magnetic, apraxic gait — short shuffling steps, wide-based, difficulty initiating ('feet stuck to floor'), en-bloc turning, frequent falls. 2) Urinary incontinence: frontal disinhibition + loss of cortical bladder control; urgency precedes incontinence. 3) Cognitive impairment: frontal-subcortical pattern — executive dysfunction, psychomotor slowing, apathy; memory less affected than in AD. Mnemonic: 'Wobbly, Wet, Wacky' (gait, incontinence, cognition — in order of typical appearance). Gait responds best to VP shunting.", difficulty: "medium" },
    { question: "What are the cardinal features of progressive supranuclear palsy (PSP)?", answer: "PSP-Richardson syndrome: 1) Vertical supranuclear gaze palsy — especially impaired downward vertical saccades (earliest and most specific ocular sign; patient cannot look down voluntarily but VOR/doll's eye may be intact early). 2) Postural instability with backward falls — often in the first year, unexplained. 3) Axial rigidity — neck and trunk > limbs (opposite distribution from PD). 4) Frontal-subcortical dementia — executive dysfunction, apathy. 5) Pseudobulbar palsy — dysarthria, dysphagia, emotional incontinence. Pathology: 4R tauopathy. MRI: hummingbird sign (midbrain atrophy on sagittal view).", difficulty: "hard" },
    { question: "What is chronic traumatic encephalopathy (CTE) and what distinguishes it neuropathologically?", answer: "CTE is a progressive tauopathy found in individuals with a history of repetitive traumatic head impacts — contact sport athletes, military veterans. Pathological hallmark: perivascular accumulation of hyperphosphorylated tau (3R+4R) at the depths of cortical sulci — distinct from all other tauopathies (AD tau begins perirhinal/EC; PSP tau is subcortical). CTE CANNOT be diagnosed in vivo — only at autopsy. Clinical features (before death): behavioral/mood changes (irritability, impulsivity, depression, suicidality), cognitive decline (executive function, memory), motor symptoms (parkinsonism) in later stages.", difficulty: "hard" },
    { question: "What are the clinical features and prognosis of sporadic CJD?", answer: "Sporadic CJD: Extremely rapid progression — median survival ~4-6 months from onset; >90% die within 1 year. Clinical: subacute progressive dementia (weeks-months), cerebellar ataxia, myoclonus (startle-sensitive), cortical visual disturbances, and akinetic mutism terminally. Biomarkers: CSF 14-3-3 (sensitivity ~94%), RT-QuIC assay (high specificity), MRI DWI: cortical ribboning and basal ganglia/thalamic DWI hyperintensities. EEG: periodic sharp wave complexes (PSWC, 1-2 Hz). Variant CJD (vCJD): younger onset, psychiatric onset, pulvinar sign on MRI (thalamic DWI/FLAIR hyperintensity).", difficulty: "hard" },
    { question: "What is corticobasal syndrome (CBS) and how does its pathology relate to its presentation?", answer: "CBS is a clinical syndrome of asymmetric cortical + basal ganglia dysfunction: unilateral limb rigidity, ideomotor apraxia, dystonia, myoclonus, cortical sensory loss (astereognosis), alien limb phenomenon (limb moves involuntarily as if with its own will), and cognitive decline. CBS is a CLINICAL syndrome — the underlying pathology may be: CBD (corticobasal degeneration, 4R tau — most pathologically specific), PSP (4R tau), AD (posterior cortical atrophy variant), FTLD-TDP, or others. Asymmetric parietal and frontal atrophy (contralateral to more affected limb) on MRI.", difficulty: "hard" },
    { question: "What is the neuropsychological profile of bvFTD vs. Alzheimer's disease in early stages?", answer: "bvFTD: Profound executive dysfunction, behavioral disinhibition, apathy, profound loss of empathy and social cognition (theory of mind, emotion recognition — often most discriminating feature); relatively preserved episodic memory early (hippocampus often spared); letter fluency > category fluency; insight often poor. AD: Prominent episodic memory impairment (encoding failure, poor recognition); behavioral changes emerge later; social awareness often preserved early; category fluency > letter fluency; insight initially preserved then lost. The bvFTD patient may score relatively normally on memory tests but show striking personality change.", difficulty: "hard" },
    { question: "What is the A/T/N biomarker framework for Alzheimer's disease?", answer: "NIA-AA 2018 framework for biological staging independent of symptoms: A (Amyloid): CSF Aβ42 decreased (trapped in plaques) or Amyloid PET positive. T (Tau): CSF phospho-tau elevated or Tau PET positive (mesial temporal early). N (Neurodegeneration): FDG-PET temporoparietal hypometabolism or MRI hippocampal/entorhinal atrophy. A+/T+/N+ = full AD biology. A+/T-/N- = Alzheimer's pathological change only. Significance: decouples the biological definition of AD from clinical expression — allows preclinical detection 15-20 years before symptoms. Anti-amyloid immunotherapy is only indicated for A+ patients in early clinical stages.", difficulty: "hard" },
    { question: "What is the role of tau isoforms in distinguishing tauopathies?", answer: "Tau protein has 6 isoforms differing by inclusion of 3-repeat (3R) or 4-repeat (4R) microtubule-binding domains. 3R tau predominant: Pick's disease (frontotemporal dementia with Pick bodies). 4R tau predominant: PSP (tuft-shaped astrocytes, coiled bodies), CBD (astrocytic plaques), FTLD-tau with MAPT mutations affecting 4R exons. Mixed 3R+4R: Alzheimer's disease, CTE, argyrophilic grain disease. This distinction is not clinically apparent during life but is increasingly accessible via tau PET (which has variable binding to 3R vs. 4R aggregates) and is diagnostically important for pathological classification.", difficulty: "hard" },
    { question: "What is the significance of REM sleep behavior disorder (RBD) as a prodromal biomarker?", answer: "Isolated RBD (acting out dreams — vocalization, complex movements during REM sleep, confirmed polysomnographically) is a prodromal marker of synucleinopathy: approximately 80% of individuals with isolated RBD develop a synucleinopathy (Parkinson's disease, DLB, or MSA) within 10-15 years. RBD results from loss of the pontine REM-atonia circuit (subcoeruleus area) from early alpha-synuclein pathology (Braak PD stage 2). RBD is now considered part of the prodromal phase — making it one of the most specific biomarkers for future synucleinopathy in clinical practice.", difficulty: "hard" },
    { question: "What distinguishes the memory deficit in DLB/PDD from that in Alzheimer's disease on neuropsychological testing?", answer: "AD: ENCODING DEFICIT — hippocampal/entorhinal dysfunction prevents information from being properly stored. Both free recall AND recognition are impaired. Cues and recognition format provide little benefit. High intrusion errors. DLB/PDD: RETRIEVAL DEFICIT — frontal-subcortical dysfunction impairs accessing stored information. Free recall is impaired but recognition is relatively preserved (information was encoded and stored; retrieval is the bottleneck). Cues and recognition prompts improve performance. This distinction has practical implications: recognition memory paradigms are key to differentiating the two conditions neuropsychologically.", difficulty: "hard" },
  ];

  const insertedFC = await db.insert(flashcardsTable).values(flashcards.map(f => ({ ...f, topicId: TOPIC_ID }))).returning();
  console.log(`  ✓ ${insertedFC.length} flashcards`);

  // ─────────────────────────────────────────────────────────────────
  // QUIZ QUESTIONS
  // ─────────────────────────────────────────────────────────────────
  const regular = [
    { question: "Alzheimer's disease amyloid plaques are composed of:", optionA: "Hyperphosphorylated tau protein filaments", optionB: "Aggregated amyloid-beta (Aβ42) peptide derived from APP cleavage", optionC: "Alpha-synuclein protein aggregates", optionD: "TDP-43 protein inclusions", correctAnswer: "B", explanation: "Amyloid plaques are extracellular deposits of aggregated Aβ42 — generated by sequential β-secretase (BACE1) and γ-secretase cleavage of APP. Tau forms neurofibrillary tangles (the second hallmark). Alpha-synuclein forms Lewy bodies. TDP-43 is found in FTLD-TDP and ALS.", examOnly: false },
    { question: "A patient with DLB is agitated with visual hallucinations. Which class of medication should be AVOIDED?", optionA: "Cholinesterase inhibitors", optionB: "Typical antipsychotics (dopamine D2 blockers)", optionC: "Memantine", optionD: "Low-dose quetiapine", correctAnswer: "B", explanation: "DLB/PDD: severe dopaminergic deficit and reduced D2 receptor expression. D2-blocking antipsychotics → severe neuroleptic sensitivity: acute parkinsonism, sedation, altered consciousness, autonomic instability, sudden death risk. If antipsychotics are absolutely necessary, quetiapine or clozapine (minimal D2 blockade) are preferred.", examOnly: false },
    { question: "Sporadic Creutzfeldt-Jakob disease (sCJD) is characterized by:", optionA: "Gradual decline over 5-10 years with prominent personality change first", optionB: "Rapid-onset dementia with myoclonus; >90% mortality within 1 year", optionC: "Fluctuating cognition with visual hallucinations and parkinsonism", optionD: "Episodic memory loss with preserved language for many years", correctAnswer: "B", explanation: "Sporadic CJD: median survival ~4-6 months; >90% die within 1 year. Key features: subacute progressive dementia, cerebellar ataxia, myoclonus (startle-sensitive), cortical visual disturbances, akinetic mutism terminally. EEG: periodic sharp wave complexes; CSF 14-3-3 sensitive; MRI DWI: cortical ribboning.", examOnly: false },
    { question: "The 1-year rule distinguishes PDD from DLB based on:", optionA: "Whether memory or behavior is the primary complaint", optionB: "Whether parkinsonism clearly precedes cognitive decline by ≥1 year (PDD) or develops within 1 year of cognitive onset (DLB)", optionC: "The specific type of alpha-synuclein aggregation pattern on autopsy", optionD: "Whether levodopa improves the patient's motor symptoms", correctAnswer: "B", explanation: "PDD = established Parkinson's motor disease (≥1 year) followed by dementia. DLB = cognitive symptoms and parkinsonism within 1 year. Both share Lewy body pathology and represent a disease spectrum. The 1-year rule has diagnostic/classification utility despite the shared biology.", examOnly: false },
    { question: "The Hakim-Adams triad of normal pressure hydrocephalus consists of:", optionA: "Tremor, rigidity, and bradykinesia", optionB: "Magnetic gait, urinary incontinence, and frontal-subcortical cognitive impairment", optionC: "Visual hallucinations, fluctuating consciousness, and parkinsonism", optionD: "Aphasia, apraxia, and agnosia", correctAnswer: "B", explanation: "NPH triad (Hakim-Adams): gait disturbance (magnetic/apraxic — most prominent/earliest), urinary incontinence (frontal disinhibition), and cognitive impairment (frontal-subcortical: executive dysfunction, psychomotor slowing, apathy). Gait responds best to VP shunting.", examOnly: false },
    { question: "Huntington's disease is caused by CAG repeat expansion in HTT. Clinical disease is certain when repeat length exceeds:", optionA: "20 repeats", optionB: "36 repeats", optionC: "40 repeats", optionD: "100 repeats", correctAnswer: "C", explanation: "HD repeat ranges: <36 = normal; 36-39 = intermediate (reduced penetrance); ≥40 = full penetrance (disease certain; age depends on length). >60 repeats = juvenile HD (Westphal variant). CAG length inversely predicts age of onset — longer repeats cause earlier disease.", examOnly: false },
    { question: "The episodic memory impairment in Alzheimer's disease is best characterized as a:", optionA: "Retrieval deficit — impaired free recall but preserved recognition", optionB: "Encoding deficit — poor free recall AND poor recognition, failure to benefit from cues", optionC: "Storage deficit — rapid loss of well-consolidated remote memories", optionD: "Frontal-executive memory deficit — impaired prospective memory only", correctAnswer: "B", explanation: "AD amnesia reflects hippocampal/entorhinal dysfunction during encoding — information never properly stored. Both free recall AND recognition impaired (unlike retrieval deficits in subcortical dementias where recognition is preserved). Cued recall provides minimal benefit. This is the defining neuropsychological signature of AD versus subcortical dementia patterns.", examOnly: false },
    { question: "The most specific early eye movement finding in progressive supranuclear palsy is:", optionA: "Bilateral horizontal gaze palsy from pontine nuclei damage", optionB: "Impaired downward vertical saccades — voluntary fast downward eye movements are slow or absent while the doll's eye reflex (VOR) may initially be preserved", optionC: "Convergence-retraction nystagmus from midbrain tectum compression", optionD: "Internuclear ophthalmoplegia from MLF damage", correctAnswer: "B", explanation: "PSP-Richardson syndrome: impaired downward vertical saccades are the earliest and most specific ocular finding. The 4R tau pathology disrupts the superior colliculus and brainstem vertical gaze centers. Patients have difficulty reading, going down stairs, and eating. It is a supranuclear palsy — the vestibuloocular reflex (doll's eye/VOR) can overcome the palsy early, proving the problem is above the level of the oculomotor nuclei.", examOnly: false },
    { question: "C9orf72 repeat expansion is most strongly associated with:", optionA: "Early-onset Alzheimer's disease with amyloid angiopathy", optionB: "Frontotemporal dementia and/or ALS — often both in the same patient or family", optionC: "Huntington's disease when repeat length exceeds 40", optionD: "Progressive supranuclear palsy with 4R tau accumulation", correctAnswer: "B", explanation: "C9orf72 hexanucleotide (GGGGCC) repeat expansion is the most common genetic cause of both familial FTD and familial ALS — and FTD-ALS overlap. The same family may have members with FTD, ALS, or both. C9orf72 mutations produce FTLD-TDP pathology and are also associated with prominent psychiatric features (psychosis, anxiety).", examOnly: false },
    { question: "APOE ε4 allele affects Alzheimer's disease risk primarily by:", optionA: "Directly causing early-onset familial AD through presenilin mutations", optionB: "Impairing amyloid-beta clearance, promoting tau pathology, and accelerating neuroinflammation", optionC: "Reducing production of neprilysin, the enzyme that degrades amyloid-beta", optionD: "Increasing APP gene expression leading to amyloid overproduction", correctAnswer: "B", explanation: "APOE4 is a risk modifier for sporadic AD: it impairs Aβ clearance (glymphatic, perivascular, cellular removal), promotes tau hyperphosphorylation, dysregulates lipid metabolism, and amplifies neuroinflammatory microglial responses. One copy ~3x risk; two copies ~8-12x risk. It does not cause FAD — those are caused by PSEN1, PSEN2, or APP mutations.", examOnly: false },
  ];

  const examOnly = [
    { question: "Braak staging of neurofibrillary tau pathology in Alzheimer's disease is important because:", optionA: "It directly determines amyloid plaque burden and correlates with CSF Aβ42 levels", optionB: "Tau pathology spreads in a stereotyped transneuronal pattern from entorhinal cortex → limbic → neocortex, with each stage correlating with progressive clinical deterioration better than amyloid burden", optionC: "Braak stages predict which genetic variant (APOE2/3/4) a patient carries", optionD: "It determines eligibility for anti-amyloid immunotherapy", correctAnswer: "B", explanation: "Braak I-II: entorhinal/perirhinal → subtle memory impairment. Braak III-IV: hippocampus/amygdala → overt amnestic syndrome. Braak V-VI: association neocortex → full dementia. Tau pathology stage correlates more closely with cognitive severity than amyloid plaque burden — a clinically critical point.", examOnly: true },
    { question: "In frontotemporal dementia, bvFTD is differentiated from Alzheimer's disease most critically by:", optionA: "The presence of memory impairment — AD always has worse memory than bvFTD", optionB: "The pattern of social cognition impairment — bvFTD severely impairs theory of mind, empathy, and emotion recognition while these are relatively preserved in early AD", optionC: "Age of onset — bvFTD occurs exclusively after age 75 while AD occurs in younger patients", optionD: "The response to cholinesterase inhibitors — bvFTD responds while AD does not", correctAnswer: "B", explanation: "bvFTD hallmark: profound early social cognition impairment (theory of mind, empathy, emotion recognition), disinhibition, apathy, and executive dysfunction — while episodic memory can be relatively spared early (hippocampus often intact). In AD, social awareness and empathy are preserved early as memory fails. Social cognition tests are among the most discriminating measures.", examOnly: true },
    { question: "Why does Down syndrome (trisomy 21) lead to Alzheimer's disease pathology by age 40?", optionA: "Trisomy 21 causes overexpression of the APOE ε4 allele on chromosome 19", optionB: "The APP gene is on chromosome 21 — three copies of APP lead to Aβ overproduction, causing amyloid plaque accumulation decades earlier than in the general population", optionC: "Trisomy 21 causes PSEN1 mutations that increase γ-secretase activity", optionD: "Down syndrome individuals have reduced neprilysin, the enzyme that degrades Aβ", correctAnswer: "B", explanation: "APP (amyloid precursor protein) is on chromosome 21. Trisomy 21 provides 3 copies → ~50% increased APP expression → lifelong Aβ overproduction → amyloid plaques detectable by age 30-40 in virtually all individuals with Down syndrome. By their 60s, most develop dementia.", examOnly: true },
    { question: "The pathological hallmark that distinguishes CTE from all other tauopathies at autopsy is:", optionA: "CTE has amyloid plaques but no tau, while AD has both", optionB: "CTE shows perivascular accumulation of hyperphosphorylated tau at the depths of cortical sulci — a distribution not seen in AD, PSP, or CBD", optionC: "CTE has alpha-synuclein Lewy bodies in addition to tau tangles", optionD: "CTE shows TDP-43 inclusions exclusively, without tau pathology", correctAnswer: "B", explanation: "The pathognomonic CTE lesion: perivascular phospho-tau accumulation at the depths of cortical sulci — reflecting mechanical stress at sulcal walls during impact. This distribution is unique to CTE. AD tau begins perirhinal/entorhinal; PSP tau is subcortical brainstem/basal ganglia; CBD tau is asymmetric frontoparietal.", examOnly: true },
    { question: "Progressive supranuclear palsy (PSP) is classified as a 4R tauopathy. The postural instability finding that distinguishes it from Parkinson's disease is:", optionA: "PSP patients fall forward while PD patients fall backward", optionB: "PSP typically causes BACKWARD falls and postural instability in the first year, while PD develops instability much later and with varied fall direction", optionC: "PSP and PD have identical fall patterns, distinguished only by eye movement abnormalities", optionD: "PSP causes instability only when performing dual-task activities, unlike PD", correctAnswer: "B", explanation: "PSP-Richardson syndrome: unexplained backward falls, often in the first year of symptom onset, is one of the earliest and most characteristic features — patients fall backward without appearing to be off-balance until they hit the floor. PD patients develop postural instability later in the disease course (typically stage 3 Hoehn-Yahr) and fall in varying directions. Backward falls early in the disease, combined with vertical gaze palsy, are the clinical red flags for PSP.", examOnly: true },
    { question: "Thiamine (B1) deficiency causes Wernicke's encephalopathy primarily by:", optionA: "Disrupting dopamine synthesis in the substantia nigra", optionB: "Impairing thiamine-dependent oxidative metabolism (pyruvate dehydrogenase, α-ketoglutarate dehydrogenase), causing energy failure and excitotoxic necrosis in metabolically vulnerable regions (mammillary bodies, dorsomedial thalamus, periaqueductal gray)", optionC: "Causing demyelination of the dorsal columns and corticospinal tracts", optionD: "Reducing ACh synthesis in the nucleus basalis of Meynert", correctAnswer: "B", explanation: "Thiamine is a cofactor for pyruvate dehydrogenase and α-ketoglutarate dehydrogenase — critical oxidative metabolism enzymes. Deficiency causes metabolic failure in regions with high demand and low thiamine stores: mammillary bodies, dorsomedial thalamus, periaqueductal gray. Necrosis of mammillary bodies + dorsomedial thalamus causes the dense amnesia of Korsakoff syndrome.", examOnly: true },
    { question: "The A/T/N biomarker framework for Alzheimer's disease is significant because:", optionA: "It provides clinical staging based only on cognitive testing, replacing biomarkers", optionB: "It decouples the biological definition of AD from its clinical expression — enabling preclinical detection and biological staging years before cognitive symptoms appear, which is the basis for disease-modifying prevention trials", optionC: "It identifies which patients should receive antipsychotic treatment for behavioral symptoms", optionD: "It predicts which specific mutation (PSEN1, PSEN2, or APP) caused a given case", correctAnswer: "B", explanation: "A/T/N (NIA-AA 2018) defines AD biologically rather than clinically. A patient can be biologically 'A+' for 15-20 years before any cognitive symptoms — this preclinical window is the target for prevention trials. Anti-amyloid immunotherapies (lecanemab, donanemab) are only effective in A+/T+ patients in early clinical stages, making biomarker status essential for treatment eligibility.", examOnly: true },
    { question: "What distinguishes the memory deficit in DLB/PDD from that in Alzheimer's disease on neuropsychological testing?", optionA: "DLB/PDD shows complete anterograde amnesia with no recognition memory whatsoever", optionB: "DLB/PDD shows a retrieval deficit (impaired free recall but relatively preserved recognition), while AD shows an encoding deficit (impaired free recall AND impaired recognition)", optionC: "AD patients have better visuospatial memory than DLB/PDD patients in all cases", optionD: "DLB/PDD memory deficit primarily affects semantic rather than episodic memory", correctAnswer: "B", explanation: "AD encoding deficit (hippocampal/entorhinal dysfunction) → poor free recall AND poor recognition; cues provide minimal benefit. DLB/PDD retrieval deficit (frontal-subcortical) → poor free recall but relatively preserved recognition (information was encoded and stored; retrieval is impaired). Recognition memory paradigms are key to making this distinction in clinical neuropsychological evaluation.", examOnly: true },
    { question: "In Huntington's disease, the earliest motor sign detectable neuropsychologically is often:", optionA: "Chorea beginning in the lower limbs and spreading upward", optionB: "Oculomotor abnormalities — prolonged saccade initiation latency and impaired smooth pursuit — reflecting early striatal-frontal circuit dysfunction", optionC: "Dysphagia from early bulbar involvement", optionD: "Rigidity and bradykinesia indistinguishable from Parkinson's disease", correctAnswer: "B", explanation: "In prodromal and early HD, oculomotor abnormalities often precede overt chorea: prolonged saccade initiation latency, increased antisaccade errors (executive control of eye movements), and impaired smooth pursuit reflect early striatal-frontal circuit dysfunction. Chorea typically begins in hands/fingers and tongue. Rigidity/bradykinesia emerge in late-stage HD or in juvenile HD (Westphal variant, >60 CAG repeats).", examOnly: true },
  ];

  const allQs = [...regular, ...examOnly].map(q => ({ ...q, topicId: TOPIC_ID }));
  const insertedQs = await db.insert(quizQuestionsTable).values(allQs).returning();
  console.log(`  ✓ ${insertedQs.length} quiz questions`);

  // ─────────────────────────────────────────────────────────────────
  // STUDY GUIDE
  // ─────────────────────────────────────────────────────────────────
  const sgContent = `# Neurocognitive Disorders — Comprehensive Study Guide

---

## Overview: Classification

**Minor Neurocognitive Disorder (MCI):** Modest cognitive decline — approximately 1-2 standard deviations below the normative mean on objective testing — that does **not** impair functional independence. The patient compensates through greater effort, time, or adaptive strategies.

**Major Neurocognitive Disorder (Dementia):** Substantial cognitive decline — typically more than 2 standard deviations below the normative mean — with **functional independence impaired**. Assistance is required for instrumental or basic activities of daily living.

Both diagnoses require documented decline from a prior level of functioning (not a lifelong baseline) and must be supported by both clinical history and objective cognitive assessment. The distinction between minor and major NCD is dimensional rather than categorical — severity is a continuum.

---

## 1. Alzheimer's Disease (AD)

**Typical Age of Onset:** Sporadic late-onset AD: risk rises sharply after age 65 (prevalence ~5% at 65-74; ~13% at 75-84; ~33% at 85+). Familial early-onset AD (PSEN1, PSEN2, APP mutations): onset typically 30s-50s. Women are disproportionately affected, partly due to longevity and partly to hormonal and genetic factors.

### Epidemiology
The most common cause of dementia, accounting for 60-70% of all cases. Approximately 6.7 million Americans are currently affected. Prevalence doubles every five years after age 65. The preclinical phase — when amyloid pathology is accumulating but the patient is cognitively normal — begins approximately 15-20 years before clinical onset.

### Pathophysiology
**Amyloid cascade:** Amyloid precursor protein (APP, chromosome 21) is cleaved by β-secretase (BACE1) and γ-secretase (a complex including presenilin 1 and 2) to generate amyloid-beta (Aβ) peptides. When Aβ42 production or clearance is disrupted, it aggregates — first forming soluble oligomers (the most synaptically toxic form), then protofibrils, then the insoluble plaques (neuritic/senile plaques) visible on neuropathology. Aβ42 oligomers disrupt synaptic transmission, activate microglia, and initiate a cascade leading to tau hyperphosphorylation.

**Neurofibrillary tangles (NFTs):** Tau protein stabilizes axonal microtubules. Hyperphosphorylation causes tau to detach from microtubules → microtubule collapse → paired helical filaments → NFTs. Tau pathology spreads in a stereotyped transneuronal pattern described by Braak staging (see below). Tau pathology correlates more closely with cognitive severity than amyloid plaque burden.

**Braak staging:** Stages I-II (transentorhinal) — entorhinal cortex and perirhinal cortex, causing earliest episodic memory impairment. Stages III-IV (limbic) — hippocampus, amygdala, basal forebrain, producing overt amnestic syndrome. Stages V-VI (neocortical) — association cortex, producing full multi-domain dementia.

**Neuroinflammation:** Microglia (TREM2-regulated) initially attempt Aβ phagocytosis but become chronically dysregulated, releasing pro-inflammatory cytokines (IL-1β, TNF-α) that amplify tau phosphorylation and synaptic damage. Astrocytes become reactive (astrogliosis) and lose homeostatic functions. Neuroinflammation is now considered a core feature, not merely a consequence.

**Cholinergic loss:** Neurons of the nucleus basalis of Meynert (NBM) — the primary cortical cholinergic source — undergo 75-80% degeneration by mid-stage AD, producing the cholinergic deficit targeted by acetylcholinesterase inhibitors.

### Genetic and Modifiable Risk Factors
The most significant genetic risk factor for sporadic AD is the **APOE ε4 allele** (chromosome 19). A single copy increases risk approximately threefold; two copies (homozygous APOE ε4) increase risk approximately eight to twelvefold. APOE ε4 impairs amyloid-beta clearance through multiple pathways — reducing glymphatic and perivascular Aβ removal, impairing microglial phagocytosis, and promoting tau hyperphosphorylation. By contrast, the **APOE ε2** allele is protective, reducing risk by approximately 40% relative to the neutral APOE ε3.

Familial early-onset AD is caused by autosomal dominant mutations in three genes. **PSEN1** (presenilin-1, chromosome 14) is the most common familial AD gene, with over 400 identified mutations; it alters γ-secretase to increase the Aβ42:Aβ40 ratio, with onset typically in the 30s to 50s. **PSEN2** (chromosome 1) causes a similar mechanism with a slightly later and more variable onset. **APP** (chromosome 21) mutations near the β- and γ-secretase cleavage sites increase Aβ42 production — this same gene is triplicated in Down syndrome (trisomy 21), explaining why individuals with Down syndrome develop amyloid pathology by age 30-40 and dementia by their 60s.

The **TREM2 R47H variant** approximately doubles AD risk by impairing microglial phagocytic clearance of Aβ.

Modifiable risk factors include midlife hypertension (the most impactful single modifiable risk), diabetes mellitus, obesity, low educational attainment, social isolation, untreated hearing loss, depression, physical inactivity, smoking, and sleep disorders. Controlling blood pressure in midlife appears to have the greatest population-level impact on dementia risk reduction. Sleep apnea and insufficient sleep impair glymphatic Aβ clearance, accelerating amyloid accumulation.

### Neuropsychological Profile
The defining neuropsychological signature of AD is an **encoding deficit**: hippocampal and entorhinal cortex dysfunction prevents information from being properly stored. Both free recall and recognition are impaired — patients do not benefit from cues or recognition format. Intrusion errors (false recalls from prior lists) are common. Rapid forgetting (steep forgetting curve between immediate and delayed recall) is characteristic.

Early features: anterograde amnesia, anomia (word-finding difficulty), topographic disorientation, and semantic (category) verbal fluency more impaired than phonemic (letter) fluency. Middle-stage features: visuospatial decline, executive dysfunction, acalculia, and constructional apraxia. Late-stage features: language breakdown, limb apraxia, agnosia, and complete ADL dependence.

### Clinical Staging
Preclinical AD: biomarker-positive (amyloid-positive) but cognitively normal — a window lasting 15-20 years during which prevention interventions are being studied. MCI due to AD: measurable cognitive decline (primarily memory), biomarker-positive, intact functional independence. Mild AD: memory plus at least one other domain impaired; functional independence partially compromised; IADL difficulties. Moderate AD: multi-domain impairment; BPSD (behavioral and psychological symptoms of dementia) emerge (delusions, hallucinations, agitation); substantial daily assistance needed. Severe AD: profound impairment; minimal verbal output; immobility; dysphagia; palliative phase.

### Critical Considerations
Anti-amyloid immunotherapies (lecanemab, donanemab) represent a genuine disease-modifying advance — they slow decline in early symptomatic AD — but carry significant risks, particularly amyloid-related imaging abnormalities (ARIA), which can present as edema (ARIA-E) or microhemorrhages (ARIA-H), and are more frequent in APOE ε4 carriers. Treatment is only appropriate for A+ patients at the MCI or mild dementia stage. Administration requires regular MRI monitoring. Cholinesterase inhibitors and memantine are purely symptomatic — they do not alter disease trajectory.

Posterior cortical atrophy (PCA), the "visual variant of AD," presents with progressive visuospatial and visuoperceptual dysfunction, Balint syndrome (simultanagnosia, optic ataxia, oculomotor apraxia), and prominent parieto-occipital atrophy, with relatively preserved episodic memory early. Approximately 80% have underlying AD pathology. Logopenic variant PPA (lvPPA) presents with sentence repetition impairment, word retrieval pauses, and phonological working memory failure, also most commonly underlain by AD pathology.

### Differential Diagnosis Considerations
From DLB/PDD: AD shows encoding failure (both free recall and recognition impaired); DLB shows retrieval deficit (recognition relatively preserved). DLB also shows prominent visuospatial impairment, attention fluctuation, visual hallucinations, and parkinsonism from early in the disease. From bvFTD: FTD shows prominent behavioral and executive changes with relatively preserved early memory; AD shows early memory failure with relatively preserved social cognition and personality. From NPH: NPH shows a gait disturbance that typically precedes or is as prominent as cognitive symptoms, with a frontal-subcortical cognitive profile and the potential for improvement with CSF drainage. From depression (pseudodementia): depressed patients typically show retrieval deficits that improve with cuing, show subjective complaints disproportionate to objective deficits, and have a mood disorder history; biomarkers for AD are negative.

### Treatment
Cholinesterase inhibitors (donepezil, rivastigmine, galantamine) increase synaptic acetylcholine by inhibiting acetylcholinesterase — modest symptomatic benefit on cognition and function. Memantine (NMDA receptor antagonist) reduces excitotoxicity — used in moderate-severe AD. Anti-amyloid immunotherapies (lecanemab, donanemab) for early AD in biomarker-positive patients. Non-pharmacological: cognitive stimulation therapy, aerobic exercise (may slow hippocampal atrophy), sleep hygiene, caregiver support and education, and aggressive management of modifiable risk factors.

---

## 2. Vascular Cognitive Impairment (VCI)

**Typical Age of Onset:** Onset is strongly tied to the age at which vascular events occur. Most cases present after age 60-65, though CADASIL (the hereditary form) can cause cognitive symptoms as early as the 40s-50s, preceded by migraine with aura in the 30s.

### Epidemiology
The second most common cause of dementia, accounting for approximately 15-20% of pure cases and far more in mixed AD+VaD pathology. Highly prevalent in African American and Asian populations due to hypertension burden. Pure vascular dementia is often less common than mixed AD-vascular pathology in older populations.

### Pathophysiology
VCI encompasses several distinct cerebrovascular mechanisms. Large vessel disease (cortical strokes) causes focal deficits and stepwise cognitive deterioration. Small vessel disease — the most common mechanism — produces lacunar infarcts in the basal ganglia, thalamus, and periventricular white matter, along with white matter hyperintensities (leukoaraiosis), generating a frontal-subcortical cognitive syndrome through disruption of white matter tracts. Strategic infarcts in locations such as the thalamus, angular gyrus, or caudate nucleus produce disproportionate cognitive effects from small lesions due to the density of cortical connections in these regions. Cerebral amyloid angiopathy (CAA) — amyloid-beta deposits in superficial cortical and leptomeningeal vessel walls — weakens vessel walls, causing lobar hemorrhages and cortical microbleeds. CAA is both a distinct entity and a common comorbidity with AD.

### Genetic and Modifiable Risk Factors
The modifiable vascular risk factors are the primary risk determinants: hypertension (the single most impactful and best-established modifiable factor), diabetes mellitus, atrial fibrillation, hyperlipidemia, smoking, obesity, and obstructive sleep apnea. Midlife hypertension substantially increases dementia risk through both direct cerebrovascular injury and by accelerating AD pathology (by lowering cognitive reserve thresholds).

The primary hereditary cause of cerebral small vessel disease is CADASIL, caused by mutations in the **NOTCH3** gene (chromosome 19). This autosomal dominant condition causes diffuse thickening of small vessel walls through accumulation of NOTCH3 extracellular domain deposits. Characteristic MRI findings — white matter lesions with prominent involvement of the anterior temporal poles and external capsule — are highly specific and should prompt consideration even without a known family history. No vascular risk factors are required for CADASIL to develop.

### Neuropsychological Profile
VaD shows a frontal-subcortical pattern: prominent executive dysfunction (planning, task initiation, set-shifting, cognitive flexibility), psychomotor slowing (one of the most prominent and early features), attention and processing speed deficits, and reduced verbal fluency. Memory impairment is present but primarily reflects a retrieval deficit — recognition memory is relatively preserved, contrasting with the encoding failure of AD. Cued recall and recognition format improve performance. Gait disturbance is often an early and prominent feature, reflecting periventricular white matter involvement. Focal neurological signs may accompany cognitive impairment.

### Critical Considerations
A temporal relationship between a vascular event and cognitive change is an important diagnostic clue, but is often absent when the mechanism is cumulative small vessel disease. Stepwise progression is characteristic of large vessel disease but is not universal — small vessel disease often produces gradual decline similar to AD. Mixed AD-vascular pathology is extremely common in the elderly; the two conditions interact additively. Controlling blood pressure is the single most evidence-based intervention for both prevention and slowing of progression.

### Differential Diagnosis Considerations
From AD: VaD shows frontal-executive predominance (vs. encoding-predominant AD), relatively preserved recognition memory, psychomotor slowing, gait disturbance, and MRI evidence of vascular lesions. Stepwise progression (in large vessel disease) versus gradual decline (AD) aids distinction, though both can be gradual in small vessel disease. From NPH: NPH shows disproportionate gait apraxia and potential reversibility with shunting; VaD's gait disturbance is from WM lesion burden and does not improve with CSF removal. From DLB: DLB lacks prominent vascular MRI findings and has characteristic features (visual hallucinations, fluctuating cognition, RBD, parkinsonism).

### Treatment
Aggressive management of vascular risk factors is the cornerstone of treatment and the only intervention with strong evidence for slowing progression. Blood pressure control, antiplatelet therapy (for non-cardioembolic ischemic stroke), anticoagulation (for atrial fibrillation), glycemic control, lipid management, and smoking cessation are all indicated. No pharmacological agents are specifically approved for vascular dementia cognition, though cholinesterase inhibitors show modest benefit, particularly in mixed AD+VaD. Cognitive rehabilitation and aerobic exercise have supporting evidence.

---

## 3. Lewy Body Disorders (DLB and PDD)

**Typical Age of Onset:** Mean onset in the 60s-70s. Parkinson's disease with subsequent dementia (PDD): motor symptoms of PD typically begin in the 60s, with dementia developing an average of 10-15 years later. DLB: cognitive symptoms typically begin in the 70s. Male predominance for both PD and DLB.

### Epidemiology
DLB accounts for approximately 10-15% of all dementias and is the second most common neurodegenerative dementia after AD. Approximately 80% of people with PD develop dementia within 20 years of motor diagnosis. Lewy body disorders are systematically underdiagnosed — in part because of clinical complexity and overlap with other conditions.

### Pathophysiology
All Lewy body disorders share the same core pathology: misfolding and aggregation of alpha-synuclein (α-syn) into Lewy bodies (cytoplasmic inclusions of α-syn + ubiquitin + neurofilament) and Lewy neurites in axons. Pathology spreads in a prion-like manner between connected neurons — in PD, Braak PD staging begins in the olfactory bulb and dorsal vagal nucleus (stages 1-2) before reaching the brainstem dopaminergic nuclei (stage 3) and limbic/cortical regions (stages 4-6). In DLB, pathology is more diffuse and cortically widespread from early stages. Cholinergic deficits (nucleus basalis of Meynert) are often more severe in DLB than in AD.

### Genetic and Modifiable Risk Factors
The most common genetic risk factor for both PD and DLB is **GBA** gene mutations (glucocerebrosidase, chromosome 1). GBA mutations impair lysosomal function, reducing alpha-synuclein clearance and promoting aggregation. GBA heterozygous mutations increase PD/DLB risk approximately 5-10-fold; homozygous GBA mutations cause Gaucher disease.

**SNCA** (alpha-synuclein gene) duplications and triplications cause autosomal dominant PD/DLB through α-syn overproduction — a dose-response relationship. SNCA point mutations (A53T, A30P, E46K) cause familial parkinsonism.

**LRRK2** (leucine-rich repeat kinase 2) mutations are the most common single-gene cause of PD worldwide, with variable penetrance and variable age of onset. LRRK2 PD has a favorable prognosis relative to other genetic forms.

**REM sleep behavior disorder (RBD):** Isolated RBD — acting out dreams without atonia — is a prodromal biomarker of synucleinopathy. Approximately 80% of individuals with polysomnography-confirmed isolated RBD develop a synucleinopathy within 10-15 years.

### Neuropsychological Profile
The most prominent early neuropsychological features of DLB are visuospatial and visuoperceptual dysfunction — figure copying, visual discrimination, mental rotation, and route navigation are impaired disproportionately early. Attention fluctuations (waxing and waning cognition, sometimes within minutes or hours) are characteristic. Executive dysfunction (frontal systems involvement) is common. Memory deficit: primarily a retrieval deficit — recognition is relatively preserved, contrasting with the encoding failure of AD. Hallucinations (well-formed visual) are tied to visual cortex involvement and are a core diagnostic feature. Language is typically preserved until late stages.

### Clinical Features (DLB Core Diagnostic Criteria)
**Fluctuating cognition:** Marked variation in alertness and attention; daytime somnolence; episodes of staring or transient confusion. **Recurrent visual hallucinations:** Well-formed, detailed (people, animals), often initially non-threatening. **REM sleep behavior disorder:** Acting out dreams, often predating dementia by years — one of the most specific prodromal biomarkers. **Parkinsonism:** Bradykinesia, rigidity, rest tremor — typically occurring concurrent with or after cognitive onset (unlike PD, where motor precedes cognition by years).

The 1-year rule distinguishes PDD from DLB: PDD = motor parkinsonism established at least 1 year before dementia onset. DLB = cognitive symptoms and parkinsonism within 1 year of each other.

### Critical Considerations
The most critical safety consideration in DLB/PDD is avoidance of dopamine D2-blocking agents. Typical antipsychotics and many atypical antipsychotics can precipitate life-threatening neuroleptic sensitivity reactions in these patients — acute parkinsonism, profound sedation, impaired consciousness, autonomic instability, and sudden death. Even a single dose of haloperidol can be fatal. Metoclopramide and prochlorperazine (commonly used antiemetics) must also be avoided. If antipsychotic treatment is unavoidable for severe psychosis, quetiapine (first choice) or clozapine (with hematological monitoring) are the only relatively safe options due to their low D2 affinity.

### Differential Diagnosis Considerations
From AD: DLB shows retrieval deficit (preserved recognition memory), prominent early visuospatial impairment, attention fluctuations, visual hallucinations, parkinsonism, RBD, and DAT scan abnormality — all less characteristic of early AD. From PSP: PSP shows vertical gaze palsy (especially downward), axial rigidity, backward falls, and a distinctive frontal-subcortical cognitive pattern without the hallucinations or fluctuations of DLB. From NPH: NPH gait is magnetic/apraxic without rigidity or bradykinesia; NPH lacks visual hallucinations and fluctuating cognition. From vascular dementia: DLB lacks prominent vascular MRI findings; VaD lacks the hallmark DLB features.

### Treatment
Cholinesterase inhibitors (rivastigmine — FDA approved for PDD; also used for DLB) are particularly important given the profound cholinergic deficit — they may improve cognition and reduce behavioral symptoms. Memantine has modest evidence. Levodopa cautiously for parkinsonism — at the lowest effective dose, as it may worsen hallucinations. Clonazepam or melatonin for RBD. Actively avoid all D2-blocking drugs.

---

## 4. Frontotemporal Lobar Degeneration (FTLD)

**Typical Age of Onset:** Predominantly a young-onset dementia — the most common dementia in patients under 65. Mean onset for bvFTD and PPA variants is in the 50s-60s. Approximately 40% of FTD cases have a positive family history. C9orf72-associated FTD tends to onset in the 50s-60s; GRN-associated FTD typically onsets in the 60s-70s.

### Epidemiology
The second most common young-onset dementia (after AD) at ages 45-64, where it has approximately equal prevalence to AD in that age group. Approximately 15% of FTD patients develop concurrent ALS; approximately 15% of ALS patients develop FTD — reflecting overlapping genetic and molecular mechanisms.

### Clinical Subtypes
Behavioral variant FTD (bvFTD) presents with early behavioral and personality change — disinhibition, apathy, loss of empathy, hyperorality (excessive eating, oral exploration of objects), stereotyped and perseverative behaviors, and executive dysfunction — with relatively preserved episodic memory in early stages. Semantic variant PPA (svPPA) presents with progressive loss of word meaning — fluent speech but profound anomia, loss of single-word comprehension, surface dyslexia, and eventually prosopagnosia from left anterior temporal lobe atrophy. Nonfluent/agrammatic variant PPA (nfvPPA) presents with effortful, apraxic speech, grammatical errors (agrammatism), and phonological paraphasias from left posterior frontal-insular pathology. FTD with motor neuron disease (FTD-MND) combines bvFTD features with upper and lower motor neuron signs.

### Pathophysiology
FTLD is pathologically heterogeneous. FTLD-TDP (~50% of cases) involves pathological TDP-43 protein inclusions — classified into Types A-E with different anatomical distributions and clinical correlates. FTLD-tau (~40%) involves 3R tau (Pick's disease — characterized by Pick bodies), 4R tau (PSP and CBD), or mixed forms, depending on the mutation. FTLD-FUS (~5%) involves FUS protein inclusions and typically causes young-onset bvFTD.

### Genetic and Modifiable Risk Factors
Three major genetic causes account for the majority of familial FTLD. The **C9orf72** hexanucleotide (GGGGCC) repeat expansion (chromosome 9) is the most common cause of both familial FTD and familial ALS worldwide. The same mutation can cause pure FTD, pure ALS, or FTD-ALS overlap — even within the same family. C9orf72 FTD is associated with prominent psychiatric features including psychosis and anxiety, which can lead to misdiagnosis as a primary psychiatric disorder. It produces FTLD-TDP pathology (Types B/C).

**GRN** (progranulin, chromosome 17) haploinsufficiency leads to loss of a neurotrophic and anti-inflammatory growth factor. GRN-associated FTD typically presents with an asymmetric cortical syndrome — the neuropsychological profile depends on whether the left or right hemisphere is more affected first. Parkinsonism features are common. Penetrance is approximately 90% by age 70.

**MAPT** (microtubule-associated protein tau, chromosome 17) mutations cause FTLD-tau directly by altering tau splicing or function. Clinical presentations vary widely — some resemble bvFTD, others resemble PSP or CBS. Parkinsonism is a common feature across most MAPT mutations.

VCP mutations cause a rare syndrome combining FTD, ALS, inclusion body myopathy, and Paget's disease of bone.

### Neuropsychological Profile
bvFTD hallmark: profound impairment of social cognition — theory of mind (mentalizing), empathy, and emotion recognition are among the earliest and most sensitive markers. Executive dysfunction (planning, initiation, set-shifting, response inhibition) is prominent. Episodic memory is relatively spared early — the hippocampus is often not affected in early bvFTD. Verbal fluency: phonemic (letter) fluency is worse than semantic (category) fluency — the opposite of the AD pattern. Stereotyped, perseverative behaviors; echolalia; and environmental dependency (reflexive interaction with objects in the environment) are characteristic.

A critical distinction from AD: the bvFTD patient may score within normal limits on memory tests but show striking social behavioral change. The AD patient shows striking memory failure with relatively preserved social awareness and personality.

### Critical Considerations
FTD is frequently misdiagnosed — particularly bvFTD, which is often mistaken for primary psychiatric disorders (depression, bipolar disorder, OCD, schizophrenia), particularly when psychiatric features (psychosis, OCD-like behaviors) are prominent (as in C9orf72). The average delay from symptom onset to correct diagnosis in bvFTD is 3-4 years. Cholinesterase inhibitors and memantine have no established benefit in FTLD — the cholinergic deficit present in AD is absent in most FTD pathologies. SSRIs may reduce disinhibition, compulsive behaviors, and emotional lability.

### Differential Diagnosis Considerations
From AD: Preserved memory (relatively) with prominent behavioral change favors bvFTD; phonemic fluency worse than semantic fluency favors bvFTD. Neuroimaging showing anterior (frontal/temporal) atrophy rather than posterior (parietal/hippocampal) atrophy favors FTLD. From psychiatric disorders: the insidious progressive course, functional decline, neuropsychological testing findings, and neuroimaging changes distinguish FTD from primary psychiatric conditions. From DLB: DLB features fluctuating cognition, visual hallucinations, parkinsonism, and RBD — less characteristic of FTD. From PSP: PSP shows vertical gaze palsy, backward falls, axial rigidity, and 4R tauopathy; PSP can produce a frontal-behavioral syndrome, but the characteristic motor features and eye movement abnormalities aid distinction.

### Treatment
No disease-modifying treatments are available for any FTLD subtype. SSRIs (particularly sertraline, fluvoxamine) may reduce disinhibition, compulsive behaviors, and irritability. Antipsychotics should be used cautiously — avoid in those with tau pathology (PSP/CBD overlap) or parkinsonism. Speech-language therapy and augmentative communication for PPA variants. Genetic counseling is essential when a pathogenic C9orf72, GRN, or MAPT mutation is identified — cascade testing of at-risk family members and psychological support for presymptomatic individuals.

---

## 5. Huntington's Disease (HD)

**Typical Age of Onset:** Mean onset of motor symptoms is 35-44 years. Range is broad: juvenile HD (>60 CAG repeats) begins before age 21; late-onset HD (intermediate repeat lengths) may not manifest until age 60+. Psychiatric and cognitive symptoms often predate the motor diagnosis by years. CAG repeat length inversely predicts age of onset.

### Epidemiology
Prevalence is approximately 5-10 per 100,000 in Western populations. Autosomal dominant inheritance — 50% of offspring of an affected parent will develop HD. The disease is invariably progressive and fatal; mean survival after motor symptom onset is approximately 15-20 years.

### Pathophysiology
Expanded CAG repeats in the HTT gene encode an abnormally long polyglutamine (polyQ) tract in the huntingtin protein (mHTT). Mutant huntingtin misfolds and forms nuclear and cytoplasmic inclusions that disrupt transcription (CREB-mediated gene regulation), impair mitochondrial function, trigger apoptotic cascades, and spread pathology transneuronally. Striatal medium spiny neurons (MSNs) are selectively vulnerable — particularly D2-receptor-expressing indirect-pathway MSNs of the caudate nucleus, which are lost first. This produces disinhibition of movement → chorea. As putamen and cortex atrophy progress, the clinical picture evolves from hyperkinesia to akinesia and rigidity. The characteristic MRI finding is caudate head atrophy producing the "butterfly" or "boxcar" appearance of frontal horns.

### Genetic Risk Factors
Repeat length ranges: fewer than 36 CAG repeats is normal with no disease risk. Between 36 and 39 repeats constitutes the intermediate zone of reduced penetrance — these individuals may or may not develop HD during a normal lifespan. 40 or more repeats represents full penetrance — disease is certain; repeat length inversely predicts the age at which it will occur. More than 60 repeats causes juvenile HD (Westphal variant), which presents with rigidity, dystonia, bradykinesia, cerebellar ataxia, and seizures rather than chorea, and is transmitted predominantly by paternal inheritance.

Anticipation — expansion of CAG repeat length across generations — occurs through mechanisms favoring expansion during spermatogenesis (paternal transmission). Each generation may see earlier onset, which has profound implications for genetic counseling.

APOE ε4 genotype may modify the rate of cognitive decline in HD, though it is not a cause.

### Neuropsychological Profile
HD produces the prototype of subcortical dementia: psychomotor slowing (reduced processing speed — among the earliest and most sensitive cognitive markers), executive dysfunction (impaired planning, mental flexibility, verbal fluency for both category and letter equally), attention deficits, and visuospatial impairment. Memory: retrieval deficit with relatively preserved encoding — recognition memory outperforms free recall. Language is relatively preserved until late stages. Psychiatric symptoms: depression (most common, ~40%), irritability and aggression, OCD, apathy, and psychosis. Prodromal cognitive changes — particularly psychomotor slowing and subtle executive deficits — predate the clinical motor diagnosis by years.

Motor features include: involuntary choreiform movements beginning in the hands, fingers, and tongue; oculomotor abnormalities (saccade initiation delay — one of the earliest detectable motor signs); dysarthria; dysphagia; and gait instability.

### Critical Considerations
Presymptomatic genetic testing is available for at-risk individuals (children of affected parents who carry 50% risk) but raises profound ethical and psychological issues. A positive test predicts an invariably fatal, currently incurable illness with moderate precision of timing but no ability to prevent it. International guidelines require comprehensive pre-test and post-test psychological counseling. The majority of at-risk individuals opt not to be tested. Testing of minors is generally not recommended unless there are exceptional circumstances.

### Differential Diagnosis Considerations
From Parkinson's disease: HD produces hyperkinesia (chorea) early, not the resting tremor and rigidity of PD. HD onset in the 30s-40s rather than the 60s+ typical of sporadic PD. From drug-induced chorea: antidopaminergic drugs, estrogen, and systemic diseases (Sydenham's chorea, SLE) can cause chorea without cognitive decline. From bvFTD: behavioral changes in HD are associated with motor signs and a characteristic genetic basis; bvFTD shows behavioral change without movement disorder until late. From other causes of young-onset dementia: genetic testing for CAG repeat expansion is definitive when HD is suspected.

### Treatment
No disease-modifying treatments are currently approved. VMAT2 inhibitors (tetrabenazine, valbenazine, deutetrabenazine) reduce striatal dopamine release, reducing chorea — the primary pharmacological approach to motor management. SSRIs and SNRIs for depression and irritability. Quetiapine (preferred) for psychosis and severe psychiatric symptoms. Physical therapy for gait and balance; speech therapy for dysarthria and dysphagia; swallowing evaluation and modified diet as disease progresses. Genetic counseling for all family members with an identified mutation.

---

## 6. Progressive Supranuclear Palsy (PSP)

**Typical Age of Onset:** Almost exclusively a disease of older adults — mean onset is typically 63-65 years. PSP essentially never begins before age 50. Male predominance (~60%). Survival after symptom onset averages 5-7 years for PSP-Richardson syndrome (the classic form), shorter than most other dementias but with significant variability.

### Epidemiology
PSP is the most common atypical parkinsonian disorder — affecting approximately 5-6 per 100,000 people. It is substantially underdiagnosed, with many patients initially diagnosed with Parkinson's disease, NPH, or stroke. Sporadic in virtually all cases; no confirmed hereditary transmission in most families.

### Pathophysiology
PSP is a **4R tauopathy** — tau protein with preferential 4-repeat (4R) isoform deposition, distinct from the mixed 3R+4R of AD. Tau aggregates accumulate in neurons as globose neurofibrillary tangles, and in glia as tuft-shaped astrocytes (characteristic of PSP) and coiled bodies. The pathology is concentrated in the midbrain tegmentum, substantia nigra, subthalamic nucleus, globus pallidus, dentate nucleus of the cerebellum, and brainstem reticular formation.

The midbrain atrophy that results from this degeneration produces the **hummingbird sign** (also called the penguin sign) on sagittal MRI: the midbrain is atrophied and its profile resembles a hummingbird, with the preserved pons as the body. The **morning glory sign** (reduced cross-sectional area of the midbrain on axial imaging) is another hallmark.

The superior colliculi and their connections to vertical gaze centers are disrupted → impaired downward vertical saccades. The substantia nigra dopaminergic neurons degenerate → parkinsonism unresponsive to levodopa. The subthalamic nucleus degeneration → loss of the indirect pathway brake → postural instability.

### Clinical Features
PSP-Richardson syndrome — the classic form — presents with the combination of:

**Vertical supranuclear gaze palsy**, particularly impaired downward saccades. This is the most specific early sign — patients have difficulty reading (cannot look down at the page), going down stairs, and eating (cannot see the food). The term "supranuclear" means the deficit is above the level of the oculomotor nuclei — the vestibuloocular reflex (doll's eye maneuver) may initially overcome the palsy, confirming that CN III itself is intact. Eventually both upward and downward saccades are lost.

**Postural instability with unexplained backward falls**, often in the first year of disease. Patients fall backward without any apparent warning or attempted correction — they seem to not realize they are falling until impact. Backward falls in the first 1-2 years of a parkinsonian syndrome are a red flag for PSP, as opposed to PD where falls typically emerge years later.

**Axial rigidity** — predominantly the neck and trunk rather than the limbs. The characteristic rigid posture is one of erect or retrocollic (neck extended backward) stance — contrasting sharply with the stooped flexion of PD. The "surprised face" — frontalis overaction, wide eyes, and furrowed brow — reflects the axial rigidity.

**Frontal-subcortical dementia** — executive dysfunction, apathy, and reduced verbal fluency dominate. Episodic memory is relatively less impaired than in AD.

**Pseudobulbar palsy** — dysarthria (harsh, strained, low-volume), dysphagia, and emotional incontinence (pathological laughing or crying disproportionate to the triggering stimulus).

PSP has several clinical variants beyond Richardson syndrome: PSP-parkinsonism (PSP-P, resembles PD closely — may respond partially to levodopa initially); PSP-pure akinesia with gait freezing (PAGF); PSP-CBS (overlapping with corticobasal syndrome); PSP-progressive nonfluent aphasia; and PSP-frontal (prominent frontal dementia with minimal eye movement findings initially).

### Genetic and Modifiable Risk Factors
PSP is sporadic in nearly all cases, with no confirmed major causative genes. A common haplotype in the **MAPT** gene (H1 haplotype, particularly H1c) is significantly associated with increased PSP risk — this is a genetic susceptibility factor rather than a causative mutation. MAPT H1 haplotype also confers risk for CBD and progressive supranuclear palsy. No other genetic causes have been established for sporadic PSP, and there are no known modifiable risk factors.

### Neuropsychological Profile
PSP produces a frontal-subcortical dementia: executive dysfunction (poor planning, mental inflexibility, perseveration), apathy (often severe — one of the most prominent early features), and psychomotor slowing. Verbal fluency is reduced for both letter and category. Memory: retrieval deficit (recognition relatively preserved). Language: preserved vocabulary and syntax, though speech is dysarthric and prosodically flat. Social cognition: some impairment in theory of mind and emotion recognition, but less profound than in bvFTD. Insight: often relatively preserved early — patients and families frequently describe awareness of progressive disability.

### Critical Considerations
PSP is almost always levodopa-unresponsive or only minimally and transiently responsive — this is an important diagnostic and treatment clue, as PD shows sustained levodopa benefit. The failure to respond to adequate levodopa trials (1,000 mg/day for at least 3 months) in a patient with parkinsonism should raise suspicion for PSP, CBD, MSA, or other atypical parkinsonism. Dysphagia in PSP is severe and a leading cause of aspiration pneumonia — the primary cause of death. Botulinum toxin may be helpful for focal dystonia. Prism glasses can partially compensate for the gaze palsy.

### Differential Diagnosis Considerations
From Parkinson's disease: PD shows resting tremor (rare in PSP), flexed posture (vs. PSP's extended/retrocollic posture), excellent sustained levodopa response, and eye movements are typically preserved until late. Backward falls occur later. From NPH: NPH gait is magnetic/apraxic without rigidity; NPH lacks eye movement abnormalities; NPH can improve with LP. From DLB: DLB has fluctuating cognition, visual hallucinations, and RBD not seen in PSP. From CBS: CBS is more asymmetric (one limb more affected), shows alien limb phenomenon, and ideomotor apraxia — distinguishing from the symmetric axial rigidity of PSP, though the two can co-exist pathologically (PSP-CBS variant). From bvFTD: FTD can resemble PSP early (apathy, executive changes) but lacks the eye movement palsy and characteristic falls of PSP.

### Treatment
No disease-modifying treatments exist for PSP. Levodopa trials should be attempted (some patients have partial, temporary benefit) and continued only if there is meaningful response. Physical therapy with intensive balance training reduces fall risk. Weighted walkers (front-weighted) can compensate for backward fall tendency. Speech therapy and modified diet textures for dysphagia; feeding tube consideration when aspiration risk becomes high. Botulinum toxin for blepharospasm and focal dystonia. Prism glasses for gaze palsy compensation. Careful fall prevention is critical throughout.

---

## 7. Normal Pressure Hydrocephalus (NPH)

**Typical Age of Onset:** Idiopathic NPH (iNPH) almost exclusively affects adults over 60, with prevalence increasing substantially after 70. Secondary NPH (from SAH, meningitis, or trauma) can affect younger adults if the precipitating event occurs earlier.

### Epidemiology
Prevalence of approximately 3-4% in those over 65 with cognitive impairment. Substantially under-recognized and under-treated, despite its potential reversibility making it one of the few treatable causes of dementia. Idiopathic NPH has no identified cause; secondary NPH follows a specific precipitating event.

### Pathophysiology
Impaired CSF reabsorption at the arachnoid granulations — despite normal CSF opening pressure (≤20 cmH₂O on LP) — leads to ventricular enlargement. The enlarged ventricles stretch and compress periventricular white matter tracts, particularly those connecting the frontal cortex to the basal ganglia, thalamus, and spinal cord. This explains the frontal-subcortical cognitive syndrome, the gait apraxia, and the bladder dysfunction. The precise mechanism of impaired reabsorption in iNPH is poorly understood — venous hypertension and glymphatic dysfunction have been implicated.

### Genetic and Modifiable Risk Factors
No specific genetic causes have been identified for idiopathic NPH. Prior subarachnoid hemorrhage, meningitis, head trauma, cardiac surgery, and aqueductal stenosis are associated with secondary NPH.

### Neuropsychological Profile
Frontal-subcortical dementia: executive dysfunction (working memory, planning, mental flexibility, processing speed), psychomotor slowing (bradyphrenia), and attention deficits. Memory: retrieval deficit (improves with cues and recognition format; notably less severe than in AD). Language: relatively preserved. Apathy is prominent; depression is common. The critical feature is potential reversibility — all three triad components (gait, cognition, incontinence) can improve with VP shunting. Gait improvement is the most robust and rapid; cognitive improvement develops over months; urinary improvement is intermediate.

### Clinical Features (Hakim-Adams Triad)
**Gait disturbance** (most prominent and typically earliest): magnetic or apraxic gait — short shuffling steps, wide-based, difficulty initiating walking (freezing), en-bloc turning (cannot turn in segments), and frequent unexplained falls. The patient appears as if their feet are "stuck to the floor." Resembles parkinsonism but without resting tremor or rigidity.

**Urinary incontinence:** Frontal disinhibition of bladder control combined with loss of cortical suppression of detrusor contractions. Urgency typically precedes frank incontinence.

**Cognitive impairment:** Frontal-subcortical pattern — executive dysfunction, psychomotor slowing, apathy — generally less severe than memory-predominant dementias.

Diagnostic workup: MRI showing ventriculomegaly disproportionate to sulcal widening (Evans index >0.3 on axial scan) and DESH (disproportionately enlarged subarachnoid spaces in high convexity/parasagittal region). Large-volume LP (30-50 mL removal) with gait assessment before and after — improvement predicts shunt response. Extended lumbar drainage (5 days) or infusion testing for uncertain cases.

### Critical Considerations
NPH is frequently misdiagnosed as AD, PD, or depression. The key distinguishing feature is that the gait disturbance is prominent and often presents concurrently with or even before significant cognitive impairment — whereas in AD, gait is typically preserved until late stages. The magnetic gait may be confused with parkinsonian gait (but NPH lacks resting tremor, rigidity, and bradykinesia beyond the gait itself). Response to a large-volume LP tap test is the most practical bedside predictor of shunt response — a patient who walks measurably better after removing 30-50 mL of CSF is likely to benefit from permanent shunting.

### Differential Diagnosis Considerations
From AD: NPH's gait disturbance and incontinence are disproportionate to cognitive impairment (vs. AD where gait is preserved until late). MRI in NPH shows ventriculomegaly; AD shows hippocampal atrophy. CSF tap test improvement is not seen in AD. From PD: PD has resting tremor, rigidity, and levodopa response that NPH lacks. From VaD: VaD has periventricular WM lesion burden on MRI; NPH's WM changes are from periventricular stretch; they can co-occur. From depression: depression does not cause gait apraxia or incontinence.

### Treatment
Ventriculoperitoneal (VP) shunting is the primary treatment — gait improvement is most robust and occurs within days to weeks. Cognitive improvement typically requires months to fully emerge. Programmable valves allow post-operative pressure adjustment without re-operation. Large-volume LP serves as both a diagnostic tap test and temporary symptom relief. Serial LPs are sometimes used as a bridge or for patients who are poor surgical candidates.

---

## 8. Traumatic Brain Injury (TBI) and Chronic Traumatic Encephalopathy (CTE)

**Typical Age of Onset:** TBI occurs across the lifespan; falls are the leading cause in the elderly (>75 years, highest mortality) while sports-related and assault-related TBI peak in adolescents and young adults. CTE is a delayed consequence of repetitive head trauma — symptom onset is typically in the 40s-70s, often decades after the period of head trauma exposure.

### Epidemiology
Approximately 2.8 million TBI-related emergency department visits, hospitalizations, and deaths occur annually in the US. Falls account for the majority, particularly in the elderly; motor vehicle accidents, sports, and assault are leading causes in younger people. Mild TBI (concussion) accounts for 75-90% of all TBIs. CTE is diagnosed exclusively at autopsy — population-level prevalence is unknown, but is substantially elevated in former contact sport athletes with prolonged careers.

### Pathophysiology
**Primary injury:** Mechanical forces produce diffuse axonal injury (DAI) — axonal shearing at gray-white matter junctions from rotational acceleration-deceleration — and focal contusions (temporal and frontal poles are most vulnerable due to irregular skull base).

**Secondary injury** (minutes to days following): Excitotoxicity from massive glutamate release, ionic imbalance (Na+/K+ pump failure), mitochondrial dysfunction, free radical production, blood-brain barrier breakdown, neuroinflammation, and cerebral edema.

**CTE:** Repetitive subconcussive and concussive impacts cause repetitive axonal injury → tau accumulation, beginning perivascularly at the depths of cortical sulci (the hallmark distribution). This 4R+3R mixed tau pathology spreads progressively from sulcal epicenters across the cortex. CTE is definitively diagnosed only at autopsy. Antemortem plasma p-tau217 and tau PET are under investigation as potential in-vivo biomarkers.

### Genetic and Modifiable Risk Factors
**APOE ε4** is associated with worse cognitive outcome after TBI and may accelerate CTE-related tau accumulation. Number and severity of cumulative head impacts — not just diagnosed concussions — is the primary risk factor for CTE; subconcussive exposure may matter as much as concussive events. Prior TBI, age, substance use (alcohol), and pre-existing psychiatric conditions worsen recovery outcomes. Second impact syndrome — a second concussion before complete recovery from the first — can cause catastrophic and rapidly fatal cerebral edema in young athletes through loss of cerebrovascular autoregulation.

### Neuropsychological Profile
**Mild TBI (concussion):** Attention, concentration, processing speed, and working memory — typically resolves within days to weeks. Persistent symptoms beyond 3 months = post-concussion syndrome (PCS), which is strongly influenced by biopsychosocial factors (anxiety, sleep, expectations). **Moderate-severe TBI:** Executive dysfunction (frontal systems most vulnerable to DAI), processing speed, learning and memory, attention, and behavioral dysregulation. Anosognosia (reduced awareness of one's own deficits) is common after frontal injury. Emotional and behavioral sequelae: depression, anxiety, irritability, impulsivity, PTSD, and personality change. **CTE (clinical, before death):** Behavioral and mood changes (irritability, impulsivity, depression, suicidality) typically precede cognitive decline; motor symptoms (parkinsonism, ataxia) emerge in later stages.

### Critical Considerations
CTE cannot be diagnosed during life with current clinical or imaging tools — this is a critical limitation for patients, families, and clinicians. No biomarker currently allows definitive antemortem CTE diagnosis, though ongoing research with tau PET and blood biomarkers is promising. Second impact syndrome, while rare, is a neurosurgical emergency — any suspected second concussion before full recovery from the first warrants immediate removal from activity.

The graduated return-to-play (RTP) protocol for sports concussion is evidence-based and requires complete symptom resolution at rest before initiating stepwise activity progression — each stage at least 24 hours apart. Full contact activity is not permitted until all stages are passed symptom-free.

### Differential Diagnosis Considerations
From AD: TBI/CTE history, younger age of onset (relative to sporadic AD), prominent behavioral symptoms early (irritability, impulsivity, mood), and slower-progressing memory decline (relative to AD) may help distinguish. From bvFTD: CTE behavioral changes overlap substantially with bvFTD; the history of head trauma exposure and the characteristic pathological pattern (sulcal-depth perivascular tau) at autopsy distinguish them. From PTSD: PTSD and mild TBI frequently co-occur in military veterans and can be difficult to distinguish clinically; both can cause concentration, memory, and sleep difficulties without the specific neuropathological changes of TBI/CTE.

### Treatment
**Acute TBI:** Symptom management (graduated rest, then graduated return to activity), avoid NSAIDs and anticoagulants acutely, manage ICP in severe TBI, treat secondary injuries. **Post-concussion syndrome:** Graduated aerobic exercise (shown to accelerate recovery — NOT complete rest, which is now known to prolong symptoms); cognitive rehabilitation; treat mood, sleep, and headache comorbidities; psychoeducation to prevent symptom amplification. **Moderate-severe TBI:** Inpatient rehabilitation, cognitive rehabilitation (errorless learning, compensatory strategies), vocational rehabilitation, long-term community support. **CTE:** No disease-modifying treatment; symptomatic management of mood (SSRIs, mood stabilizers) and behavioral dysregulation; prevention through rule changes, improved protective equipment, and public awareness.

---

## 9. Prion Diseases

**Typical Age of Onset:** Sporadic CJD (the most common form): median onset in the 60s. Familial CJD (PRNP mutations): onset may be earlier, depending on the specific mutation. Variant CJD (vCJD — linked to BSE exposure): distinctive for its young age of onset (mean ~28 years, range 12-74).

### Epidemiology
Extremely rare: approximately 1-2 cases per million people per year (CJD). Sporadic CJD accounts for approximately 85% of all prion disease; familial CJD (from PRNP gene mutations) approximately 10-15%; variant CJD has affected fewer than 250 people worldwide (primarily in the UK following the BSE/mad cow disease epidemic of the 1980s-90s); iatrogenic CJD from contaminated dura mater, corneas, or pituitary-derived growth hormone is now rare. All forms are invariably fatal — no treatments alter disease course.

### Pathophysiology
Prion protein exists normally as PrPc (cellular form). In prion diseases, misfolded PrPsc (scrapie form) acts as a template, inducing normal PrPc to convert to PrPsc in a self-propagating cascade. PrPsc is protease-resistant, accumulates, and causes spongiform degeneration — vacuolation of the neuropil producing the characteristic "sponge-like" appearance. The PRNP gene (chromosome 20) encoding prion protein has polymorphisms (e.g., codon 129 Met/Val) that influence susceptibility: all vCJD cases have been homozygous Met/Met at codon 129.

### Clinical Features by Form
**Sporadic CJD:** The prototype of the rapidly fatal dementia — median survival 4-6 months; >90% die within 1 year. Subacute progressive dementia (weeks to months), cerebellar ataxia, myoclonus (often startle-sensitive), cortical visual disturbances, and akinetic mutism terminally. Biomarkers: CSF 14-3-3 protein (sensitive but not specific), CSF total-tau (often dramatically elevated), RT-QuIC assay (high specificity for prion seeding activity in CSF or nasal brushing). MRI DWI: cortical ribboning (gyral DWI restriction) and basal ganglia/thalamic hyperintensities. EEG: periodic sharp wave complexes (PSWC, 1-2 Hz) — classic but present in only ~60-70% of sCJD.

**Variant CJD:** Younger age (~28 years), psychiatric onset (depression, anxiety, personality change) before dementia, painful dysesthesias, and the pulvinar sign on MRI (bilateral thalamic DWI/FLAIR hyperintensity, particularly the "hockey stick" sign of pulvinar + dorsomedial thalamic hyperintensity). Slower progression than sCJD (median survival ~14 months). Prion protein detectable in lymphoid tissue (tonsil biopsy).

**Familial/Gerstmann-Sträussler-Scheinker syndrome (GSS) and Fatal Familial Insomnia (FFI):** PRNP mutations. FFI selectively destroys thalamic nuclei → progressive untreatable insomnia, autonomic failure, and death.

### Critical Considerations
CJD is a reportable disease and must be handled with strict infection control precautions — prions are resistant to standard autoclaving, alcohol, formalin, and UV radiation. Surgical instruments exposed to high-risk CJD tissue require special decontamination protocols. Lumbar puncture should be performed when CJD is suspected for biomarker analysis, but brain biopsy is rarely indicated (diagnosis confirmed at autopsy). Early diagnosis is important for appropriate infection control and family counseling, though no treatment alters prognosis. Psychiatric prodrome (particularly in younger patients) may delay diagnosis.

### Differential Diagnosis Considerations
From AD: AD progresses over years to decades; CJD progresses over weeks to months. Myoclonus and cerebellar ataxia are characteristic of CJD, not typical AD. MRI changes (cortical ribboning, basal ganglia signal) are specific to CJD. From DLB: DLB also progresses rapidly relative to AD but still over years; DLB has visual hallucinations and parkinsonism, not the myoclonus and cerebellar findings of CJD. From autoimmune encephalitis: autoimmune encephalitis (anti-NMDAR, anti-LGI1, etc.) can cause rapid cognitive decline with seizures and psychiatric features but is treatable and has specific antibody biomarkers — critically important to exclude as a potentially reversible differential. From metabolic encephalopathy: delirium from systemic causes (electrolyte disorders, hepatic encephalopathy, thyroid disease) can mimic CJD acutely but is typically more fluctuating and related to a systemic precipitant.

### Treatment
No disease-modifying treatments exist for any prion disease. Care is palliative and supportive. Clonazepam, valproate, or levetiracetam may partially suppress myoclonus. Symptom management for anxiety and distress. Early palliative care integration is appropriate given the invariably fatal prognosis. Psychological support for families is essential.`;

  const [sg] = await db.insert(studyGuidesTable).values({
    topicId: TOPIC_ID,
    title: "Neurocognitive Disorders — Comprehensive Study Guide",
    content: sgContent,
  }).returning();
  console.log(`  ✓ Study guide id=${sg.id}`);

  const [exam] = await db.insert(practiceExamsTable).values({
    topicId: TOPIC_ID,
    title: "Neurocognitive Disorders Practice Exam",
    timeLimit: 60,
    passingScore: 70,
  }).returning();

  const allQsDb = await db.select({ id: quizQuestionsTable.id }).from(quizQuestionsTable).where(eq(quizQuestionsTable.topicId, TOPIC_ID));
  await db.insert(practiceExamQuestionsTable).values(allQsDb.map((q, i) => ({ examId: exam.id, questionId: q.id, questionOrder: i + 1 })));

  console.log(`\n✅ Neurocognitive Disorders v2 complete!`);
  console.log(`   Flashcards: ${insertedFC.length} | Questions: ${insertedQs.length} | Study guide: id=${sg.id}`);
}

rework().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
