import type { ComponentType } from "react";
import { ArrowRight, BookOpen, Brain, CalendarDays, Check, ChevronRight, LayoutDashboard, Library, Target, Trophy } from "lucide-react";
import "./_group.css";

const brain = "/__mockup/images/psychpro-chrome-brain.webp";
const glass = "/__mockup/images/psychpro-teal-glass.webp";

function Sidebar({ eppp = false }: { eppp?: boolean }) {
  const items: Array<[string, ComponentType<{ size?: number; className?: string }>]> = eppp ? [["EPPP Dashboard", LayoutDashboard],["Practice Exams", Target],["Study Plan", CalendarDays],["Domain Review", BookOpen],["Resources", Library]] : [["Dashboard", LayoutDashboard],["Courses", BookOpen],["Study Lab", Brain],["Brain Lab", Brain],["Progress", Trophy],["Resources", Library]];
  return <aside className="pp-sidebar"><span className="pp-wordmark">PSYCHPRO</span><p className="pp-navcap">Learn</p>{items.map(([label, Icon], i) => <div className={`pp-nav ${i === 0 ? "active" : ""}`} key={label}><Icon />{label}</div>)}<div className="pp-user"><span className="pp-avatar">MC</span>Maya Chen<br/><span style={{marginLeft:27}}>Master plan</span></div></aside>;
}
function Shell({ children, type, eppp = false }: { children: React.ReactNode; type: string; eppp?: boolean }) {
 return <section className={`pp-page ${type}`}><div className="pp-page-label"><span>{eppp ? "EPPP DASHBOARD" : "MAIN DASHBOARD"}</span><span>PsychPro / demo</span></div><div className="pp-app"><Sidebar eppp={eppp}/>{children}</div></section>;
}
function Progress({ value }: { value:number }) { return <div className="pp-progress"><span style={{width:`${value}%`}} /></div>; }
function Week() { return <div className="pp-week">{[1,1,1,1,1,0,0].map((on,i)=><span className={on?"on":""} key={i}/>)}</div>; }
function DomainList({ compact=false }: {compact?:boolean}) { return <div className={`pp-domains ${compact?"pp-domaincompact":""}`}>{[["Biological bases",72],["Assessment & diagnosis",64],["Intervention",58],["Ethics & legal",81]].map(([n,v])=><div className="pp-domain" key={String(n)}><span>{n}</span><Progress value={Number(v)}/><span>{v}%</span></div>)}</div>; }
function MainCompact() { return <Shell type="compact"><main className="pp-main"><div className="pp-topline"><div><p className="pp-eyebrow">Thursday · study workspace</p><h2 className="pp-heading">Good afternoon, Maya</h2></div><img src={brain} className="pp-brain"/></div><section className="pp-primary"><div className="pp-continue"><p className="pp-eyebrow">Continue studying</p><h3>Psychological Assessment</h3><p>Return to your active course at the exact point you left off.</p><Progress value={68}/><div className="pp-actionline"><span className="pp-card-meta">12 of 18 lessons complete</span><button className="pp-chrome-btn dark">Resume lesson <ArrowRight/></button></div></div><div className="pp-statside"><div className="pp-statcell"><p className="pp-mini-label">Current streak</p><p className="pp-stat" style={{margin:"7px 0 0"}}>12 <small style={{fontSize:9}}>days</small></p><Week/></div><div className="pp-statcell"><p className="pp-mini-label">Weekly progress</p><p className="pp-card-meta">4 focused sessions · 3h 18m</p><Progress value={57}/></div></div></section><section className="pp-recommendations"><p className="pp-eyebrow">Recommended for you</p><div className="pp-recommend-grid"><article className="pp-card pp-recommend"><h3 className="pp-card-title">Review: Reliability & validity</h3><p className="pp-card-meta">15 min · Assessment foundations</p><button className="pp-chrome-btn" style={{marginTop:10}}>Start review <ChevronRight/></button></article><article className="pp-card pp-recommend"><h3 className="pp-card-title">New: Trauma-informed care</h3><p className="pp-card-meta">32 min · Clinical practice</p><button className="pp-chrome-btn" style={{marginTop:10}}>Open course <ChevronRight/></button></article></div></section><div className="pp-secondary"><aside className="pp-spotlight"><p className="pp-eyebrow">Spotlight</p><h4>How memory changes under pressure</h4><p>A concise featured reading from the PsychPro community.</p></aside><article className="pp-card" style={{padding:15}}><p className="pp-eyebrow">Your progress</p><p className="pp-stat" style={{margin:"8px 0 0"}}>47%</p><p className="pp-card-meta">Overall course completion</p><Progress value={47}/></article></div></main></Shell>; }
function EpppCompact() { return <Shell type="compact" eppp><main className="pp-main"><div className="pp-topline"><div><p className="pp-eyebrow">EPPP Mastery Suite</p><h2 className="pp-heading">Exam preparation</h2></div><button className="pp-chrome-btn"><CalendarDays/> Jun 18, 2026</button></div><section className="pp-compact-eppp"><div><p className="pp-mini-label">Exam readiness</p><p className="pp-stat" style={{margin:"8px 0 0"}}>64%</p><Progress value={64}/></div><div><p className="pp-mini-label">Study streak</p><p className="pp-stat" style={{margin:"8px 0 0"}}>12 days</p><Week/></div><div><p className="pp-mini-label">Exam countdown</p><p className="pp-stat" style={{margin:"8px 0 0"}}>38</p><p className="pp-card-meta">days remaining</p></div></section><section className="pp-eppp-action"><article className="pp-actioncard"><p className="pp-eyebrow">Next best action</p><h3 className="pp-card-title" style={{fontSize:14,marginTop:8}}>Domain review: Intervention</h3><p className="pp-card-meta">Target the lowest-confidence domain before your next practice exam.</p><button className="pp-chrome-btn dark" style={{marginTop:14}}>Begin 20 questions <ArrowRight/></button></article><aside className="pp-spotlight"><p className="pp-eyebrow">This week</p><h4>2 of 3 planned sessions</h4><p>Keep Thursday's review and you will meet your weekly study target.</p></aside></section><article className="pp-card pp-domaincard"><p className="pp-eyebrow">Domain progress</p><DomainList/></article></main></Shell>; }

function MainToday(){return <Shell type="today"><main className="pp-main"><header className="pp-focus-head"><p className="pp-eyebrow">Today · Thursday, May 11</p><h2 className="pp-heading">A clear place to begin</h2><p className="pp-subtitle">One meaningful session is enough for today.</p></header><div className="pp-focus-body"><section className="pp-next"><p className="pp-eyebrow">Your next study action</p><h3>Review 18 cards due today</h3><p>Assessment foundations · estimated 14 minutes</p><img src={brain} className="pp-brain"/><button className="pp-chrome-btn dark">Start review <ArrowRight/></button></section><div className="pp-agenda"><article className="pp-card" style={{padding:14}}><p className="pp-eyebrow">Then, if you have time</p><div className="pp-listrow"><span>Continue Psychological Assessment</span><span>18 min</span></div><div className="pp-listrow"><span>Read: Clinical interviewing</span><span>12 min</span></div></article><article className="pp-card" style={{padding:14}}><p className="pp-eyebrow">Completed today</p><div className="pp-listrow"><span><Check size={11}/> Ethics practice set</span><span>8 / 10</span></div><div className="pp-listrow"><span>Morning study plan</span><span>done</span></div></article></div><section className="pp-mutedstat"><div><p className="pp-mini-label">Course progress</p><p className="pp-stat" style={{margin:"7px 0 0"}}>47%</p></div><div><p className="pp-mini-label">Current streak</p><p className="pp-stat" style={{margin:"7px 0 0"}}>12 days</p></div><div><p className="pp-mini-label">This week</p><p className="pp-stat" style={{margin:"7px 0 0"}}>3h 18m</p></div></section></div></main></Shell>}
function EpppToday(){return <Shell type="today" eppp><main className="pp-main"><header className="pp-focus-head"><p className="pp-eyebrow">EPPP Mastery Suite · today</p><h2 className="pp-heading">Prepare with purpose</h2><p className="pp-subtitle">Your plan is centered on the work that needs attention now.</p></header><div className="pp-eppp-focus"><section className="pp-priority"><div className="pp-priority-grid"><div><p className="pp-eyebrow">Today's priority</p><h3>Intervention: targeted question set</h3><p className="pp-card-meta">20 questions selected from your lowest-confidence domain.</p></div><button className="pp-chrome-btn dark">Begin session <ArrowRight/></button></div></section><div className="pp-agenda"><article className="pp-card" style={{padding:14}}><p className="pp-eyebrow">Plan for today</p><div className="pp-listrow"><span>Targeted question set</span><span>25 min</span></div><div className="pp-listrow"><span>Review missed questions</span><span>12 min</span></div><div className="pp-listrow"><span>Schedule practice exam</span><span>optional</span></div></article><article className="pp-card" style={{padding:14}}><p className="pp-eyebrow">Recent insight</p><h3 className="pp-card-title" style={{marginTop:9}}>Ethics is trending upward</h3><p className="pp-card-meta">81% across your last three sessions. Keep Intervention as your focus.</p><Progress value={81}/></article></div><section className="pp-readiness"><div><p className="pp-mini-label">Exam readiness</p><p className="pp-stat" style={{margin:"8px 0 0"}}>64%</p><Progress value={64}/></div><div><p className="pp-mini-label">Exam date</p><p className="pp-stat" style={{margin:"8px 0 0"}}>38 <small style={{fontSize:9}}>days</small></p><p className="pp-card-meta">June 18, 2026</p></div></section></div></main></Shell>}

function MainVisual(){return <Shell type="visual"><main className="pp-main"><header className="pp-visual-head"><div className="pp-titleblock"><p className="pp-eyebrow">Study workspace</p><h2 className="pp-heading">Welcome back <img src={brain} className="pp-titlebrain"/></h2><p className="pp-subtitle">Your courses, practice, and community in a steady rhythm.</p></div><aside className="pp-glass pp-glassart"><img src={glass}/></aside></header><div className="pp-gridbody"><article className="pp-card pp-studyhero"><p className="pp-eyebrow">Continue studying</p><h3>Psychological Assessment</h3><p>Resume at Lesson 12: Observational methods and clinical inference.</p><Progress value={68}/><div className="pp-workline"><span>12 / 18 lessons</span><span>68% complete</span></div><button className="pp-chrome-btn dark">Resume lesson <ArrowRight/></button></article><article className="pp-card"><p className="pp-eyebrow">Due today</p><h3 className="pp-card-title" style={{marginTop:8}}>18 review cards</h3><button className="pp-chrome-btn" style={{marginTop:10}}>Start 14-min review</button></article><article className="pp-card"><p className="pp-eyebrow">Recommended</p><h3 className="pp-card-title" style={{marginTop:8}}>Trauma-informed care</h3><p className="pp-card-meta">A 32 minute clinical practice course.</p></article><div className="pp-gridstats"><div><p className="pp-mini-label">Streak</p><p className="pp-stat" style={{margin:"6px 0 0"}}>12d</p></div><div><p className="pp-mini-label">Total progress</p><p className="pp-stat" style={{margin:"6px 0 0"}}>47%</p></div></div></div></main></Shell>}
function EpppVisual(){return <Shell type="visual" eppp><main className="pp-main"><header className="pp-visual-head"><div className="pp-titleblock"><p className="pp-eyebrow">EPPP Mastery Suite</p><h2 className="pp-heading">Readiness overview <img src={brain} className="pp-titlebrain"/></h2><p className="pp-subtitle">A consistent view of where to focus before exam day.</p></div><aside className="pp-glass pp-glassart"><img src={glass}/></aside></header><div className="pp-eppp-grid"><article className="pp-card pp-readinesscard"><p className="pp-eyebrow">Exam readiness</p><p className="pp-readiness-big">64%</p><p className="pp-card-meta">Based on recent practice and mastery across domains.</p><Progress value={64}/><div className="pp-workline"><span>Exam date</span><span>38 days</span></div><button className="pp-chrome-btn dark">Review study plan <ArrowRight/></button></article><article className="pp-card"><p className="pp-eyebrow">Next action</p><h3 className="pp-card-title" style={{marginTop:8}}>Intervention question set</h3><p className="pp-card-meta">20 tailored questions · 25 min</p><button className="pp-chrome-btn" style={{marginTop:10}}>Begin practice <ArrowRight/></button></article><article className="pp-card"><p className="pp-eyebrow">Study rhythm</p><p className="pp-stat" style={{margin:"8px 0 0"}}>12 days</p><Week/><p className="pp-card-meta">4 active days this week</p></article><article className="pp-card" style={{gridColumn:"1 / -1"}}><p className="pp-eyebrow">Domain progress</p><DomainList compact/></article></div></main></Shell>}

function Board({ name, description, children }: {name:string;description:string;children:React.ReactNode}){return <div className="pp-board"><header className="pp-board-head"><div><p className="pp-board-kicker">PsychPro · layout direction</p><h1 className="pp-board-title">{name}</h1></div><p className="pp-board-note">{description}</p></header><div className="pp-comparison">{children}</div></div>}
export function CompactBoard(){return <Board name="01 / Compact workbench" description="Useful course work leads. Supporting metrics stay near the action; Spotlight becomes a contained lower-priority module."><MainCompact/><EpppCompact/></Board>}
export function TodayBoard(){return <Board name="02 / Today focus" description="A guided agenda removes choice friction: one next action first, then a concise sequence and context kept intentionally secondary."><MainToday/><EpppToday/></Board>}
export function VisualBoard(){return <Board name="03 / Restrained visual grid" description="A shallow branded header contains the glass artwork. A shared, modular grid creates a deliberate rhythm across both dashboards."><MainVisual/><EpppVisual/></Board>}